### PR TITLE
Elizabeth Changes

### PR DESCRIPTION
**Pull request by pontiferous**
AW geeze I hope I'm doin' this right.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @pontiferous!

This is almost ready to go! There's just a few thing we need to address, and we'll be set.

1) It looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's.

2) Make sure that you are linking to your custom stylesheet (elizabeth-style.css) from your advice page. Right now you are linking to the main stylesheet (css/style.css)

3) We are also going to need a link in the main index.html file that will point to your advice page, so that folks and read and benefit from your words of advice. :)

Once you make those changes, you can add, commit, and push your 'skillcrush-104' branch up once more, which will automatically update your pull request. Then we should be all set to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by redrambles** [comment]
Hey @pontiferous!

Ok - you are now super super super close! You have resolved every point I had listed earlier.
The thing is that though you changed the link from css/style.css to css/elizabeth-style.css in your advice page (Yay!) - you also did the same for the main index.html page. Oops! The main index.html page should be linking to the css/style.css stylesheet, so we'll need you to change that back.

While still in your 'skillcrush-104' branch, once you make that teeny correction, go ahead and add (git add -A) and commit (git commit -m "your message here") and then push up your branch once more (git push origin skillcrush-104) and we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by pontiferous** [comment]
AW geeze. @redrambles quick weird question. When I'm looking in my skillcrush-104 folder, I'm not seeing the index.html file. How to I pull it again so that I can change the css?

**Comment by pontiferous** [comment]
magical deletion

Not sure if the png would work, but it literally says that it got deleted. As did another html file?

**Comment by redrambles** [comment]
Hey there! Ok so let's 'undelete' these files by running:

`git checkout -- .`

You should now be able to 'see' and work on the index.html file. Keep us posted!

**Comment by pontiferous** [comment]
Hurray! It worked!

**Pull request closed without merging**
