### PR TITLE
Edits

### PR DESCRIPTION
**Pull request by ebooker2013**
Added my Advice section

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @ebooker2013 !

This is great - there is just one file that we need you to remove, `advice/advice-.html`. Once you do, you'll need to run `git add -A` followed by `git commit -m "your message here"` in order to add and commit that change.

Once that is taken care of, you'll just need to push up your branch once more (`git push origin edits`), which will automatically update this pull request - and then we should be good to go!

Let us know if you have any questions! :)

Cheers,
Ann

**Comment by ebooker2013** [comment]
I am getting the following error:

ebook@LAPTOP-HK6D177H MINGW64 /c/users/ebook/onedrive/desktop/skillcrush_coding/                skillcrush-104 (edits)
$ git push origin edits
Enter passphrase for key '/c/Users/ebook/.ssh/id_rsa':
To github.com:ebooker2013/skillcrush-104.git
 ! [rejected]          edits -> edits (fetch first)
error: failed to push some refs to 'git@github.com:ebooker2013/skillcrush-104.gi                t'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by redrambles** [comment]
Hey @ebooker2013 !

Are you still getting this message when trying to push up your edits branch? If so, this usually happens because an edit was made directly on GitHub - or if you have cloned this repository on another computer and have pushed from there.

 I would first make sure that you are on your edits branch (git checkout edits) and then create a copy of the branch just in case (git branch edits-backup). Then you can go ahead and pull in the branch from GitHub so that you can incorporate whatever changes it has that your local branch does not (git pull origin edits) - and then you can try pushing again (git push origin edits).

Let us know how this goes! :)

Cheers,
Ann

**Comment by ebooker2013** [comment]
Hi Ann,

I followed the first set of directions and didn't see any errors or
anything, so not sure what I'm looking for to know if it previously didn't
work. Do I need to resubmit the pull request?

**Comment by acodeinprogress** [comment]
Hey @ebooker2013,

Would you mind sending a screenshot of your terminal with the commands you're running as well as the results? You can try to attach it here or email it to questions@skillcrush.com.

We'll take a look at and see if we can spot what it happening!

xoxo,
Sharon

**Comment by ebooker2013** [comment]
I am confused on what message you think I am receiving. I have not had any
errors on merging or pushing until I have started these steps. They have
always looked exactly like the lesson plan. Can you please provide me a
step by step on what commands exactly you want me to run in order so I can
send a screenshot? I didn't know there was an issue with my merge so I
already have an upstream and I don't want it to mess anything up. My git
status says nothing to commit working tree clean.

**Comment by redrambles** [comment]
Hey @ebooker2013 !

Sorry about the confusion! We are referring to the initial error message you received in the Terminal (which you pasted in a reply above) when you wanted to push up your branch. If you take a look at the [change set included in your pull request](https://github.com/skillcrush/skillcrush-104/pull/1874/files) - you will see the additional file (advice/advice-.html) that we are requesting that you delete. Once you do, you'll want to make sure that you add that change `git add -A` and commit `git commit -m "your message here"` and then push up your branch once more `git push origin edits` - which will automatically update your pull request. At that point we should be all set to merge in your code. 

Let us know if you have any more questions - and don't be shy to reach out at 'questions@skillcrush.com' if it is easier to communicate there.

Cheers,
Ann

**Comment by redrambles** [comment]
Hey @ebooker2013 ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Comment by ebooker2013** [comment]
Hi Ann,

I have already deleted the file and updated the branch so I guess I don't
know what else is needed of me.

**Pull request closed without merging**
