### PR TITLE
Amanda's added advice!

### PR DESCRIPTION
**Pull request by alhasenzahl**
I added my piece of advice from my front end developer blueprint!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @alhasenzahl,

Looks great so far! I see that you added an extra file (TMP4S00HT.htm) to the project. If you could remove that file then run a slightly different git command (git add -A), commit, and push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by alhasenzahl** [comment]
Hello, 
Sorry about the extra file.  I'm not sure what the git command is for removing files...I looked online and there were a few different answers, so I wanted to double check that I was using the right one first before trying to do it.  

Thanks, 
Amanda

**Comment by acodeinprogress** [comment]
Hey @alhasenzahl,

Removing the file isn't a git thing. All you need to do is go into your project folder to wherever the file is and delete it. Then, to add, you'll do **git add -A** since that will recognize and delete the file from your repo. Then repeat the normal commit and pushing steps and you're all done!

xoxo,
Sharon

**Comment by alhasenzahl** [comment]
Thank you so much for your help!  I was able to get rid of the extra file and redo the add and commit steps with the project.  Please let me know if there is anything else I need to do!

-Amanda

**Comment by acodeinprogress** [comment]
Hey @alhasenzahl,

Thanks for making that change! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
