### PR TITLE
commiting a new file 

### PR DESCRIPTION
**Pull request by dattyle**

### CODE REVIEW

**Comment by sareg0** [comment]
hey @dattyle i see that you are linking to your own css file in the html file, but I don't see the css file anywhere in your commits. Did you forget to add it?

**Comment by dattyle** [comment]
sorry about that. thanks for the note. I've recommitted the css file. lmk if I"m missing anything else. thanks.

**Comment by acodeinprogress** [comment]
Hey @dattyle, it looks like you added everyone's css to your dl-style.css file. Since this is your personal stylesheet, you only need to add your css. It also looks like you have an extra untitled.css file.  If you could update your dl-style.css file and remove the untitled.css, run git add -A, commit, and then push, your changes should join the pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hi @dattyle, it's been a while since we're heard from you so I went ahead and removed all the extra css from your file and I removed the untitled.txt file from the css folder. Your changes are all merged in now.

**Pull request merged**
