### PR TITLE
Katie's Advice

### PR DESCRIPTION
**Pull request by katmaryd**
A few quick tips on learning to code.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @katmaryd! 

This is great! We just need you to include a link to your advice page in the main index.html file, and we'll be able to merge this in! Once you've added the link locally, add and commit your change and push your branch once more. This will automatically update your pull request. :)

Let us know if you have any questions!

**Comment by acodeinprogress** [comment]
Hey @katmaryd,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 10 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by katmaryd** [comment]
Hi Sharon - I've been busy with work so haven't had a chance but will do so
by the end of this week!

**Comment by katmaryd** [comment]
Hi all, I *think* this is complete. Could you check it out?

**Comment by redrambles** [comment]
Hi @katmaryd!

Ok! I see that you've added a link in the index.html file - which is great! But you also included another advice page and another bit of css. [See here?](https://github.com/skillcrush/skillcrush-104/pull/1503/files) Your link in the index.html is pointing to 'advice/katied-advice.html' so let's delete the other advice page from the repo ('advice/katie-advice.html').

Your 'advice/katied-advice.html' page is referencing 'css/katied-advice.css' for your styles, so let's delete the other stylesheet ('css/katie-advice.css'). 

Once that is done, you'll need to use a slightly different command:
`git add -A`
followed by a commit:
`git commit -m "your message here"`

And then push your branch back up again, which will automatically update this pull request:
`git push origin newbranch`

So! To summarize:

**While in your _newbranch_ branch**:

1. **Delete** advice/katie-advice.html
2. **Delete** css/katie-advice.css
3. `git add -A`
4. `git commit -m "your message"`
5. `git push origin newbranch`

That should do it! Let us know if you have any questions!

**Comment by acodeinprogress** [comment]
Hey @katmaryd,

We still haven't heard from you in a while. I'm going to close this pull request. Feel free to reopen this or submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
