### PR TITLE
Amanda Capella's advice html and css

### PR DESCRIPTION
**Pull request by CapellaBlue**
whew, the more practice the better!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @CapellaBlue, it looks like you forgot to include a link to your page in the index.html file. Go ahead and do that then add, commit, and push. Your changes will join your pull request here and then I can get it all merged in! Let me know if you need any help.

**Comment by CapellaBlue** [comment]
Oh, I didnt realize we need to add a link.  Is it a link to our github profile or our personal site? Or do you mean link to a style sheet? I tried linking it to the style.css in the folder just with my own personal style section.  Either way, lol I'm a bit confused.


Sent via the Samsung Galaxy S® 5 ACTIVE™, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by acodeinprogress** [comment]
All you need to do is add a link to the html page that you created. If you take a look in the index file, it should help clear things up. Let me know if you're still confused!

**Comment by CapellaBlue** [comment]
I am so sorry, but I dont know what link youre referring to.  I'm looking at the html file in notepad++ right now...and I dont see any instructions for a link:( I'll add a link to my website (?) and resubmit.


Sent via the Samsung Galaxy S® 5 ACTIVE™, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by acodeinprogress** [comment]
That's perfect! Now it's all merged in! Great work!

**Comment by CapellaBlue** [comment]
Thanks, Sharon lol

**Pull request merged**
