### PR TITLE
My changes

### PR DESCRIPTION
**Pull request by Komorebi-Girl**

### CODE REVIEW

**Comment by Komorebi-Girl** [comment]
I added my index.html webpage to the group.

**Comment by Komorebi-Girl** [comment]
I also changed the title of my webpage slightly.

**Comment by acodeinprogress** [comment]
Hey @Komorebi-Girl,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Komorebi-Girl,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 20 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Komorebi-Girl,

We still haven't heard from you. If no changes are made in 10 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Komorebi-Girl,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
