### PR TITLE
Created M. Drlik's advice web page

### PR DESCRIPTION
**Pull request by mdrlik0125**
This is my contribution to "Advice for Newbies"

### CODE REVIEW

**Comment by mdrlik0125** [comment]
I had to add the missing URL's from the time I forked the repo and when I was ready to commit

**Comment by mdrlik0125** [comment]
I'm kinda lost, so I'm closing the pull request and starting over

**Review by mdrlik0125 — COMMENTED** [review]
This commit should be ignored. I do not know how to delete it.

**Comment by mdrlik0125** [comment]
I think this commit is ready for Skillcrush/skillcrush-104

**Comment by acodeinprogress** [comment]
Hey @mdrlik0125,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Comment by mdrlik0125** [comment]
Sharon,
Thanks. I was really kind of bumbling around, there. I’ve been practicing with my own stuff so I can better understand the whole Git, GitHub process. It is coming along, just not as fast as I’d like it to ;-)

Marena

**Pull request merged**
