### PR TITLE
added jason-force.rb

### PR DESCRIPTION
**Pull request by mojason-81**

### CODE REVIEW

**Comment by sareg0** [comment]
Hey @mojason-81 execellent work!

I just have one request before I merge this. Could you please move your ruby file to the 'ruby' folder in the repo. You can then add, commit and push and the changes will be reflected in this pull request. 

Many thanks in advance!

**Comment by mojason-81** [comment]
Hey Sara, 

I did this work probably about a month ago and since then I've had to
reimage my machine and I lost some files and still need to set up a
local git repo and try to get all my work back and get it organized.
I'll try and find some time for the changes, but I'm not sure it's going
to be any time soon (but I'll put it on my plate this weekend). I'm
still trying to keep up with SC204 (and the rest of life :-) ). As soon
as I can figure out how to pull the repo back down locally, I'll move
the file over, commit my changes, and send another pull request. I must
have had a break with reality. I'm not sure why I didn't put it in there
in the first place. Sorry for the trouble. 

Thanks! 
---

Jason Force
www.mojason.com [3]
_Always a work in progress!_

On 04/15/2015 18:06, sareg0 wrote: 

> Hey @mojason-81 [1] execellent work! 
> 
> I just have one request before I merge this. Could you please move your ruby file to the 'ruby' folder in the repo. You can then add, commit and push and the changes will be reflected in this pull request. 
> 
> Many thanks in advance! 
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1] https://github.com/mojason-81
[2]
https://github.com/skillcrush/skillcrush-104/pull/144#issuecomment-93593223
[3] http://www.mojason.com

**Comment by mojason-81** [comment]
Sara, 

I managed to pull my skillcrush-104 clone back down and moved my .rb
file into the ruby folder, pushed my changes back to my cloned repo. I
just need to figure out how to send you a pull request for that repo
again and I can't remember how to go about doing that. I looked at the
provided cheat sheets again, but didn't see anything to help. I looked
on the GitHub help page for pull requests, but the directions aren't
matching up with what I' seeing. Can you provide some help for me
please? 

Thanks, 
---

Jason Force
www.mojason.com [3]
_Always a work in progress!_

On 04/15/2015 18:06, sareg0 wrote: 

> Hey @mojason-81 [1] execellent work! 
> 
> I just have one request before I merge this. Could you please move your ruby file to the 'ruby' folder in the repo. You can then add, commit and push and the changes will be reflected in this pull request. 
> 
> Many thanks in advance! 
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1] https://github.com/mojason-81
[2]
https://github.com/skillcrush/skillcrush-104/pull/144#issuecomment-93593223
[3] http://www.mojason.com

**Comment by sareg0** [comment]
Hey Jason, if you look above your last comment you will see a new commit. Which is exactly on the money, so I'm going to merge this on up for you.

Terrific work!

**Pull request merged**
