### PR TITLE
changed advice to my own

### PR DESCRIPTION
**Pull request by Melificent92**
Just a few changes :)

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Melificent92 !

This is great - we just need you to make one small change. Your advice page currently doesn't have an extension - it's 'advice/melissas-advice' but should be 'advice/melissas-advice.html'. Please rename this file, add and commit that change then push up your experiments branch once more, which will automatically update this pull request. 

Once that is done, we should be all set to merge in your code! Let us know if you have any questions.

Cheers,
Ann :)

**Comment by Melificent92** [comment]
I knew there was something wrong but I didn't see that! Thanks!

**Comment by redrambles** [comment]
Hi @Melificent92 !

Your changes to your advice file don't appear to have come through. Still on your experiments branch, let's try again, this time using this command:

`git mv advice/melissas-advice advice/melissas-advice.html`

Then add and commit that change, and push up your experiments branch once more, which will update this pull request.

Then we should be all set! Let us know if you have any questions!

**Comment by acodeinprogress** [comment]
Hey @Melificent92,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
