### PR TITLE
Adam Britt Advice Addition

### PR DESCRIPTION
**Pull request by adam-britt**
Some advice for future pupils!

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @adam-britt!

This is almost ready to go - but it looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's. Once you make that change, you can add, commit, and push up your branch once more, which will automatically update your pull request.

Then we should be all set to merge in your code! :)

Let us know if you have any questions!

Cheers,
Ann

**Comment by adam-britt** [comment]
I edited the CSS file, but I can't seem to push it up to GitHub :/

I'll attach screenshots of my terminal - help appreciated.

Adam

**Comment by redrambles** [comment]
Hey @adam-britt ! 

I'm not seeing any screenshots - adding them here is a bit tricky - [here is some more info about that](https://www.tilcode.com/add-a-screenshot-to-your-github-repo-readme-md/).

If you'd prefer to communicate with us via e-mail about this -you totally can! Just shoot us an e-mail and we'll troubleshoot there!

Cheers,
Ann

**Comment by adam-britt** [comment]
Here are the screenshots again (sending this via email, so you should be
able to access)

Please let me know how to proceed in order to complete this process.

Thanks,
Adam

**Comment by acodeinprogress** [comment]
Hey @adam-britt!

I'm not seeing any changes yet. Did you need any more help with this?

xoxo,
Sharon

**Comment by adam-britt** [comment]
Did that work?

**Comment by acodeinprogress** [comment]
Hey @adam-britt!

I'm seeing some changes in the index.html file but not to your stylesheet. Did you make sure to make the changes that Ann requested?

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @adam-britt,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
