### PR TITLE
Brianna's Advice and Styles

### PR DESCRIPTION
**Pull request by bda412**
Thank you! I'm learning tons!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @bda412,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by bda412** [comment]
Hi Sharon,

Okay, I pushed the changes as you asked, hope all looks good now!

Thank you,
Brianna
ᐧ

**Comment by acodeinprogress** [comment]
Hey @bda412,

Unfortunately, I'm not seeing any changes. Did you add and commit your changes? If so, did you make sure that you were on your brianna-advice branch and pushed up to your brianna-advice branch of GitHub?

xoxo,
Sharon

**Comment by bda412** [comment]
Okay, when I look on Github now, I can see the change in my branch. Can you
see it now?
ᐧ

**Comment by acodeinprogress** [comment]
Hey @bda412,

Perfect! Thanks for making that change! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
