### PR TITLE
created advice html and css files

### PR DESCRIPTION
**Pull request by aelshia**
Let's try this out

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @aelshia !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in.

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by acodeinprogress** [comment]
Hey @aelshia!

It looks like you added another advice file and added some extra styles to the style.css file in your latest commit. You just need one advice file and you only need to add your styles to one file (whether it's style.css or your personal stylesheet).

If you could remove the extra files, that would be great! Then you'll want to run a slightly different git command (git add -A), commit, and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @aelshia,

You can see the extra files if you look at the [Files Changed](https://github.com/skillcrush/skillcrush-104/pull/1778/files) tab near the top of this page.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @aelshia,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
