### PR TITLE
Katie's advice index and css

### PR DESCRIPTION
**Pull request by ktclgrv**
my advice index and css modifications

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @ktclgrv !

This is a great start! Your `advice/katiec-advice.html` file is great - and is in the right location. We do have two more files from you, though - and they are both CSS files and inside the /advice/css directory - which isn't where we want them. [Here is a link to your pull request so that you can see what I see.](https://github.com/skillcrush/skillcrush-104/pull/2072/files)

There is already a 'normalize.css' file inside the 'css/' directory - so you can delete this file entirely (`advice/css/normalize.css`). You are already linking to the css/normalize.css in your advice page, so you don't need to change anything there.

You will need to delete the `advice/css/main.css` file as well - but you can first copy the contents and place the block of code inside the main stylesheet (css/style.css). Then you'll want remove the link to 'css/main.css' in the <head> of your advice page. Your advice page should only be linking to the 'css/normalize' file and the 'css/style.css' file- preferably in that order.

We'll need you to delete the 'advice/css' directory as well.

Great! Now your styling is all set up. The last thing we'll need you to do is include a link to your advice page in the main index.html file. Most students add their link to the very top or the very bottom of that long list - but it is really up to you.

Once those change have been made - please add (`git add -A`), commit (`git commit -m "your message here"`) and push up your branch once more (`git push origin katiebranch`) - which will automatically update this pull request.

Then we should be all set to merge in your code!

Let us know if you have any questions, and keep up the great work!

Cheers,
Ann

**Comment by ktclgrv** [comment]
I am so confused. The snip is all I have now, with no css anymore, because
the main.css file I had linked I have now deleted based on the instructions
you emailed. So now it says the main.css file is not found anymore, and I
don't have any css styling anymore. I also don't know where the
css/style.css is that you're referring to. And what do you mean be
including a link to the advice page? What sort of link? I thought this was
the link in html form?

I'm sure I've misinterpreted the instructions but I feel like I'm more
confused now than I was before.

Sorry for the confusion,

Katie

**Comment by ktclgrv** [comment]
Can I just start over? i don't know what I did and I don't know how to fix it. I am very confused and I'd rather just start this project over.

**Comment by acodeinprogress** [comment]
Hey @ktclgrv,

Yes. We want you to learn in the best way possible so you can definitely start over if you think it would be helpful to go through this again. Just let us know and we can close this pull request and you can submit a new one. :)

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @ktclgrv,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
