### PR TITLE
September

### PR DESCRIPTION
**Pull request by teabuzz80**
I don't know if i'm doing this right.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @teabuzz80,

This looks great! I just have a couple smallrequests before I merge this in.
1) We would like for you to include a link to your advice page in the index.html file. 
2) I see an absolute link in your advice page that links to a file on your computer. When someone looks at your page, they won't have access to your computer files. You'll want to change that url to a relative url. Here's a great article on absolute vs relative: https://internetingishard.com/html-and-css/links-and-images/#absolute-relative-and-root-relative-links

If you could make those updates to your code, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by teabuzz80** [comment]
Hi Sharon,
Thank you. I'm still not all that confident and don't know what I'm doing. I just followed the instructions step-by-step, I'm thinking of re-doing the whole lesson again to understand it better. Would you recommend I complete the HTML & CSS first to understand GIT better?

Thank you,
Tsering

**Comment by acodeinprogress** [comment]
Hey @teabuzz80,

You don't have to know HTML & CSS to know Git. You should know it to complete the HTML & CSS portion of this assignment but it's nothing major. If you think it would help you to go back and redo the material, go right ahead! We really want you to learn the material and be successful with it so we support whatever you need to make that happen. You're welcome to close this pull request and then submit a new one when you're ready.

xoxo,
Sharon

**Comment by teabuzz80** [comment]
Thank you Sharon. I'll try my best.

Tsering

**Comment by acodeinprogress** [comment]
Hey @teabuzz80,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 10 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by teabuzz80** [comment]
Hi Sharon,
I made the changes an started from the beginning like I mentioned in my last email. And I also got confirmation from your side that my project was merged.

Thanks,
TJ

**Comment by acodeinprogress** [comment]
Hey @teabuzz80,

So sorry about that! I'll go ahead and close this pull request. Thanks for letting me know!

xoxo,
Sharon

**Pull request closed without merging**
