### PR TITLE
I add my advice- Kim

### PR DESCRIPTION
**Pull request by jukeb0xhero**
Here's something that I wish I new before I started; just a little something that I hope to make beginning coders lives a tad easier.

### CODE REVIEW

**Comment by redrambles** [comment]
Hi @jukeb0xhero!

Ok! There a lot of files here in your pull request, and we should only be seeing three:

1. Your advice page
2. Your css (whether in a separate css file or additional code added to the main style.css file) 
3. Your added link to the main index.html file, so folks can find (and read) your advice.

At the moment I see 10 changed files in your pull request. If you take a look at this page - can you narrow down which files are yours?

**Comment by jukeb0xhero** [comment]
Hello @redrambles!

Yeah, I was running into all sorts of issues while trying to go through the lessons on the terminal. I did commit a couple of times, but I didn't know they all registered because I didn't know as to whether the first few times took, since I kept getting errors.

Also, I accidentally saved an html file to the advice folder by mistake and moved things around on my desktop while trying to code another website. I'm working on staying more organized...

Any who, I only planned on making changes to 'advice/kimpereira-advice.html' and 'css/pereirastyle.css'. Is there anything else I need to do on my end? Please advise. Thanks!

**Comment by redrambles** [comment]
Hey @jukeb0xhero !

Thanks for the clarification!

Ok! There are two ways to handle this. The first is a simpler way (blue pill) - which essentially involves moving both of the files that you wish to keep outside of the project for temporary safekeeing - deleting your experiments branch and creating it again, and the second is a Git ninja way (red pill). The Git ninja way would involve several steps as well as commands that we don't cover in the course, but might be fun! 

Let me know if you choose the blue pill or the red pill, and we'll go from there. :) 

P.S - No shame in choosing the blue pill - just wanted to lay out your options.

**Comment by acodeinprogress** [comment]
Hey @jukeb0xhero,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 10 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @jukeb0xhero,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
