### PR TITLE
added my advice

### PR DESCRIPTION
**Pull request by kwags**
Added my advice

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @kwags,

Great job so far! It looks like you have some merge conflicts and edited some other peoples styles. If you could fix those things up then add, commit, and push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @kwags,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 20 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by kwags** [comment]
Thanks Sharon! I think maybe I've got it now?

**Comment by acodeinprogress** [comment]
Hey @kwags,

Thanks for making that change! Unfortunately, it looks like there are some merge conflicts in your code. We won't be able to merge this in with that in the code.

xoxo,
Sharon

**Comment by kwags** [comment]
Hmmmm...with my latest commit it tells me there are no conflicts. Can you let me know where the conflicts are? Thank you.

**Comment by acodeinprogress** [comment]
Hey @kwags,

Take a look at the Files Changed tab. You'll see some content like this:
screen shot 2017-06-12 at 9 26 46 am
The red boxes show where the merge conflicts are. The reason your GitHub isn't saying that there are conflicts are because you saved them in your code. It is not good practice to save merge conflict code into a codebase, so we can't merge it in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @kwags,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
