### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by hall2011**

### CODE REVIEW

**Comment by hall2011** [comment]
thanks for making my changes

**Comment by acodeinprogress** [comment]
Hey @hall2011,

Looks great! I only have 3 small requests for you. 

1) It would be great if you could give your page some styling by adding some css to the style.css file.
2) We would love it if you included a link to your advice page in index.html so that others can see your awesome work.
3) Your advice page is in the main directory and we'd like for it to be in the advice folder. 

If you could make those changes, then run git add -A (don't forget the -A), commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by hall2011** [comment]
Which assignment are you referring to?

**Comment by acodeinprogress** [comment]
It depends. Are you completing this assignment through Skillcrush 104 or Skillcrush 105?

**Comment by hall2011** [comment]
That had to be about github so 105

**Comment by acodeinprogress** [comment]
This should be in Lesson 10 - Make a Change Then Push to Your Repo

**Comment by acodeinprogress** [comment]
Hey @hall2011,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by hall2011** [comment]
I sent my advice file to the folder you told me to.

**Comment by acodeinprogress** [comment]
@hall2011 I'm going to close this pull request since I merged in your other one.

**Pull request closed without merging**
