### PR TITLE
sarah_g.rb

### PR DESCRIPTION
**Pull request by gagliardisa**
Very coolness!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @gagliardisa,

This looks great! I only have 1 tiny request for you. We'd love for you to have a link to your advice page in the index.html file. If you could add that in, then add, commit, and push, your changes will join this pull request.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @gagliardisa,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 17 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @gagliardisa,

This is just a reminder that this pull request will close in 7 days if no changes are made.

**Comment by gagliardisa** [comment]
Inserted the link on the advice page. Thank you

**Comment by acodeinprogress** [comment]
Great work, @gagliardisa! Your code is all merged in.

**Pull request merged**
