### PR TITLE
practice

### PR DESCRIPTION
**Pull request by jenjarsbutterfly**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @jenjarsbutterfly !

This is almost ready to go! We just need you to make a small change. In your change set [over here](https://github.com/skillcrush/skillcrush-104/pull/2101/files), you can see that you have added a custom stylesheet (which you have linked to from your advice page) - and you have made changes to the main stylesheet (css/style.css) - but the latter isn't necessary, given that you are using a custom stylesheet. 

Please remove the block of code that you added to the main stylesheet (as well as the remaining conflict marker), save the file and then add and commit that change. Then you can push up your experiments branch once more, which will automatically update your pull request.

Once that's done, we should be all set to merge in your code! :)

Let us know if you have any questions, and keep up the great work!!

Cheers,
Ann

**Comment by jenjarsbutterfly** [comment]
Can you please explain why there are other advices on the main stylesheet
and why I don't have to add my CSS?
"

**Comment by jenjarsbutterfly** [comment]
It says this branch has conflicts that must be resolved. What can I do?

**Comment by redrambles** [comment]
Hello @jenjarsbutterfly ! 
To answer your first question, you can add styles to the main stylesheet or you can add styles to a custom stylesheet, but you don't want to do both. Given that you had made changes in both places but that you had linked to your custom stylesheet in your advice page, I thought it best that we stay with your custom stylesheet and remove the code in the main stylesheet, as it seemed the simplest operation.

You've done that, by the way - which is great! Your code is all set.

For your second question, the warning about conflicts means that the main code base has evolved since you submitted your pull request, and GitHub is letting us know that in order to merge your code in as it is now, we'll need to resolve a few merge conflicts. This is 100% normal on a codebase that so many people contribute to and that evolves fairly quickly. If you like, we can take care of this for you on our end - but if you prefer to get more practice, you can fetch from upstream, merge upstream/master into your master branch and then merge your freshly updated master branch into your experiments branch, resolving the conflicts that arise yourself. Then you can push up your experiments branch once more, and it will be conflict free (for now! :)). If you would prefer that we do this on our end, that's not a problem. :)

Let us know what you'd like to do - and good job on this assignment!

Cheers,
Ann

**Comment by jenjarsbutterfly** [comment]
Hi Ann,

Yes, please take care of it for me. Thanks!

**Comment by redrambles** [comment]
Hey @jenjarsbutterfly,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Comment by jenjarsbutterfly** [comment]
🔥🔥🔥🔥🔥👍👍👍👍👍😸😸😸😸😸 Thanks!

**Pull request merged**
