### PR TITLE
EPIC advice page. 

### PR DESCRIPTION
**Pull request by PghMav**
So, I really went all out on my assignment and made an advice page that I'm really proud of. It includes a js file...I hope that's okay. 

Thanks!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @PghMav,

Looks great so far! I see that you added a JavaScript file to the project. We like to keep our repository as simple and clean as possible so we can only accept the work we requested. If you could remove the js folder and file then run a slightly different git command (git add -A), commit, and push, your changes will join your pull request here.
If no changes are made in 10 days, this pull request will close.

Let us know if you need any help!

xoxo,
Sharon

**Comment by PghMav** [comment]
Hey, Sharon! 

Great to hear from you on this. Yeah, I know I went a little beyond what was asked. I’m okay with the pull request closing; if I remove the JS, the page will look awful and I don’t want to put the time into making a corrected version. 

Thanks again! This was a fun exercise.

B

**Comment by acodeinprogress** [comment]
Hey B,

That sounds good. Even though we can't accept it, awesome job on the JavaScript!

xoxo,
Sharon

**Comment by PghMav** [comment]
Thanks!!

**Pull request closed without merging**
