### PR TITLE
modified html and css betinalynn

### PR DESCRIPTION
**Pull request by betina72**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @betina72,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by betina72** [comment]
Hi Sharon,

i made the change, did the add and commit, but i'm getting stuck on how to
push it to the remote upstream master. tips?

Thanks,

Betina

**Comment by acodeinprogress** [comment]
Hey @betina72,

You'll want to make sure that you've made your changes and commits on your betinalynn branch and then push up to that same branch. You should be able to do it the same way you did when you made your original commits and push.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @betina72,

Thanks for adding in that link! Unfortunately, it looks like you also changed someone else's styles in the style.css file and you added 2 personal stylesheets, one of which doesn't have the .css extension at the end of it. My suggestion would be to undo the changes in style.css and delete the extra stylesheet (the one that's missing .css at the end). Once you do that, you'll need to run a slightly different git command (git add -A), commit, and then push.

xoxo,
Sharon

**Comment by betina72** [comment]
Hi Sharon,

Thanks for the head's up. I think I've got it now. I just fixed the errors
and pushed the most recent version of my stylesheet.

Thanks,

Betina

**Comment by acodeinprogress** [comment]
Hey @betina72,

Awesome! Thanks! There's just one little thing. If you take a look at the Files Changed tab, you'll see this
screen shot 2017-07-14 at 10 38 50 am
If you could fix that back up and push again, I'll be able to merge this in. :)

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @betina72,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 18 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @betina72,

This was my last message regarding changes:
screen shot 2017-07-21 at 4 48 40 pm

If you take a look at the Files Changed tab, it still hasn't been changed back. :)

xoxo,
Sharon

**Comment by betina72** [comment]
Hi Sharon,

Okay, I found that line in the style.css file, changed it, did the git add
-A, commit with comment, pushed to betinalynn and refreshed my github
page...it says the pull request has been updated. Thanks for sticking with
me on this. I got through the class so easily I thought I had this stuff
down pretty well.... goes to show me!

:-)

Betina

**Comment by acodeinprogress** [comment]
Hey @betina72,

Perfect! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
