### PR TITLE
added my advice file

### PR DESCRIPTION
**Pull request by Rani-Lioness**
Added my advice file, so going to try again!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Rani-Lioness,

It looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's. Once you make that change, you can add, commit, and push and it'll join your pull request here.

Let us know if you need any help!

If no changes are made in 10 days, this pull request will be closed.

xoxo,
Sharon

**Comment by Rani-Lioness** [comment]
Oh, alright I thought I had removed them already, but I’ll check!

**Comment by Rani-Lioness** [comment]
Oh alright... what do I do??

**Comment by redrambles** [comment]
Hey @Rani-Lioness,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
