### PR TITLE
make a change then push to your repo

### PR DESCRIPTION
**Pull request by mhiggins0228**

### CODE REVIEW

**Comment by mhiggins0228** [comment]
I added some advice and changed the name of advice to mhiggins0228

**Comment by acodeinprogress** [comment]
Hey @mhiggins0228,

I can't seem to see an advice page or any css. It looks like you've only included a link to your file in index.html (which is great!). If you could add in the rest of the content, that would be fantastic!

Once you make that change, you can add, commit, and push. Your changes will join your pull request here.

Let me know if you need any help.

**Comment by mhiggins0228** [comment]
@acodeinprogress 
I do. I was having trouble with this task. Ann said the branch had been pushed so yes, any assistance would be very helpful. 

Thanks

**Comment by acodeinprogress** [comment]
Hey @mhiggins0228,

Could you try adding your file and css again?
This is all that I'm seeing:
screen shot 2016-07-24 at 10 32 45 am

**Comment by mhiggins0228** [comment]
@acodeinprogress 
I think I did what you requested. Please check to make sure everything worked out. Thanks

**Comment by acodeinprogress** [comment]
Hey @mhiggins0228,

Thanks for adding the css! But you'll also need an advice page so that your css will show and so that your link in the index.html file doesn't result in an error. :)

**Comment by mhiggins0228** [comment]
@acodeinprogress 
There is no advice page and I have no idea why. I followed the directions provided, but when I "git clone git@github.com:mhiggins0228/skillcrush-104.git" in my terminal, I get the message " 'skillcrush 104' already exists and is not an empty directory." Even I can see that my advice is not showing up but have no idea how to remedy this.

**Comment by acodeinprogress** [comment]
That just means that you already have a skillcrush-104 folder in that directory. You can either move the folder to a different directory, clone your repo into a different directory, or delete the folder. Then you should be able to clone it.

**Comment by mhiggins0228** [comment]
I created an html advice page and used my mouse to move into the "advice" folder. The page links to the index html page but I don't see my name on it. I have no idea what I'm doing but that seems like it works.

**Comment by acodeinprogress** [comment]
Hey @mhiggins0228,

That sounds right to me! Did you push your changes up to GitHub? I'm not seeing it in the Files Changed tab.

**Comment by mhiggins0228** [comment]
@acodeinprogress 
Ok. I may have actually figured out what I'm doing. I pushed the file to the repo.

**Comment by acodeinprogress** [comment]
Hey @mhiggins0228,

Were your changes on your experiments branch? I'm still not seeing your advice page.

**Comment by mhiggins0228** [comment]
@acodeinprogress 
Yes but I thought they were pushed to the repo. Obviously, I have no clue.

**Comment by acodeinprogress** [comment]
Hey @mhiggins0228,

Are you able to make it to office hours? It's on Saturday at 1pm EDT. We can go over it there. Or send us an email and we'll figure something out.

**Comment by mhiggins0228** [comment]
@acodeinprogress 
Let's do office hours this saturday @ 1ET. Is that also on Google talk?

**Comment by acodeinprogress** [comment]
@mhiggins0228 Yep!

**Comment by mhiggins0228** [comment]
@acodeinprogress 
Hi. I signed up for the office hours but I did them with Ann. I decided I would just start over on this task. I just completed it. I'm fairly confident everything's been done right, but please verify.

**Comment by acodeinprogress** [comment]
Hey @mhiggins0228,

I don't see another pull request from you. Do you want to close this one and submit a new one?

**Comment by mhiggins0228** [comment]
@acodeinprogress 
Yes please do that.

**Comment by acodeinprogress** [comment]
Ok, it's now closed. :)

**Pull request closed without merging**
