### PR TITLE
changes to advice column

### PR DESCRIPTION
**Pull request by automaticsweetheart**
I have some advice to share!

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @automaticsweetheart!

This is a great start! We just need you to do two things and then we'll be good to merge this in.

1) You have included a file in the project called 'css/reneevalenzuela-style .css' - which isn't referenced by your advice page, so we will need you to delete it.
2) We need you to add a link to your advice page at the bottom of the list on the main index.html page, so folks can find your words of wisdom! :)

Once you have made both of those changes, you'll need to run:

`git add -A`

followed by:

`git commit -m "your message here"`

and then finally:

`git push origin experiments`

This will automatically update your pull request, and we should be good to merge it in!

Let us know if you have any questions - and keep up the good work!

**Comment by acodeinprogress** [comment]
Hey @automaticsweetheart,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 9 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by automaticsweetheart** [comment]
Hi Sharon, 

Thank you for the reminder! 
I will work on this today. 

x-Renee


On Nov 12, 2017, at 7:22 AM, Sharon <notifications@github.com> wrote:

Hey @automaticsweetheart <https://github.com/automaticsweetheart>,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 9 days, this pull request will be closed.

Let us know if you need any help!

xoxo,
Sharon

**Comment by automaticsweetheart** [comment]
Hi Sharon, 

I did all the necessary deletions/additions, ran the git add -a , git commit -m , and git push origin experiments commands. On that last one, I’m getting a window that pops up asking for the SSH password. I did do the lesson when setting up Github that would make it so I wouldn’t have to type a password in every time I run an operation. Any ideas why it’s asking me for it? And would it be key that is listed in my GitHub account? Any words of wisdom appreciated. 

Thank you! 

-Renee



On Nov 12, 2017, at 7:22 AM, Sharon <notifications@github.com> wrote:

Hey @automaticsweetheart <https://github.com/automaticsweetheart>,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 9 days, this pull request will be closed.

Let us know if you need any help!

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @automaticsweetheart !

Your computer is probably asking you for your _passphrase_, which we set up earlier in the course when we first created our ssh keys. It's normal that we need to enter it again every once in awhile, especially if there has been a computer reboot since the last time we needed to communicate with an outside server using Git. 

Let us know if that solves the issue! If not - can you please include a screenshot of the popup window that you are seeing?

Thanks!!

**Comment by automaticsweetheart** [comment]
Ok, got it!
Using the pass phrase solved the problem. 

Thank you for your help!

x-Renee


On Nov 13, 2017, at 6:01 PM, Ann Cascarano <notifications@github.com> wrote:

Hey @automaticsweetheart <https://github.com/automaticsweetheart> !

Your computer is probably asking you for your passphrase, which we set up earlier in the course when we first created our ssh keys. It's normal that we need to enter it again every once in awhile, especially if there has been a computer reboot since the last time we needed to communicate with an outside server using Git.

Let us know if that solves the issue! If not - can you please include a screenshot of the popup window that you are seeing?

Thanks!!

**Comment by acodeinprogress** [comment]
Hey @automaticsweetheart,

It looks like you added in some extra files in your commit. You can take a look at them by clicking on the Files Changed tab near the top of this page. You'll need to remove those files before we can merge this in.

Happy git-ing,
Sharon

**Comment by acodeinprogress** [comment]
Hey @automaticsweetheart,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
