### PR TITLE
changed html and styles

### PR DESCRIPTION
**Pull request by mannyn19**
check the new styles for the web and the advices

### CODE REVIEW

**Comment by mannyn19** [comment]
this is the las update

**Comment by mannyn19** [comment]
i would like to know if im doing things right

**Comment by acodeinprogress** [comment]
Hey @mannyn19,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by mannyn19** [comment]
i dont understand why everytime im trying to use git push origin
"experiment"
i have this message

Enter passphrase for key '/Users/manuelnunez/.ssh/id_rsa':

ERROR: Permission to skillcrush/skillcrush-104.git denied to mannyn19.

fatal: Could not read from remote repository.


you guys mention that we can add this automatically, i am very confuse
about everything with this github.com,


i made the changes and now i wan to use git push to finish this and it
doesnt work

**Comment by acodeinprogress** [comment]
Hey @mannyn19,

My guess is that you added a password when you set up your ssh key. Maybe you could try the main password you use on your computer? Otherwise, you can try setting up another ssh key.

Let me know how it turns out!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @mannyn19,

We haven't heard from you in a while. If no changes are made in 10 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @mannyn19,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
