### PR TITLE
this forkin'rocks

### PR DESCRIPTION
**Pull request by JMart77**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @JMart77,

It looks like you deleted a file from the ruby folder. Would you mind putting that file back in? The file name and code can be found under the Files Changed section of this pull request. Once you do that, you can add, commit, and push. Your changes will join your pull request here.

Let me know if you need any help!

**Comment by JMart77** [comment]
Sorry,  I did not know.  I will give it a try.
~Jessica

**Comment by acodeinprogress** [comment]
Hey @JMart77,

It still looks like that file is missing. If you take a look at the Files Changed tab at the top, it'll show you what file and content was deleted.

**Comment by acodeinprogress** [comment]
Hey @JMart77,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by JMart77** [comment]
okay I think I got it. Added back the file and completed advice contribution.  Please let me know if it looks wrong.
~Jessica

**Comment by acodeinprogress** [comment]
Hey @JMart77,

I have a few new comments for you.
1) It looks like your advice page has a lot of extra content. I'm thinking this may have come from a text editor. Could you reduce some of the extra clutter in it?
2) You're not linking to your custom css file in your advice page in the <head>.
3) You have an extra html file in the main directory. 
4) When you added back the code in the previously missing file, you add -. The - that show on GitHub means that those lines were deleted. Could you remove the - at the beginning of all your lines in that file?

**Comment by acodeinprogress** [comment]
Hey @JMart77,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 16 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @JMart77,

This is just a reminder that this pull request will close in 10 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @JMart77,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

**Pull request closed without merging**
