### PR TITLE
erika's custom colors

### PR DESCRIPTION
**Pull request by epprice**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey ,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by epprice** [comment]
I did create an advice page and css, but seemed to be having trouble with
the push. Let me try to redo the lesson and see what happens.

Thanks,
Erika

**Comment by epprice** [comment]
ok, I've thoroughly confused myself now. I think moving on from this lesson and coming back is making it even more difficult because I'm stepping into the middle. Attaching a screenshot of Git Bash so you can see what I'm trying to do... 
screenshot 92

**Comment by acodeinprogress** [comment]
Hey @epprice,

You're super close! Your files were added in but it looks like they don't have any extensions on them (.html and .css). You'll need to rename those files so that they have the correct extensions and then run a slightly different git command (git add -A), then commit, and push just like you did last time.

xoxo,
Sharon

**Comment by epprice** [comment]
Ok, I think it worked this time. Yes?

**Comment by acodeinprogress** [comment]
Hey @epprice,

Unfortunately, I'm not seeing any changes. Did you make sure to push your code to GitHub?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @epprice,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 8 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by epprice** [comment]
Yes! I know it’s still out there and I promise I’ll get back to it in the next few days. I got pulled away to my job and website stuff there and haven’t had a chance to get back. The good news is that I successfully migrated my company’s site from some ancient hosting service (ever heard of Concipia?) to WP Engine last night. I learned way more than anticipated about DNS and SSL certificates, but the website is back up so I’m happy -and now I have a hosting service with a staging area for me to get going on building the new site.  

Thanks for the help!
Erika

**Comment by acodeinprogress** [comment]
Hey @epprice,

Wow! Congratulations! That's quite an accomplishment!

I'm going to go ahead and close this pull request for now. Feel free to reopen it or open a new one when you're ready to work on this again. :)

xoxo,
Sharon

**Comment by epprice** [comment]
Sorry to leave that out there languishing. I guess sometimes our learning
goes down unexpected paths, but the good news is I'm still doing all this!

Erika

**Pull request closed without merging**
