### PR TITLE
Adding advice from Eileen

### PR DESCRIPTION
**Pull request by eileenschaubert**
Second try - from my fork, not the master.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @eileenschaubert !

This is great (I love the advice too!) The only thing is that there were a few links accidentally deleted in the index.html file, when you added your own link ([see here](https://github.com/skillcrush/skillcrush-104/pull/1875/files)). 

Please add those back in (and keep your link as well, of course!) - then add and commit your change, and push up your branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by eileenschaubert** [comment]
Let's see if that worked... thanks!

**Comment by redrambles** [comment]
Hey @eileenschaubert !

This is so close! Thanks for making those changes - there are just a few conflict markers that need to be removed. [Check out the index.html file in your pull request here](https://github.com/skillcrush/skillcrush-104/pull/1875/files) - do you see the `<<<<<<< HEAD`, `========` and `master >>>>>>>` ? Those are conflict markers that are useful indicators while we are merging, but shouldn't be left in the code. 

Once you remove them, add and commit your changes and push up your branch once more - and then we should be good to go! :)

Cheers,
Ann

**Comment by redrambles** [comment]
This is great, @eileenschaubert! Thank you for making those changes. :)

Your code is all merged in!

**Pull request merged**
