### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by TRose2014**
My advice

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @TRose2014,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @TRose2014,

Thanks for adding in that link!
It looks like you deleted someone else's styles in the style.css file when you made that change. If you could add those styles back in, that would be fantastic. You can see the changes if you click on the Files Changed tab at the top of this page.

xoxo,
Sharon

**Comment by TRose2014** [comment]
Sorry, hopefully I fixed everything : )

**Comment by TRose2014** [comment]
Sorry about the issues, did I do it correctly this time. My 7 month old was banging on my laptop, I guess she did more damage than I thought. : )

**Comment by acodeinprogress** [comment]
Hey @TRose2014,

That's totally ok! This is great! Thanks for making all those changes. Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif) now.

xoxo,
Sharon

**Pull request merged**
