### PR TITLE
kimberly's changes

### PR DESCRIPTION
**Pull request by kimolabear**
Kimberly's advice

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @kimolabear,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by kimolabear** [comment]
I updated my branch 104kw2 - think i committed the changes, sorry.

**Comment by acodeinprogress** [comment]
Hey @kimolabear,

I'm not seeing your changes here. In order for them to show up on this pull request, you'll need to make sure to make them on your `104kw` branch and then push to your `104kw` branch. Otherwise, you'll need to submit a new pull request for a different branch.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @kimolabear,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
