### PR TITLE
Kim williams advice

### PR DESCRIPTION
**Pull request by kaushiro**
I hope Im doing this right!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @kaushiro,

Looks great so far! I see that you added an image to the project. We like to keep our repository as simple and clean as possible so we cannot accept images. You can host the image online and then include a link in your code to the image. If you could remove the image then run a slightly different git command (git add -A), commit, and push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by kaushiro** [comment]
@acodeinprogress I am not sure if I am doing this revised pull request correctly. You told me to take image off and link it to an image online so I found a google image of it and linked it into my css.  Is that what you meant I should do?

**Comment by redrambles** [comment]
Hey @kaushiro!

Yes - this is what we mean about the image, awesome! So now we just have to remove the image from the root of the directory, (babybuddha.jpg) - and that will settle the image issue.

In addition to this, however - there are a few other stylesheets that you have added in your branch which aren't needed, such as 'css/kimwilliams_style' and 'kimwilliams_style.css'. Once these three files are removed, you will want to use '

```git add -A```

followed by

```git commit -m "removed unnecessary files" ```

and then push back up:

``` git push origin branch ```

which will update your pull request. :)

So - to recap:

1. remove babybuddha.jpg
2. remove kimwilliams_style.css
3. remove css/kimwilliams_style
4. `git add -A`
5. `git commit -m "your message here"`
6. `git push origin branch`

Then we should be all set to merge in your code.

Let us know if you have more questions!

**Comment by kaushiro** [comment]
@redrambles I did exactly what you said and I'm still seeing the deleted files on github, even though I don't see them on my desktop? What is going on? How can I check to see that my git push was successful?

**Comment by redrambles** [comment]
Hey @kaushiro!

Ok! You made the necessary changes - but unfortunately they were made on the master branch instead of your 'branch' branch! Oops!

No worries - we can fix this!

First thing - pop into your 'branch' branch:

`git checkout branch`

and merge your master branch into it:

`git merge master -m "merging master into branch"`

This will pull in those commits that you meant to make on your 'branch' branch. Once that is done, check your files - the changes that you made on your master branch should be reflected there as well. Then you'll want to push up your branch:

`git push origin branch`

and this will update your pull request, which means we should be able to merge it in.

Let us know how it goes!

**Comment by kaushiro** [comment]
dont understand

**Comment by kaushiro** [comment]
@redrambles this is what i get when I try to push the branch which is why i pushed the master...

**Comment by kaushiro** [comment]
@redrambles I shut down git bash and tried again and somehow got it to push, but do you have any idea why I got the previous messages and how to get around that in the future?

**Comment by acodeinprogress** [comment]
Hey @kaushiro,

Hmm... I can't say why you're getting that error without being able to play around in git bash. It's very interesting that it resolved when you restarted it.

I'm still seeing the extra css file in there. Did you make sure to run `git add -A`, then commit and push?

If you're still having trouble with this, would you mind sending us an email at your blueprint email? We'll help get you back on track with this!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @kaushiro,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 5 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @kaushiro,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
