### PR TITLE
added my advice

### PR DESCRIPTION
**Pull request by yetanothersarah**
I didn't alter the content, but I did change up the CSS styling.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @yetanothersarah,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by yetanothersarah** [comment]
Hi @acodeinprogress ! I had added, just forgot to commit and push - did that just now, let me know if anything goes awry!

Sarah

**Comment by redrambles** [comment]
Hey @yetanothersarah !

We're not seeing any changes here - are you sure that you pushed up your advice branch? Can you give it another try? `git push origin advice`

Thanks!

**Comment by redrambles** [comment]
Hey @yetanothersarah ! I went to check out your repository, and I see that you did indeed push this commit - but to your master branch, rather than on your advice branch. 

No worries! Here is how you can fix it.

1) Checkout your advice branch `git checkout advice`
2) Merge in your master branch `git merge master -m "merging with master"`
3) Push up your advice branch `git push origin advice`

Nice! Now your pull request should contain that index.html file.

In order to remove the commit that you accidentally made on the master branch, let's checkout the master branch now:

4) `git checkout master`
5) And now we'll roll it back in time with `git reset --hard 6517bb7` (this will reset that branch to this particular point in time.

Let us know how this goes!

**Comment by yetanothersarah** [comment]
That all seemed to go fine, but now there's a conflicting files message in this conversation - should I resolve that as well?

**Comment by acodeinprogress** [comment]
Hey @yetanothersarah,

Thanks for making those changes! I went ahead and fixed up the merge conflict so that we could move forward and merge this in. :)

xoxo,
Sharon

**Pull request merged**
