### PR TITLE
Some advice!

### PR DESCRIPTION
**Pull request by jgordon85**
I made some pretty advice.

### CODE REVIEW

**Comment by jgordon85** [comment]
Hoping this is all set.

**Comment by acodeinprogress** [comment]
Hey @jgordon85,

You're super close!
It looks like you deleted some other students work in the style.css and index.html files. You can see what was deleted by looking at the Files Changes tab near the top of the page or [here](https://github.com/skillcrush/skillcrush-104/pull/1550/files).

Once you add those back in, all you have to do is add, commit, and push and your changes will join your pull request here.

Happy git-ing!
-Sharon

**Comment by jgordon85** [comment]
Really bizarre, as I took care to not delete anything at all. I can certainly add it back in though.

**Comment by jgordon85** [comment]
I think it's all set now?

**Comment by acodeinprogress** [comment]
Hey @jgordon85,

You're almost there! It looks like you included some minus signs when you added back in other students code. The minus and plus signs that you see when looking at the Files Changed tab indicate what lines have been taken out or added in between versions, so they shouldn't be included in the code.

Happy git-ing!
-Sharon

**Comment by acodeinprogress** [comment]
Hey @jgordon85,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
