### PR TITLE
advice

### PR DESCRIPTION
**Pull request by srkiley1**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @srkiley1,

I have a few requests before we can merge this in.
1) You seem to have added 2 personal stylesheets. You only need to add one of those so you can delete the extra one.
2) It looks like you added all of the styles from the main style.css stylesheet into your custom stylesheets. All you need in there are your personal styles, so you can remove everyone else's. 
3) Your advice file looks like you copied the main index.html file. Instead, we'd like for you to copy and edit the advice-template.html file.

Once you make those changes, you can run a slightly different git command (`git add -A`), commit, and push and it'll join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by srkiley1** [comment]
Thanks.

**Comment by acodeinprogress** [comment]
Hey @srkiley1,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 4 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @srkiley1,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by srkiley1** [comment]
Thanks!

**Pull request closed without merging**
