### PR TITLE
Nicole advice

### PR DESCRIPTION
**Pull request by nicolecfarley**
Changed the content to reflect some of my own advice, as well as updated my own styling.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @nicolecfarley,

This looks great! I just have one teensy request for you. It looks like you added everyone's styles to your personal stylesheet. Since only your page will be accessing your stylesheet, you only need to include your personal styles. Once you fix that, you can add, commit, and push and your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @nicolecfarley,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 19 days if no changes are made.

**Comment by nicolecfarley** [comment]
Did everything work? So sorry about the delay, the Javascript course has me working hard! Hopefully I pushed it back properly with the changes, I was a bit confused as to how to do that again.

**Comment by acodeinprogress** [comment]
Great job, @nicolecfarley! Your code is all merged in.

**Pull request merged**
