### PR TITLE
Added new file

### PR DESCRIPTION
**Pull request by wperez185**

### CODE REVIEW

**Comment by wperez185** [comment]
Introductory file

**Comment by acodeinprogress** [comment]
Hey @wperez185,

Looks great! I only have 2 tiny requests for you. 
1) We'd love for you to include a link to your advice page in the main index.html file.
2) We would like for your ruby file to be in the ruby folder. 

If you could make those changes, then run git add -A, commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by wperez185** [comment]
I will get to you asap just have a family issue to resolve so once i resolve i will update.

Thank you for your patience

**Comment by wperez185** [comment]
Done i added link to my advice page and put ruby file in ruby folder and pushed code to github.

**Comment by acodeinprogress** [comment]
Great job, @wperez185! Your code is all merged in.

**Pull request merged**
