### PR TITLE
add my advice page, my styles, and then link to index.html

### PR DESCRIPTION
**Pull request by nitsirk**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @nitsirk, it looks like you added an extra CSS file. If you could delete it then run git add -A (the -A deletes the file in git), commit, then push, your changes will join your pull request and I can merge everything in!

**Comment by nitsirk** [comment]
Removed the extra css file and pulled upstream to fix merge conflicts.

**Comment by acodeinprogress** [comment]
Great work, @nitsirk! All merged in!

**Comment by nitsirk** [comment]
Thank you!

**Pull request merged**
