### PR TITLE
added new file

### PR DESCRIPTION
**Pull request by ekrul**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @ekrul,

Great work! I only have 1 tiny request for you. We would like for your ruby file to be in the ruby folder. If you could move it over there, then run git add -A, commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by ekrul** [comment]
Hey :)

I made the changes. Looks like I don't need to submit another pull request?

**Comment by acodeinprogress** [comment]
Hi @ekrul,

You're correct - you don't need to make another pull request. It looks like you have your file in the main directory as well as the ruby folder. All you have to do is delete the file in the main directory, then run git add -A (don't forget -A). Then you can commit, push, and your changes will be added to this pull request.

**Comment by acodeinprogress** [comment]
Thanks for making that change, @ekrul! Looks great! Your code is all merged in now. :)

**Pull request merged**
