### PR TITLE
new janel advice page and styling

### PR DESCRIPTION
**Pull request by janellucia**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @janellucia,

Looks great! I only have 2 tiny requests for you. We would like for your advice file to be in the advice folder. It would also be great if you could include a link to your advice page in the index.html file. If you could make those changes, then run git add -A, commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @janellucia,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by janellucia** [comment]
hi @acodeinprogress

I uploaded a day ago.....I may have done it wrong, I attached a screenshot of my upload when I tried to do a pull request today
 
screen shot 2016-08-05 at 12 13 49 pm

pls let me know how I can correct my mistake,
Thanks again Sharon!

**Comment by janellucia** [comment]
screen shot 2016-08-05 at 1 33 08 pm

**Comment by acodeinprogress** [comment]
Hmm... That looks odd. I checked your repo and you did create a pull request for your own repo rather than for the skillcrush repo. What is the url that you're on when you see that info?

**Comment by janellucia** [comment]
https://github.com/janellucia/skillcrush-104/pulls

**Comment by acodeinprogress** [comment]
Hey @janellucia,

This shows a pull request that you made for your own repo. It looks like you made a pull request to merge in Skillcrush's skillcrush-104's master branch into your own repo. Instead, you'll need to push any changes to your experients branch.

**Comment by janellucia** [comment]
Hey @acodeinprogress 

I notices in the commits tab in this conversation my second pull request. Could you check it out and let me know if thats what we are looking for?

screen shot 2016-08-06 at 8 01 41 pm

**Comment by acodeinprogress** [comment]
Hey @janellucia,

You're right - sorry about that!
The Files Changed tab shows that you have your advice page in the advice folder and one in the main directory. Could you delete the one in the main directory and then run git add -A (the -A will remove it on Git), commit, and push?

**Comment by janellucia** [comment]
@acodeinprogress Yay!
we figured it out. I deleted my advice page from the main dir. and i pushed it. It's in the commits tab (:
Thanks again sharon

**Comment by acodeinprogress** [comment]
Hey @janellucia,

That's awesome! I have one more change for you.
You have this in your advice page: href="css/style.css" - remember that the href link is relative to where our current file is. Since we're in the advice folder, you're linking to a css folder inside the advice folder (which doesn't exist). If you could change it so that it links to the right location (Hint: You'll need to have it go back a directory at some point), then add, commit, and push, I'll be able to merge in this pull request.

**Comment by acodeinprogress** [comment]
Hey @janellucia,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by janellucia** [comment]
Hey! Sorry I just saw all this.... doing it now (:

**Comment by janellucia** [comment]
Hi @acodeinprogress 
Just push the new version, the sweet thing is that I'm getting a ton of experience pushing and committing and navigating git in general. Thank you for all your patience

**Comment by acodeinprogress** [comment]
Hey @janellucia!

Thanks for making all those changes! and you're totally right - it IS great practice! Your code is now all merged in. :)

**Pull request merged**
