### PR TITLE
LizT advice page added

### PR DESCRIPTION
**Pull request by LizTW**
Added advice page html and css

### CODE REVIEW

**Comment by redrambles** [comment]
Hey there @LizTW!

Ok! Things are looking pretty good here but there are a few files that don't belong in the pull request, namely:

1) ruby/LizTW.github.io
and
2) ruby/index.html

I'm guessing you will probably want to hang on to your LizTW.github.io - so I would suggest that you put it elsewhere on your computer - but not inside another folder that is also under version control.

You can go ahead and delete the ruby/index.html file.

Once you've removed the .github.io folder and deleted that file, a `git status` inside your skillcrush-104 project will reveal that these changes have been picked up by Git. In order to proceed to a commit, you will first need to add these changes with:

`git add -A`

and then commit:

`git commit -m "your message here"`

and then finally push up once more:

`git push origin master`

which will automatically update your pull request.

At that point we should be good to merge in your code. 

Let us know if you have any questions!

**Comment by LizTW** [comment]
Thank you!  I think everything should be good to go now!

Liz Tracy
liz@liztracywriting.com
www.liztracywriting.com
Twitter: @liztracywriting
Instagram: LizTracyWriting


"Don't forget - no one will see the world the way you do, so no one else will be able to tell the stories you have to tell." Charles de Lint

**Comment by redrambles** [comment]
Hey @LizTW,

Thanks for the update! I'm not seeing any new commits on this branch that would address our issue, though. Did you forget to push up your changes?

**Comment by acodeinprogress** [comment]
Hey @LizTW,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
