### PR TITLE
added advice to skillcrush 104 repo

### PR DESCRIPTION
**Pull request by harrismalcolm**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @harrismalcolm!

This is almost ready to go - but it looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's. Once you make that change, you can add, commit, and push and it'll join your pull request here. :)

Let us know if you have any questions!

Cheers,
Ann

**Comment by harrismalcolm** [comment]
I went and deleted all other styles in my style.css other than me own.

**Comment by redrambles** [comment]
Hi @harrismalcolm! 

I see that you've merged your master branch into your advice branch - which is great in terms of keeping it up to date with the main codebase - but I don't see any changes to your code. If you run `git status` while in still in your advice branch, do you see that there is a change to your css/macharris-style.css file that still needs to be added and committed? 

Once you add and commit that change to your stylesheet, you can push up your advice branch once more, which will automatically update this pull request. 

Let me know if you have any questions!

**Comment by redrambles** [comment]
Hi @harrismalcolm - 

Your other pull request was merged (yay!) - so we are going to close this one. :)

**Pull request closed without merging**
