### PR TITLE
added advice and style file for karenh

### PR DESCRIPTION
**Pull request by karenhowell**
Updated advice section for karenchanel file

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @karenhowell,

Looks great! I only have 2 tiny requests for you. 

1) It would be great if you would add a link to your advice page in the index.html file.
2) It looks like you added all of the styling from style.css. All you need in that file is your personal styles. 

If you could make those changes, then add, commit, and push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @karenhowell,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @karenhowell,

This is just a reminder that this pull request will close in 10 days if no changes are made.

**Comment by karenhowell** [comment]
Ok I've updated the files for karenchanel as requested :)

**Comment by acodeinprogress** [comment]
Hey @karenhowell,

I don't see that any changes were made. Did you remember to push your code up to GitHub?

**Comment by karenhowell** [comment]
I see my changes on Github, should I submit a new pull request?

**Comment by acodeinprogress** [comment]
Hey @karenhowell,

It's totally up to you! If you want to submit a new pull request, go for it! :)

**Comment by karenhowell** [comment]
Ok I think I fixed it :)

On Tue, Jun 7, 2016 at 9:03 AM, Sharon <notifications@github.com> wrote:

> Hey @karenhowell <https://github.com/karenhowell>,
>
> It's totally up to you! If you want to submit a new pull request, go for
> it! :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/skillcrush/skillcrush-104/pull/524#issuecomment-224328727>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMRXijIIH1uEahFB0s9eNp_GOyrRyg06ks5qJZZZgaJpZM4IZlIE>
> .
>



-- 
~~~~~When Life hands You Lemons, Make Lemonade with a Twist!~~~~~

**Comment by acodeinprogress** [comment]
Great work, @karenhowell! Your code is all merged in.

**Comment by karenhowell** [comment]
Yes! so proud! Thanks :)

On Fri, Jun 10, 2016 at 10:49 AM, Sharon <notifications@github.com> wrote:

> Great work, @karenhowell <https://github.com/karenhowell>! Your code is
> all merged in.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/skillcrush/skillcrush-104/pull/524#issuecomment-225249786>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMRXii-73ACvWLEJHHNR-FDHIa-ZORONks5qKaOwgaJpZM4IZlIE>
> .
>



-- 
~~~~~When Life hands You Lemons, Make Lemonade with a Twist!~~~~~

**Pull request merged**
