### PR TITLE
committing Alicia's Advice

### PR DESCRIPTION
**Pull request by arufino**
Hi! I did the whole exercise again from scratch. I hope it's working now!!
Sorry for the extra work :)

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @arufino,

This is veeeery close! It looks like you changed the link to the style.css page in index.html. Remember that ../ goes back a directory. Our style.css file is in our css folder and our css folder is in the same directory as our index.html file so we don't have to go back a directory, only forward into the css folder, which is why we had it set to css/style.css.

**Comment by arufino** [comment]
@acodeinprogress 
At least I'm learning the git codes by heart :)
Does it look better now?
Thanks!
Alicia

**Comment by arufino** [comment]
@acodeinprogress 
Hi Sharon! Do I have everything now or can I wrap up the lesson?
Thanks & have a wonderful weekend!
Alicia

**Comment by acodeinprogress** [comment]
Hey @arufino,

Looks great! Your code is all merged in.

**Pull request merged**
