### PR TITLE
test push forked repo

### PR DESCRIPTION
**Pull request by kkait**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @kkait,

Looks great! I only have 1 tiny request for you. We would like for your ruby file to be in the ruby folder. If you could move it over there, then run git add -A, commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by kkait** [comment]
I think it was already in my ruby folder? I might have moved it there after
I pushed it, so I just tried it again.  Did it work this time?

This is what my terminal was reading:

**Comment by kkait** [comment]
Just kidding, I was confused because multiple "ruby" directories on my
computer.  I am fairly certain I actually did it correctly this time. As in
about 30 seconds ago.

**Comment by acodeinprogress** [comment]
Hey @kkait,

Thanks for making that change! I have 1 more request for you. We'd love for you to add some css for your advice page. If you could do that then add, commit, and push, I'll merge in your code. :)

**Comment by kkait** [comment]
Done.  Since it was such a small amount of css I had just put it at the top
of my html file.  I moved it to it's own file (kate-advice-style.css) in
the css directory so should be good now.

Thanks

**Comment by acodeinprogress** [comment]
Hey @kkait,

One more thing:
It looks like you're using an absolute url (file:///Users/kkait/Sites/Ruby/skillcrush-104/advice/kate-advice.html) to your page. Since we can't access your computer (which is definitely a GOOD thing), when we click on that link, it'll give us an error. What you want to do instead is use a relative path. This says that "you can find this folder in this location in relation to where I'm at now". So when users are on the index page, they're in the main directory. In relation, your advice file is in the advice folder. So all you have to do is use "advice/kate-advice.html"

**Comment by kkait** [comment]
Ok, I think I fixed it. Sorry for all the tedious bugs.

Kate

**Comment by acodeinprogress** [comment]
Hey @kkait,

Last thing. You made a custom css file but you're not linking to it. Instead, you're linking to style.css. Go ahead and fix that and then I can get your code all merged in.

**Comment by acodeinprogress** [comment]
Hey @kkait,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by kkait** [comment]
Hi,

Sorry I must have clicked through the previous e-mail without reading it,
or otherwise failed to recall it. I changed the link to my custom css.

Thanks, sorry I keep forgetting all of these things.
Kate

**Comment by acodeinprogress** [comment]
Hey @kkait,

No problem at all! It looks like there's a merge conflict happening. Do you remember how to resolve this?

**Comment by kkait** [comment]
I did a factory reboot of my laptop last week (wildcard, I know), so I
didn't have the files on my hard drive.  I edited the file from the github
web UI.  I think I see what the issue is (line 212 of index.html), but I
don't know how to resolve it.

I cloned the pull request onto my computer but it isn't showing up as a
merge conflict from my command line.

I'm stuck.  Should I just submit a new pull request and try again?

**Comment by acodeinprogress** [comment]
Hey @kkait,

You'll need to get the latest changes from the skillcrush-104 repo and try to merge them with your code on your computer. Then you should get a merge conflict that you can fix.

If you'd prefer, you can also submit a new pull request. But it's totally up to you!

**Pull request closed without merging**
