### PR TITLE
Added Savannah Barlow Advice HTML and CSS

### PR DESCRIPTION
**Pull request by savannahbarlow**
Hi. I added some advice and gave it some css. :)

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @savannahbarlow,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @savannahbarlow,

Unfortunately, it looks like you removed another student's link to their advice page in the index.html file. You can see it by looking at the [Files Changed](https://github.com/skillcrush/skillcrush-104/pull/2018/files) tab near the top of the page. It is highlighted in pink.

If you could add that back in and then add, commit, and push, that would be fantastic and then we can merge this in!

xoxo,
Sharon

**Comment by savannahbarlow** [comment]
-___-; I'm so sorry. I was trying to fix the conflict and thought it was a duplicate. I fixed it and hopefully, we're all good now....please LOL :)

**Comment by redrambles** [comment]
Hey @savannahbarlow,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
