### PR TITLE
Added Kelly Von styles

### PR DESCRIPTION
**Pull request by KellyVon**
Updated my styles.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @KellyVon,

Looks great! I only have 1 tiny request for you. It looks like you added styles to both your custom stylesheet and style.css. Since you linked to your personal stylesheet in your advice page, I would recommend removing your styles from style.css. Once you do that, you can add, commit, then push, and your changes will join your pull request here.

Let me know if you need any help!

**Comment by KellyVon** [comment]
Hi Sharon,

I think I need help then :).  That was one of the conflict errors I had, so
I did go in and remove from Style.css and saved.  Then added, committed and
pushed.  I have checked my git status...and have "working tree clean".

I have opened the Style.css just now to double check and I see that it is
removed.  But on Git, I see that it isn't showing that I deleted...would be
in red, correct?

I'm puzzled...lol

Kelly

Thanks,
Kelly

**Comment by acodeinprogress** [comment]
Hey @KellyVon,

Could you show me a screenshot of what's happening?

**Comment by acodeinprogress** [comment]
Hey @KellyVon,

I can't see your images. Could you try attaching them following the instructions right below in the comment box?

**Comment by KellyVon** [comment]
Hi Sharon, 

I was reply by email...let's try again but in Git Hub :)

git_commit_screenshot

no_styles_on_style_sheet

clean

**Comment by acodeinprogress** [comment]
Hey @KellyVon,

Does the css file you're looking at on your computer happen to be in the advice folder?

**Comment by KellyVon** [comment]
Hi Sharon, sorry for the delay getting back to you.

No, I have created the file on my desktop/skillcrush-104/css/kellyvon_style

Kelly

Thanks,
Kelly

**Comment by acodeinprogress** [comment]
Hey @KellyVon,

Could you send an email to your blueprint-specific email? I or another one of the instructors will help you with this. :)

**Comment by acodeinprogress** [comment]
Hey @KellyVon,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by KellyVon** [comment]
Hi Sharon,

Sorry, I thought I would carry on with the course and then come back to this one after...I will take a look again today or tomorrow and will put in that email to my blueprint email address.

thanks!
Kelly

**Comment by acodeinprogress** [comment]
Hey @KellyVon,

We still haven't heard from you in a while. This is just a reminder that this pull request will close in 10 days if no changes are made.

**Comment by KellyVon** [comment]
Hi Sharon,

I did send in an email and Ann has given me some suggestions, so I will
take a stab at those.

Kelly

Thanks,
Kelly

**Comment by acodeinprogress** [comment]
Thanks for making those changes, @KellyVon. Your code is all merged in.

**Pull request merged**
