### PR TITLE
Adding project for Mollie Morrison

### PR DESCRIPTION
**Pull request by mollieemo**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @mollieemo,

This looks great so far! I have a couple small requests for you before we can merge this in.
1) It looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's.
2) We would like for you to include a link to your advice page in the index.html file.

Once you make those changes, you can add, commit, and push and they'll join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by mollieemo** [comment]
Awesome, thanks Sharon! I have made these changes and pushed.

**Comment by redrambles** [comment]
Hey @mollieemo !

This is great - thanks for making that CSS change! The only thing that we are missing now, is a link to your advice file in the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links and see if you can add one of your own!

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by acodeinprogress** [comment]
Hey @mollieemo,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
