### PR TITLE
Added link in HTML and updated local repository-This should be correct now.

### PR DESCRIPTION
**Pull request by sluzkow**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @sluzkow  !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in.

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by redrambles** [comment]
Hello @sluzkow !

Ok! I think I might have been unclear in my last message. What we need is a link inside the index.html document that will point to your advice/stevel-advice.html advice page. You added a link to the class inside your advice/stevel-advice.html page, but we don't need that.

Here's what remains to be done! :)

1) Please remove the `<link href="https://github.com/skillcrush/skillcrush-104/advice">` from your advice/stevel-advice.html document.

2) In the main index.html page, at the bottom of the long list, add a link to your advice page.

3) Delete the stevel-advice.html file that was added to the root of the repository - we just want to keep the 'advice/stevel-advice.html' file.

Once you have made those changes, make sure to add `git add -A` - commit `git commit -m "your message here"` and then push up your branch once more, which will automatically update this pull request.

Then we should be all good to merge in your code!

Let us know if you have any questions! :)

Cheers,
Ann

**Comment by acodeinprogress** [comment]
Hey @sluzkow!

Almost! Right now, you're adding a link to your advice page inside of your advice page. You're also using a behind the scenes <link> that we normally reserve for things like stylesheets and fonts.

Instead, you'll want to go to the index.html file and open it in your text editor. If you scroll down to the <body> tag, you should see a bunch of <a> tags from other students that link to their advice pages. That's the kind of link that we want you to add in that file.

There's one last step. Right now, you have one advice page in the main directory and one advice page in the advice folder. You'll want to keep the one in the advice folder and delete the one in the main directory.

Once you take all those steps, you'll run a slightly different git command (git add -A), commit, and push.

xoxo,
Sharon

**Comment by sluzkow** [comment]
Omg. So close yet so far! I’ll get to that shortly. Thank You!!

**Comment by redrambles** [comment]
Hey @sluzkow ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Comment by sluzkow** [comment]
No problem.
I have a lot going on.

**Comment by redrambles** [comment]
Sure thing - no problem! Take your time. :)

**Pull request closed without merging**
