### PR TITLE
Advicetwig

### PR DESCRIPTION
**Pull request by kategackerman**
just practicing

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @kategackerman,

I only see changes to the stylesheet in your pull request. It would be great if you could add an advice page that uses that stylesheet and also include a link to your advice page in index.html.
Once you do that, you can add, commit, and push and your changes will join your pull request here.

Let me know if you need any help!

**Comment by kategackerman** [comment]
Thanks – I just tried again.

I am confused about a few things:
1.  After you make a branch, do you need to add the files to it that you are going to work on before making the edits?
2.  Do you edit multiple files on one branch (both the css and html) or should they be on separate branches?

Thanks,

Kate

**Comment by acodeinprogress** [comment]
Hey @kategackerman,
1.  After you make a branch, do you need to add the files to it that you are going to work on before making the edits?
Once you make a branch, you can start editing files. The reason we use branches is to prevent things from getting clogged up on master when multiple people work on a project. A branch is almost like your own repo. You can treat it as you would master, except that it will be merged into master at a point later down the road.
2.  Yep! You can edit, add, remove multiple files. 

It looks like you made the changes on your banana branch rather than your advicetwig branch. There are a couple options. 1) You could make the changes on your advicetwig branch. 2) You could close this pull request and make a new one for your banana branch.
I also noticed a couple things on your banana branch.
1) You added styles to the style.css stylesheet and made your own personal stylesheet. On that note, your personal stylesheet also had all the styles from style.css. Since only your page will be using your personal stylesheet, you only need to include your personal styles.
2) You're linking to the style.css file but you made your own stylesheet. If you want to use style.css, you can delete your custom stylesheet. If you want to use your custom stylesheet, you can remove the changes in style.css and use src in your advice page to link to your custom stylesheet.
3) It looks like you included all the links from the index.html file in your advice page. We only want your advice page to link back to the index page. The index page will take care of linking to everyone else's pages.

**Comment by acodeinprogress** [comment]
Hey @kategackerman,

I'm going to close this pull request since you submitted a new one.

**Pull request closed without merging**
