### PR TITLE
Styled my advice

### PR DESCRIPTION
**Pull request by LenaEbb**

### CODE REVIEW

**Comment by LenaEbb** [comment]
Here's some advice for the newbies...

**Comment by acodeinprogress** [comment]
Hey @LenaEbb,

This looks great so far! I have a couple small requests before we can merge this in.
1. It looks like you created 2 different CSS files and 2 different advice files. If you could delete the advice file that doesn't have the .html extension and also delete the extra CSS file, that would be fantastic!
2. We'd love for you to include a link to your advice file inside the index.html file.

Once you do that, you'll need to run a slightly different git command (git add -A), then commit and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @LenaEbb !

No worries! Can you please show us a screenshot of what you are seeing in the terminal when you attempt to delete those files? Thank you!

If you prefer to communicate with us via e-mail - which may make including screenshots simpler - feel free to do so! (questions@skillcrush.com)

**Comment by redrambles** [comment]
Hey again! I see that you've opened another pull request - shall I close this one?

**Comment by acodeinprogress** [comment]
Hey @LenaEbb,

It looks like you opened another pull request and we haven't heard from you in a while on this one so I'm going to close this pull request.

xoxo,
Sharon

**Comment by LenaEbb** [comment]
Omg, 
Sorry, I got busy with another project, totally didn’t get anymore what I was supposed to do lol. Can I do this assignment again step by step and pull again to make sure it’s right? Thank you!

Lena

**Pull request closed without merging**
