### PR TITLE
My changes

### PR DESCRIPTION
**Pull request by Ebyakin**
Some advice

### CODE REVIEW

**Comment by Ebyakin** [comment]
!!!!

**Comment by acodeinprogress** [comment]
Hey @Ebyakin,

This looks great! I just have 2 teensy requests before I merge this in.
1) We would like for you to include a link to your advice page in the index.html file.
2) It looks like you're missing a closing tag in your advice file.
If you could add that those in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by Ebyakin** [comment]
Done! Please check that everything is ok
Regards,
Evgeniy

**Comment by acodeinprogress** [comment]
Hey @Ebyakin,

It looks like you pushed your changes to your master branch rather than your ebyakin branch. You'll need to push them to this branch instead so that they'll get merged in.

xoxo,
Sharon

**Comment by Ebyakin** [comment]
Hi Sharon! 
I did it one more time, you can see a screenshot, as I understood I
screen shot 2017-06-07 at 08 00 42
 needed to "git push -u origin master" when I on the Ebyakin branch, is it right?
By the way, terminal asked for a password again, I thought that I fixed it (here is topic and solution that I implemented https://groups.google.com/forum/?hl=en&utm_source=hs_automation&utm_medium=email&utm_content=36543814&_hsenc=p2ANqtz-9MDbJNwy_KkARvRtl-f8KDVjUPWqQBCbGjUbPasV5fzJ5TBnxapuRN5prSb9rK7mK0rKzQS19y46FBMLi-dyG56gLGiw&_hsmi=36543814#!category-topic/skillcrush-front-end-developer-april-2017/questions-skillcrush-105/D3EncL5giEw) Guess what is a 
screen shot 2017-06-07 at 08 00 42
a problem could be with it?

**Comment by acodeinprogress** [comment]
Hey @Ebyakin,

Sorry for the delay! You shouldn't push your branch changes to your master branch. That's why we have a separate branch - the code in it should stay separate from master. What you'll need to do is push your ebyakin code to your ebyakin branch. So while you are on your ebyakin branch, you'll do **git push -u origin ebyakin**.
Try that out and see what happens!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Ebyakin,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 10 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by Ebyakin** [comment]
Hi @acodeinprogress  Sharon! 
Sorry for long silence.
It seems I've done it eventually!) Please check it out
screen shot 2017-06-25 at 23 05 32

**Comment by acodeinprogress** [comment]
Awesome work, @Ebyakin! Your code is all merged in.

xoxo,
Sharon

**Comment by Ebyakin** [comment]
Hooray!!!

**Pull request merged**
