### PR TITLE
added my own branch files

### PR DESCRIPTION
**Pull request by BradNoyes**
my attempt at this project

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @BradNoyes!

This is super close!! I just have a couple small requests before I can merge this in.
Take a really close look at the link that you added to the index.html file. Do you see anything missing at the very beginning?
Your HTML file has two .html extensions. I would suggest renaming your file so that it only has one.

Once you make those changes, you'll need to run a slightly different git command (git add -A), then commit and push. They'll join your pull request here and we'll be able to get your code merged in.

If no changes are made in 10 days, this pull request will close.

Let us know if you need any help!

xoxo,
Sharon

**Comment by BradNoyes** [comment]
Thanks Sharon.. Changes made.  Cheers. Brad

**Comment by BradNoyes** [comment]
Oops.

**Comment by BradNoyes** [comment]
Hi Sharon,I made the changes and pushed it.  Silly mistakes.Thank you.  Brad 


-------- Original Message --------
Subject: Re: [skillcrush/skillcrush-104] added my own branch files
(#1733)

**Comment by redrambles** [comment]
Hey @BradNoyes,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Comment by BradNoyes** [comment]
YAY!Thanks Ann.Best regards, Brad 


-------- Original Message --------
Subject: Re: [skillcrush/skillcrush-104] added my own branch files
(#1733)

**Pull request merged**
