### PR TITLE
added shylos advice and style

### PR DESCRIPTION
**Pull request by shys**
here you go.

### CODE REVIEW

**Comment by shys** [comment]
yup here's a message.

**Comment by acodeinprogress** [comment]
Hey @shys ,

This looks great! I just have a few small requests before we can merge this in.

1. We would like for you to include a link to your advice page in the index.html file. 
2. It seems as though some extra files snuck into the pull request. They are called `desktop.ini` and are in the `advice`, `css`, `ruby` folders as well as in our main `skillcrush-104` folder. These files will need to be deleted.

Once you do that, you'll need to run a slightly different git command (git add -A), commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by shys** [comment]
I think I got it. Let me know if there are any problems.

Thanks,
Shylo

**Comment by redrambles** [comment]
Hello @shys,

Ok! If you have a look at this [view here](https://github.com/skillcrush/skillcrush-104/pull/1996/files), you will see your particular change set that is contained in your pull request. As you can see - there are several files there that don't belong (namely all the '.ini') files - and we still need a link to your advice page on the main index.html file. 

Your advice is great - your advice page and your CSS are totally fine - we just need you to remove the .ini files and to edit the main index.html file in order to add a link to your advice page - so that others can discover your words of wisdom! :) Your pull request should contain three files - your advice page, your advice styles and the main index.html file.

Once you have made those changes, please add (`git add -A`) - commit (`git commit -m "your message here"`) and push up your branch once more (`git push origin experiments`) - which will update your pull request.

Please let us know if you have any questions!

Cheers,
Ann

**Comment by redrambles** [comment]
Hey @shys,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
