### PR TITLE
Practicing pull and merge

### PR DESCRIPTION
**Pull request by laghee**
Practice practice practice ...

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @laghee,

Looks great! I only have 1 tiny request for you. We would like for your ruby file to be in the ruby folder. We'd also like for it to have some ruby content. If you could add some ruby code and move it over there, then run git add -A (don't forget the -A), commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @laghee,

I'm still seeing your ruby file in the main directory. If you could remove it then run a slighty different git add command (git add -A), commit, and push, it'll remove it from your Files Changed.

**Comment by laghee** [comment]
Hi, I think I did it, although possibly the wrong way ... Let me know!

**Comment by acodeinprogress** [comment]
Hey @laghee,

That's perfect! Thanks for making that change! Your code is all merged in.

**Pull request merged**
