### PR TITLE
My Advice Challenge

### PR DESCRIPTION
**Pull request by cshomaker**

### CODE REVIEW

**Comment by sareg0** [comment]
Hey @cshomaker great work. However, I notice that in your styles file, you are committing the CSS for everyone. Could you please try stripping everything out that you don't need in that file, and the adding, committing and pushing the changes. This will update your pull request. Many thanks!

**Comment by cshomaker** [comment]
Oops... I was copying how others did it but got confused and used the full one. I've just changed it and am working my way through notes to remember the commit/push/pull etc process (I'm rusty - had to focus on a couple RWD projects). Thanks for letting me know!

**Comment by cshomaker** [comment]
Hi @sareg0 I just completed the steps up to push... If I understand your message I don't need a new pull request, so I think I'm done but if I've missed a step please let me know :)

**Comment by sareg0** [comment]
yes that's it @cshomaker ! You got it 100% right. I'm going to merge this puppy now :)

**Pull request merged**
