### PR TITLE
Adds my contribution to project

### PR DESCRIPTION
**Pull request by sadiejay**
Some advice I'd like to share! :)

### CODE REVIEW

**Comment by redrambles** [comment]
Hello @sadiejay !

This is great - but we cannot accept the icon files are are [included in this pull request.](https://github.com/skillcrush/skillcrush-104/pull/1867/files) Please remove them from your sadiejay branch, and then run `git add -A` followed by `git commit -m "your message here"` to add and commit that change. Then you'll be all set to push up your branch, which will update your full request (`git push origin sadiejay`).

At that point, we should be all good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by sadiejay** [comment]
@redrambles Hi Ann!

Those darn Icon files! *shakes fist* I deleted them from the branch using the -rm rf in the terminal as well as the .DS_Store files. However, when I check git status, there seems to be no changes to commit. I'm not sure what to do at this point.

**Comment by redrambles** [comment]
Hey @sadiejay ! These appear to be files, not repositories - so that would explain why the deletion didn't take with 'rm -rf' you can remove them without the '-r' flag (you shouldn't need the 'f' flag either):
`rm Icon`
You can also open up your Finder / Explorer and find the files that way, and drag them to the Trash. 

Then when you run `git status` - you should see that Git has picked up on the deletion of those three items. Then you can add with `git add -A`, followed by your commit `git commit -m "die, icon files, die"` (maybe another message would be best) and then finally you can push up your branch (`git push origin sadiejay`) - which will automatically update this pull request.

Let us know how it goes!

Cheers,
Ann

**Comment by acodeinprogress** [comment]
Hey @sadiejay,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
