### PR TITLE
Let the fork begin!

### PR DESCRIPTION
**Pull request by micinmylefthand**

### CODE REVIEW

**Comment by micinmylefthand** [comment]
Fork, Spoon, Knife

**Comment by acodeinprogress** [comment]
Hey @micinmylefthand,

Looks great! I only have 1 tiny request for you. We would like for your ruby file to be in the ruby folder. If you could move it over there, then run git add -A, commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by micinmylefthand** [comment]
Sorry for the delay!  The file is now moved.

**Comment by acodeinprogress** [comment]
Hey @micinmylefthand,

Perfect! I just have one more request for you. We would love for you to include a link to your advice page in the index.html file. Once you add that, you can add, commit, then push.

Again, let me know if you need any help!

**Comment by micinmylefthand** [comment]
You know, for some reason, I thought i was supposed to be adding the advice link to my github io page.  Sorry about that.  Should be good now!  Thanks for your patience!

**Comment by acodeinprogress** [comment]
Hey @micinmylefthand,

No problem at all! Thanks for making those changes! Your code is all merged in.

**Pull request merged**
