### PR TITLE
104-changes

### PR DESCRIPTION
**Pull request by SJUDD84**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @SJUDD84,

It looks like you deleted some other student's files. Instead, we'd like for you to add your own advice and css files and a link to your advice page in the index.html file. If you could restore the advice pages tat you deleted and then add in your own, that would be great! Once you do that, you can add, commit, and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by SJUDD84** [comment]
Hi @acodeinprogress - 

Sorry, I have no idea how that happened. How would I restore the advice pages that were deleted? 

Thanks,
Siobhan

**Comment by acodeinprogress** [comment]
Hey @SJUDD84,

It looks like you attempted a revert earlier. You could try doing that again. and you can make sure everything is fine by checking the Files Changed tab.

xoxo,
Sharon

**Comment by SJUDD84** [comment]
It doesn't give me an option to revert back. I'm not sure how the other student's files got taken out and I can't even tell if mine were added in. I don't want to mess anything else up - is there a way to undo this and I can try another pull request for my files?

Thanks!
-Siobhan

**Comment by acodeinprogress** [comment]
Hey @SJUDD84,

If you want, you can close this pull request and open up another one. :)

xoxo,
Sharon

**Pull request closed without merging**
