### PR TITLE
Adding my advice and css files

### PR DESCRIPTION
**Pull request by sandyvern**
I have attempted to style up my advice sheet...not exactly how I had hoped for, as I was attempting to make the background color a light blue...and although I added what I thought might work to my styles it remains a white background. Would love any advice as to what I might be doing wrong with that!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @sandyvern,

This looks great! I only have a couple requests for you before I can merge this in. First, it looks like you edited the advice-template. When naming classes, we use lowercase letters. Also, the name of the class in the HTML and the name of the class in CSS are case sensitive and they have to match exactly. So we don't want to change skillcrush-advice to Skillcrush-advice for those reasons. If you could change that back, that would be great! The second change I have for you is to add a link to your advice page in the index.html file so that everyone can link to your page! Once you make those changes, you can add, commit, and push and your changes will join your pull request here.

Let me know if you need any help with this!

**Comment by sandyvern** [comment]
Ok...I think I have corrected all of your changes.

**Comment by acodeinprogress** [comment]
Hey @sandyvern,

Thanks for making those changes! I just have one more request for you! Would you mind adding a link to your advice page in the index.html file? Once that's done, you can add, commit, and push.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @sandyvern,

We haven't heard from you in a while. This pull request will be closed in 10 days if no changes are made.

Again, let me know if you need any help!

**Comment by sandyvern** [comment]
Sorry thought I had done that already...add link to my advice page now.

**Comment by acodeinprogress** [comment]
Great work, @sandyvern! Your code is all merged in.

**Pull request merged**
