### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by tomilynn814**
I am not seeing the changes I made to my css and html. I see the original the I did.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @tomilynn814 !

This is great! The only thing that needs to change is that your `advice/tomilynns-advice.html` file is still linking to the `css/style.css stylesheet` - but we want it to link to your custom `css/tomilynn-advice.css` instead. Once you make this change, we will be good to merge in your code! Yay!

1) Make sure that you are in your **advice** branch. `git checkout advice`
2) Using your text editor, open up your 'advice/tomilynns-advice.html' file and make that correction to link to the correct stylesheet (around like 5)
3) Save your file, and add `git add advice/tomilynns-advice.html` and commit `git commit -m 'fix link to stylesheet` 
4) Push up your branch once more `git push origin advice`, which will automatically update this pull request.

That's it! At that point we should be good to merge in your code.

You're nearly there!!

Ann

**Comment by tomilynn814** [comment]
Am I not linking this correctly it seems right but I must be missing
something?
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="../css/ tomilynn-advice.css">
<link rel="stylesheet" type="text/css" href="../css/style.css">
<link href="https://fonts.googleapis.com/css?family=Lobster|Merriweather"
rel="stylesheet">

<title>Tomilynn's Advice</title>
</head>


<body class="tomilynns advice">
<header>
<a href="..index.html">Back to Main Page</a>
<h1>Want to learn to Code<...></h1>
<h3> Here's some advice</h3>
</header>

<section>
<div class="advice">

**Comment by tomilynn814** [comment]
going back and looking at this another time it looks like I have css
linking 2xs one with mine and other with the original so I took the
original out and left mine I think this is the problem I am having.

**Comment by redrambles** [comment]
Hey @tomilynn814 ,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Comment by tomilynn814** [comment]
Yay! Thank You! I think I am beginning to understand how this all works

**Pull request merged**
