### PR TITLE
Merge pull request #1101 from skillcrush/redrambles-patch-1

### PR DESCRIPTION
**Pull request by mrsbrown08837**
Trying to open a pull request

Update style.css

### CODE REVIEW

**Comment by mrsbrown08837** [comment]
learning how to work with github

**Comment by rockatthebeach** [comment]
Seeing if I've successfully created a pull request & comparing across lesson fork and my own fork.

**Comment by juliet24440** [comment]
I'm learning how to work with github.

**Comment by skillsofcourt** [comment]
Currently learning how to work with github! Practicing on how to submit pull request.

**Comment by tinkdarkness** [comment]
GitHub practice

**Comment by debramort** [comment]
Hoping I get GitHub

**Pull request closed without merging**
