### PR TITLE
Branch 1

### PR DESCRIPTION
**Pull request by tylermoroz**
sharing my advice

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @tylermoroz!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links and see if you can add one of your own!

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by tylermoroz** [comment]
Sorry I’m not too sure what you mean. I thought my advice page was linked.

Sent from Mail for Windows 10

**Comment by acodeinprogress** [comment]
Hey @tylermoroz,

I'm not seeing your changes here. Did you make sure to make them on your `branch-1` branch and then push up to your `branch-1` branch on GitHub?

xoxo,
Sharon

**Comment by tylermoroz** [comment]
adding Tyler's Advice

**Comment by tylermoroz** [comment]
I made sure that I was adding and committing on branch-1 and then I used
git push origin branch-1 and it asked for my code and it said everything is
up to date

**Comment by redrambles** [comment]
Hey @tylermoroz ,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
