### PR TITLE
created km.rb

### PR DESCRIPTION
**Pull request by KimBlackmore**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @KimBlackmore,

Great work! I only have 1 tiny request for you. We would like for your ruby file to be in the ruby folder. If you could move it over there, then run git add -A, commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @KimBlackmore,

We haven't heard from you in a while. This pull request will be closed in 20 days if no changes are made.

Again, let me know if you need any help!

**Comment by KimBlackmore** [comment]
Hi I think I have done that now.

**Comment by acodeinprogress** [comment]
Thanks for making those changes, @KimBlackmore! Your code is all merged in.

**Pull request merged**
