### PR TITLE
My advice page

### PR DESCRIPTION
**Pull request by dicksonca**
Github practice!

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @dicksonca!

This is almost ready to go - but it looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's. Once you make that change, you can add, commit, and push and it'll join your pull request here. :)

Let us know if you have any questions!

Cheers,
Ann

**Comment by dicksonca** [comment]
Hi Ann!

I wondered if I should delete all those extra lines of code! I fixed my css file and attempted to add, commit, and push the changes, but have been having some trouble. I looked back at the lesson and checked out the git guides, but I can't seem to solve my own problem. Attached is a screenshot of my latest attempt. What am I doing wrong? 

screen shot 2018-02-22 at 9 24 30 pm

**Comment by redrambles** [comment]
Hello @dicksonca!

Ok! What I can see at the moment is that you are in your master branch, rather than in your experiments branch. Let's begin by removing that 'advice/advice-template copy.html' file, which we don't need.

`rm "advice/advice-template copy.html"`

The quotation marks are important here, as there is a space in the name and we want to make sure that we are deleting this particular file. Run `git status` again, and you should only see your 'css/cdickson-styles.css' file. 

Now check out your branch: `git checkout experiments`. Git will notice that your css/dickson-styles.css' file has been modified. If you run `git status`, you should only see this file listed. Now we will need to add it `git add .` and commit the change `git commit -m "your message here"` and then you will be able to push up your branch `git push origin experiments` which will automatically update this pull request, given that it is based off of your experiments branch.

At this point, we should be good to merge in your code. Let us know how it goes and if you have any questions! :)

Cheers,
Ann


Once you've done that

**Comment by dicksonca** [comment]
Ok, I think I got it! This was a messy learning experience, but I feel much more confident about this process now. Thank you!

**Comment by redrambles** [comment]
Hey @dicksonca,

Excellent! Everything is good, now - we are merging in your code. Great work!

Cheers,
Ann :)

**Pull request merged**
