### PR TITLE
updated the html and css files

### PR DESCRIPTION
**Pull request by romadelrey**
woo hoo!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @romadelrey,

It looks like you added 2 different personal stylesheets and both of them contain all of the styles from the main style.css stylesheet. All you need is 1 personal stylesheet and your personal styles, so you can remove everyone else's styles and the extra file. I also noticed that you didn't include a link to your advice page in the index.html file. Once you make those changes, you can run a slightly different git command (git add -A), commit, and push and it'll join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @romadelrey,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 20 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by romadelrey** [comment]
Oh will do! Sorry I'm on vacation

**Comment by acodeinprogress** [comment]
Hey @romadelrey,

Just wanted to check in and see if you were back from vacation yet. 

Hope you had/are having a great time!

xoxo,
Sharon

**Comment by romadelrey** [comment]
Almost! I'll be back on Monday, I can resend it then if that's still in the
time frame!

**Comment by romadelrey** [comment]
Hi Sharon,

I think I may start from scratch. Sorry for keeping you hanging! Feel free
to delete it

**Comment by acodeinprogress** [comment]
Hey @romadelrey,

That's perfectly fine! I'll go ahead and close this and keep an eye out for your new pull request. :)

xoxo,
Sharon

**Pull request closed without merging**
