### PR TITLE
Khrunde new branch

### PR DESCRIPTION
**Pull request by khrunde**
first pull request

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @khrunde,

It looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's. Once you make that change, you can add, commit, and push and it'll join your pull request here.

Let us know if you need any help!.

xoxo,
Sharon

**Comment by khrunde** [comment]
Just checking in to see if I fixed it...thanks!

**Comment by acodeinprogress** [comment]
Hey @khrunde,

It looks like you made those changes on your master branch rather than your khrunde-new-branch. You'll need to push to the right branch in order for the changes to show up in this pull request.

xoxo,
Sharon

**Comment by khrunde** [comment]
Just checking in to see if that did the trick- looks like I did finally commit my css changes to the right branch. I also did it via the GUI interface here in Github, not the terminal. I pasted the commands I did in the terminal below so maybe you can help me see what I missed? My commits didn't show up on my Github after doing those commands in the Terminal. I'll do that over in the google group, too. Thanks again for your help!


♥ cd ..
rundemc04: skillcrush-104
♥ git checkout khrunde-new-branch
Already on 'khrunde-new-branch'
rundemc04: skillcrush-104
♥ open .
rundemc04: skillcrush-104
♥ git branch -a
* khrunde-new-branch
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/khrunde-new-branch
  remotes/origin/master
  remotes/upstream/master
rundemc04: skillcrush-104
♥ git add css/katie-runde-style.css
rundemc04: skillcrush-104
♥ git commit -m"added new css to khrunde-new-branch instead of master"
On branch khrunde-new-branch
Untracked files:
	advice/khrunde-advice.html

nothing added to commit but untracked files present
rundemc04: skillcrush-104
♥ git push origin khrunde-new-branch
Counting objects: 36, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (36/36), done.
Writing objects: 100% (36/36), 4.45 KiB | 0 bytes/s, done.
Total 36 (delta 23), reused 0 (delta 0)
remote: Resolving deltas: 100% (23/23), completed with 8 local objects.
To git@github.com:khrunde/skillcrush-104.git
   fe3c297..2a92400  khrunde-new-branch -> khrunde-new-branch
rundemc04: skillcrush-104
♥

**Comment by redrambles** [comment]
Hello there!

You are very close! The only thing left to do is to delete the extra 'katie-runde-style.css' that is in the [root of the project.](https://cloudup.com/c0cEaLOveXH) You already have a this file inside the /css directory, where it should be - so we just need to delete that extra one in the root of the project. Once that is done, you'll want to run:

```git add -A```

followed by 

```git commit -m "your message here"```

and then push your topic branch back up once more, which will update this pull request. At that point we should be good to go!

Let us know if you have more questions!

**Comment by khrunde** [comment]
Ok, deleted the extra css file from the root of the project and then ran that code...
hoping that did the trick? Let me know how that looks and thanks again!

**Comment by acodeinprogress** [comment]
Hey @khrunde,

It looks like you made those changes and pushed them to your master branch again. You'll need to make them on this branch in order for them to show up here. :)

xoxo,
Sharon

**Comment by khrunde** [comment]
Ok, from what I can tell:
-I made changes in the katie-runde-new-branch
-I deleted (on the second try) that stray css file from the root of the project- duh, didn't even see that there before
-pushed the correct css file in the correct folder again while still on the correct branch

I will be so excited if this finally did the trick- I really am getting this, as hard as that may seem to believe!
Thanks again!

**Comment by redrambles** [comment]
Hey @khrunde !

Good work, your code is all merged in!! Congrats!

**Pull request merged**
