### PR TITLE
adding my advice

### PR DESCRIPTION
**Pull request by sn31**
Just some mental notes for everyone and myself.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @sn31,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by sn31** [comment]
Hi Sharon,

I included a link to my advice in the index.html file, added, committed and pushed it. I am not sure if it works. Could you verify?

Thank you!

**Comment by redrambles** [comment]
Hey @sn31 ! 

We aren't seeing any changes to your pull request. If you run `git status` do you see any changes that still need to be added and committed? If not - can you try pushing again to `git push origin my-advice`? 

Let us know how it goes!
Cheers,
Ann

**Comment by sn31** [comment]
Hi there,

I did git push origin master the first time and that's why you didn't see it. Let me know if you see the 2nd commit now.

Thanks!
Skye

**Comment by redrambles** [comment]
Hey @sn31,
Yes - this is great! Your code is all merged in! :)

Cheers,
Ann

**Pull request merged**
