### PR TITLE
styled text and background

### PR DESCRIPTION
**Pull request by msgallup**
What do you think about my advice?

### CODE REVIEW

**Comment by redrambles** [comment]
Hi @msgallup!

I see a CSS file here, but no advice page nor a link to it from the main index.html file. Is it possible that you have created these but forgot to commit them, or push them up?

Once you add your advice page and the main index.html page with your modification (the link to your advice page) - commit these changes and push up your branch once more, which will automatically update your pull request.

Once this is done, we should be good to merge in your code!

Let us know if you have any questions!

**Comment by msgallup** [comment]
I was not quite sure how to link them with multiple people using the same css.  I just linked it they way it was and it seemed to link them on my computer.   “<link rel="stylesheet" type="text/css" href="css/style.css”>”.    Is that part correct?

Thank you

Marlene

**Comment by redrambles** [comment]
Hello @msgallup !

Yes - linking to the stylesheet in the manner you describe is perfect! While in your experiments branch, what do you see when you run 'git status'?

**Comment by msgallup** [comment]
I am not sure what to do next?

**Comment by msgallup** [comment]
Hi Ann.  I think I have everything fixed now, but now it says I have a conflict.  I know what to do to solve a conflict, but I am afraid to do anything with it.  Can you take a look at it?

Thanks
Marlene

**Comment by redrambles** [comment]
Hi @msgallup !

Ok great! Before we can look at resolving the conflicts, we need to make one more change in your experiments branch. Right now, your advice page is in the root of the project, but we want it to be in the advice/ directory. Please move the file inside the advice directory, then add the change with `git add -A`, then commit `git commit -m "your message here"`, then push up your branch `git push origin experiments`.

Once that is done, you will need to hop into your master branch `git checkout master` and bring it up to date with the main code base, by fetching from upstream `git fetch upstream` and then merging it into your master branch `git merge upstream/master`. 

Then you pop back into your experiments branch `git checkout experiments` and merge in your freshly updated master branch `git merge master`. This is when you will see conflicts, both in css/style.css and index.html. Your terminal will point out these files to you as containing conflicts, which you will need to resolve. Open each of these files in your text editor and resolve the conflicts. Make sure you don't erase anyone else's code, and that you get rid of the conflict markers, such as `>>>>>>>>HEAD`. Save each of these files, and then add them once more - either individually or in one fell swoop with `git add -A` - and commit `git commit -m "bring up to date with master"` (or message of your choice).

Last step: Push your branch back up once more `git push origin experiments` and your code should be conflict-free and ready to be merged!

Let us know if you have any questions! :)

Ann

**Comment by msgallup** [comment]
Thank you so much for all of the help.  I never could have done this myself. I don’t know how I messed it up so bad to begin with.  Anyway, I am now to the point where I should see conflicts in my terminal, but there aren’t any. I just want to double check and make sure that it is okay for me to move to the next step where I commit again.  Attached is a pic of my terminal and what I have done.

Thank you so much

Marlene

**Pull request merged**
