### PR TITLE
Kimberlybe advice

### PR DESCRIPTION
**Pull request by Kimberly-BE**
Hello, I shared some advice via kimberlybe-advice.html. I also added a different color for the link at the top of the page (see normalize stylesheet) which links to the index.html. 

Thanks,
Kimberly B.E.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Kimberly-BE!

I love your advice page! This is great, but we need a few more things before we can merge in your code. You have a 'css/kimberlybe-advice-normalize.css' stylesheet that you link to from your advice page which is included in this pull request, but there is also a 'css/kimberlybe-advice.css' page that is referenced in your advice page that you have not included here. We also need a link to your advice page from the main index.html document - so that folks can find and enjoy your words of wisdom!

Here's what we would like you to do:

1) While still in your 'kimberlybe-advice' branch, add your 'kimberlybe-advice.css' page inside the css/ directory.

2) Add a link to your 'advice/kimberlybe-advice.html' page in the main index.html page.

Once you have done that, add your changes and commit them, and then push up your kimberlybe-advice branch once more. This will automatically update your pull request and we should then be good to merge in your code. :)

Let us know if you have any questions!!

**Comment by Kimberly-BE** [comment]
Hi Ann,

Thank you kindly for the compliment re: my advice page, I truly appreciate it. Per your request,  I added the link for my html advice to the main index.html. Moreover, my advice.css document was in the css folder; but there was also a 2nd copy outside of the folder so I took care of that.

I also added & committed the aforementioned files. However, when trying to push to GitHub, I ran into an error (screenshot attached). Can you please help me understand what I should do?

Thanks in advance for your help!

Kind Regards,
Kimberly B.E.

Sent from Mail for Windows 10
"Happiness is the ability to fulfill worthy goals; the ability to love & have compassion; the ability to find the creative source within you, which is your spirit." - Deepak Chopra

**Comment by Kimberly-BE** [comment]
Hey Ann,
No sooner than sending my previous email did it hit me, I needed to look deeper into my pdf cheatsheet… and realized I needed to push to my branch, not the origin master.

Thanks anyway!!

Kimberly B.E.

Sent from Mail for Windows 10
"Happiness is the ability to fulfill worthy goals; the ability to love & have compassion; the ability to find the creative source within you, which is your spirit." - Deepak Chopra

**Comment by redrambles** [comment]
Hello @Kimberly-BE!

Thank you for making those changes - you are correct, you are going to want to push up your kimberlybe-advice branch.

[Here you can see the files that have changed](https://github.com/skillcrush/skillcrush-104/pull/1642/files). You have your stylesheet included twice - one in the css/ directory - which is perfect - and another time in the root of the project, which we will need to remove. If you want to add your normalize stylesheet into the /css directory, that's fine too. 

So! We're nearly there!

1) Delete the kimberlybe-advice.css stylesheet that is in the root of the project
2) Optionally add your 'kimberlybe-advice-normalize.css' inside the /css directory

Once you have made those changes (still in your kimberlybe-advice branch) - add with 

`git add -A` - then commit `git commit -m "your message here"` and then finally push up your branch with `git push origin kimberlybe-advice` - and we should be good to go!

We're very close!!! Let us know if you have any questions. :)

**Comment by Kimberly-BE** [comment]
Hello Ann,

I followed everything below. I hope this worked this time 😊!

Please let me know if I need to do anything else, in order to complete this challenge.

Kind Regards,
Kimberly B.E.

Sent from Mail for Windows 10
"Happiness is the ability to fulfill worthy goals; the ability to love & have compassion; the ability to find the creative source within you, which is your spirit." - Deepak Chopra

**Comment by redrambles** [comment]
Yay!!



Great work - everything is merged in now. Congrats!

**Comment by Kimberly-BE** [comment]
YAAAAAAYYYYYY! I’m so excited! Thank you again for your help Ann!!!!!

Sent from Mail for Windows 10
"Happiness is the ability to fulfill worthy goals; the ability to love & have compassion; the ability to find the creative source within you, which is your spirit." - Deepak Chopra

**Pull request merged**
