### PR TITLE
My first fork

### PR DESCRIPTION
**Pull request by adamr714**
This is my first fork attempt...so far so good I think.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @adamr714,

Looks great! I only have 1 tiny request for you. We would like for your ruby file to be in the ruby folder. If you could move it over there, then run git add -A, commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by adamr714** [comment]
Thanks Sharon, and thank you for checking my work.  I will attempt to do that on my lunch break.  I will definitely let you know if (when) I need help. 

Happy Friday!!!

Best,
Adam

**Comment by adamr714** [comment]
Hi Sharon,

I'm doing something wrong...i've committed and pushed but it won't let me
make a pull request.... :-(  where did i go wrong please?

Thanks for your help.

Adam

**Comment by acodeinprogress** [comment]
Hey @adamr714,

You did it correctly! and now your code is all merged in.

**Pull request merged**
