### PR TITLE
My first fork clone and push project

### PR DESCRIPTION
**Pull request by tomilynn814**
Some advice I would like to share with you. I hope you enjoy it!

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @tomilynn814 ! You opened up your pull request from your 'tomilynns-advice.html' branch - but you want to open it up using your 'advice' branch that we worked on together yesterday. :) It's the same process, just choose the 'advice' branch instead when you open up another pull request. Then we'll close this one, ok?

Let me know how it goes!

**Comment by acodeinprogress** [comment]
Hey @tomilynn814,

This looks great! I just have a couple small requests before I merge this in.

1. We would like for you to include a link to your advice page in the index.html file.
2. It would also be great if you could add some CSS for your page, either in the main.css file or by adding your own personal stylesheet.

Once you fix that up, all you have to do is add, commit, and push your changes and they will join your pull request here.  Then we can get it all merged in.

If no changes are made in 10 days, this pull request will close.

xoxo,
Sharon

**Comment by tomilynn814** [comment]
Sharon I went in and did a pull request I believe the way it is suppose to
be would you mind checking it? Now I will work on the css and after it is
done add and commit it..
Thanks so much

**Comment by tomilynn814** [comment]
When trying to link my html with css its not recognizing

 <!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="../css/style.css"><link href="
https://fonts.googleapis.com/css?family=Dancing+Script|Roboto+Condensed"
rel="stylesheet">


<title>Tomilynn's Advice</title>
</head>


<body class="tomilynns advice">
<header>
<a href="../advice/tomilynns-advice.html">Back to Main Page</a>
<h1>Want to learn to Code?Here's some advice</h1>
</header>

<section>
<div class="advice">

**Comment by tomilynn814** [comment]
I have finished these steps and looks like it went through. I did a git
remote upstream because that was the message I got when trying to commit my
changes to my branch "advice" then merged it. Not sure if it is correct but
i does look like on my end it went through. It says I have nothing left to
commit, I will wait until you look at it to make sure its all good before
the next step, Thank you for your patience with me.

**Pull request merged**
