### PR TITLE
added advice and styled

### PR DESCRIPTION
**Pull request by Andygirl**
Some advice I would have loved to have when starting to learn to code!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Andygirl,

Looks great! I only have 1 tiny request for you. We would like for your advice file to be in the advice folder. If you could move it over there, then run a slightly different git command (git add -A), commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by Andygirl** [comment]
Hi Sharon,

I received an error when trying to push my files:

? git push origin Andygirl/skillcrush-104

error: src refspec Andygirl/skillcrush-104 does not match any.

error: failed to push some refs to 'git@github.com:Andygirl/skillcrush-104.git'


And, I'm not seeing any changes in my GitHub, so I'm not sure if it worked or not?  Please let me know what I did wrong, or if I did it right somehow?


Thank you,


Andy


________________________________

**Comment by acodeinprogress** [comment]
Hey @Andygirl,

You only need to push to the name that you gave your repo. For example, it is probably origin. So all you need to do is **git push origin**.

**Comment by Andygirl** [comment]
Hi Sharon,


I did the below steps, just wanted to check and make sure everything worked out alright.


Take care,

Andygirl


________________________________

**Comment by acodeinprogress** [comment]
Hey @Andygirl,

So sorry for the delay! You did a great job and your code is all merged in! Yay!

xoxo,
Sharon

**Pull request merged**
