### PR TITLE
Nay advice compared with master

### PR DESCRIPTION
**Pull request by nayonnapurnell**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @nayonnapurnell,

It looks like your advice page is linking to the style.css file. It would be great if you could add some styles there. Once you do that, you can add, commit, and push and your changes will join your pull request here.

Let me know if you need any help!

**Comment by nayonnapurnell** [comment]
Thank you Sharon for the feedback.  Just to make sure I am clear on what you are saying below.

My advice page should not be linked to another page.

Also I need to redesign the advice page with my own styles.

Then add and commit it to the github account in the terminal.

**Comment by acodeinprogress** [comment]
Hey @nayonnapurnell,

That's close!
We actually do want you to link to the stylesheet. The issue that I mentioned was that you didn't add any styles to the stylesheet that you linked to. It's best to do this in the stylesheet rather than add them in your advice page.

**Comment by acodeinprogress** [comment]
Hey @nayonnapurnell,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by nayonnapurnell** [comment]
Hello Sharon:

I went back to work on some of the other missing assignments.  I forgot all about submitting the pull-request.  I noticed that people added to the css file.  I am a little confused at the assignment.

I am under the impression that I am supposed to create a CSS file.  I now understand my previous mistake by not creating a style.css file to link to my advice.html file.  I get it.

However, what is the name of the css file I am pulling from?  I have the sample file but I am unsure which .css file to pull from.


Nayonna

**Comment by acodeinprogress** [comment]
Hey @nayonnapurnell,

You have a couple different options here.
1) We already have a style.css file so you can simply add your styles at the bottom of that.
2) You can create a custom css file and then change the link in your advice page to your custom css page rather than style.css.

**Comment by acodeinprogress** [comment]
Hey @nayonnapurnell,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 10 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @nayonnapurnell,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

**Pull request closed without merging**
