### PR TITLE
cdevespa advice

### PR DESCRIPTION
**Pull request by cdevespa**
some advice I would love to share

carlos de villasante

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @cdevespa,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by cdevespa** [comment]
Hi Sharon I made the changes and add, commit, and push but do i need to
submit a new pull request?
xxo
Carlos

**Comment by acodeinprogress** [comment]
Hey @cdevespa,

When you push your changes, they'll automatically be added to this pull request. Unfortunately, I'm not seeing any changes so one or more of those steps might not have worked correctly. Are you sure that you made changes to your master branch and then pushed them to your master branch?

xoxo,
Sharon

**Comment by cdevespa** [comment]
Oh right I only made changes to my experiments branch. I forgot to merge with my master branch. 
I will try again thx
Xo carlos

**Comment by cdevespa** [comment]
I have gotten slightly lost but I think I comitted and merged.....

**Comment by acodeinprogress** [comment]
Hey @cdevespa,

Thanks for fixing that up! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
