### PR TITLE
commented out header font

### PR DESCRIPTION
**Pull request by alisande07**

### CODE REVIEW

**Comment by alisande07** [comment]
practice on submitting a pull request.

**Comment by acodeinprogress** [comment]
Hey @alisande07,

Looks great! We'd love it if you would also add some css in the style.css file (or make your own stylesheet - but remember to change your link to it ini your advice page). It would also be great if you could add a link to your advice page in index.html so others can see your awesome work!

Once you do that, you can add, commit, then push and your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @alisande07,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @alisande07,

It looks like you deleted the link to Malene's advice page. You can see it highlighted in pink under the Files changed tab.

**Pull request closed without merging**
