### PR TITLE
Added Ashley B's advice

### PR DESCRIPTION
**Pull request by aepriebebrown**
Please review. Thanks!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @aepriebebrown,

Good work! One little thing that I noticed is that you're linking to the style.css file but instead, you put your css in a custom stylesheet. If you could link to the right file, then add, commit, and push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by aepriebebrown** [comment]
Hi! My css is in the style.css file. It starts at line 2859. Do I need to move it to its own stylesheet?

**Comment by acodeinprogress** [comment]
Hey @aepriebebrown,

That is fine! Sorry, I must've had a brain fart when reviewing your submission. One other thing is that it looks like there's a merge conflict happening. Do you remember how to resolve this?

**Comment by acodeinprogress** [comment]
Hey @aepriebebrown,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by aepriebebrown** [comment]
Hi @acodeinprogress, I tried to fix the merge conflict, but failed. This is my first merge conflict aside from the practice one in 105. There have been quite a lot of changes made between when I added my code and now, and I'm not sure what to do. Could you please point me in the right direction? Thanks!

**Comment by acodeinprogress** [comment]
Hey @aepriebebrown,

You'll need to pull skillcrush's master branch into your branch. Then check out this guide for resolving conflicts: https://githowto.com/resolving_conflicts

**Comment by aepriebebrown** [comment]
Hi @acodeinprogress, thanks for the resource! I will comment again after I get this resolved. Don't give up on me yet :)

**Comment by aepriebebrown** [comment]
Hi again @acodeinprogress, on my end, everything says it is up to date. What do I need to do now?

**Comment by acodeinprogress** [comment]
Hey @aepriebebrown,

You'll need to get the latest changes from skillcrush's repo. Once you do that, you should encounter the merge conflict. :)

**Comment by aepriebebrown** [comment]
Thanks, @acodeinprogress. I have used "git fetch upstream" to do this. Is that right?

**Comment by acodeinprogress** [comment]
Yep! :)

**Comment by aepriebebrown** [comment]
@acodeinprogress, okay, thanks. I have done that, checked out my master, merged upstream, checked out my branch, and merged it with the master. I ran git status on my branch; it said, "nothing to commit, working directory clean". I also ran git status on my master branch, and it said, "Your branch is ahead of 'origin/master' by 5 commits. (use 'git push' to publish your local commits)", so I used git push origin to resolve that. Running git status now returns the message, "nothing to commit, working directory clean" on both my branch and the master, which is what I expected to see. I resolved the merge conflict several days ago, but I think where I have been running into trouble is with the "branch ahead of origin/master" message. I believe that is fixed now. Am I missing something?

**Comment by acodeinprogress** [comment]
Great work, @aepriebebrown! Your code is all merged in.

**Pull request merged**
