### PR TITLE
added Kessiah's Pep Talk for New Tech Wizards

### PR DESCRIPTION
**Pull request by Kessiah27**
Added a little advice for my fellow aspiring tech wizards!

### CODE REVIEW

**Comment by redrambles** [comment]
Hello @Kessiah27 ! 

This is great - but we need you to do two more things in order to be able to merge in your code.

1) I see that you are linking to '/css/style-kessiah.css' in your advice page - we will need you to include that css file please.

2) We also need you to add a link to the bottom of the list on the main index.html page so that folks can find your advice! :)

When you have done this, please add (git add . ) and commit (git commit -m "your message here")  your changes, and then push your branch back up. This will automatically update your pull request and we should be able to merge your code into the main code base.

Let us know if you have any questions! :)

**Comment by Kessiah27** [comment]
Hey Ann,

Thanks so much for this feedback! Oh my goodness I knew I had a lot to learn … okay, I’ve been trying to make little changes in the little windows of time between work appointments today but I think that’s causing some trouble with newer updates (hello, merge conflicts!), so I’m going to take some time to review and re-do either tonight or tomorrow when I have more than 10 minutes here and there to dig in. Hopefully I haven't destroyed the master branch yet!

More from me soon and thanks again for the guidance,
Kessiah

**Comment by redrambles** [comment]
Hello @Kessiah27!

Actually - this is looking great! The only thing is that there is a merge conflict in the index.html file, as other code has been merged in the meantime and that the line that where you add the link to your advice page is now occupied by someone else. No worries! I can either quickly resolve that for you, or you can try your hand at it yourself!

Let me know what you'd like to do. :)

**Comment by redrambles** [comment]
You did great!!

Congrats, @Kessiah27 - your code is merged in!

**Comment by Kessiah27** [comment]
Hooray!!! Thanks so much for the nudges along the way!

**Pull request merged**
