### PR TITLE
Sarah's advice added

### PR DESCRIPTION
**Pull request by sjbenenate**
Added some formatted advice!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @sjbenenate,

This looks great so far! I just have one teensy request before I can merge this in.
It looks like you deleted the advice-template.html file. We still need that file in the project so that other students can use it when they add their advice.

If you could add that back in, that would be great! Then you can add, commit, and push your changes to GitHub and they'll join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by sjbenenate** [comment]
Hi Sharon,

Whew! That was some of the best git practice yet!

How are things looking now?

Thank you :)
Sarah

**Comment by sjbenenate** [comment]
Just curious here...
I changed the branch I used for working and pushed to the remote but the pull request would not let me automatically merge until I pushed the master branch as well to the remote (the forked remote).
Why is this so, when only the experimental working branch is being mention in this pull request?

**Comment by redrambles** [comment]
Hello @sjbenenate !

This is looking nearly perfect - we just have a few conflict markers that remain in the index.html file - notably on lines 896, 899 and 906 - so we are going to need you to remove those, and then add the file, make a commit and push up your branch once more.

At that point, we should be able to merge in your code! Yay!!! :)

P.S - I am not sure that I am fully understanding your last question - if something similar happens again, please take a screenshot of the commands in your terminal so that we can have the necessary context to work out what occurred - and we will be happy to help clarify!

**Comment by sjbenenate** [comment]
Ok, done!
How do things look now?
Thanks :)

I must have missed that conflict as it was further down the page.

**Comment by acodeinprogress** [comment]
Hey @sjbenenate,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Sharon

**Pull request merged**
