### PR TITLE
Experiments2

### PR DESCRIPTION
**Pull request by benedettoadrianne**

### CODE REVIEW

**Comment by benedettoadrianne** [comment]
Added Adrianne's advice & styled the page.

**Comment by acodeinprogress** [comment]
Hey @benedettoadrianne,

It looks like you added 2 different advice files and 2 different css files. You only need to add 1 of each. If you could delete the extra files, then run a slightly different git command (git add -A), commit, and push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by benedettoadrianne** [comment]
Hi Sharon,
I wasn't sure what to do because I took 105 in April during the front end
blueprint, I already had files in there from then. So I just redid each
lessons, which may be why I had a few push/ pull problems. Should I remove
the files from the last time I took the class?
Thank you
Adrianne Scalera

**Comment by acodeinprogress** [comment]
Hey @benedettoadrianne,

That sounds like a good plan to me! 

xoxo,
Sharon

**Comment by benedettoadrianne** [comment]
Hi again,
We were on vacation and so I wasn't able to get to my computer until
now...I'm looking at my repositories now and am confused. I put each class
advice & css file in different branches ( in the 1st class I called it
"experiments" & 2nd  "experiments2") so do you need me to delete the files
or the whole branch? I just want to clarify before deleting!!
Thank you!
Adrianne

**Comment by acodeinprogress** [comment]
Hey @benedettoadrianne,

I hope you had a good vacation! Right now, it looks like all of your files are on the experiments2 branch since that's the one you're trying to merge in. So all you need to do is delete whichever files you don't want from that branch and make sure to push to the same branch on your repo. :)

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @benedettoadrianne,

It looks like you deleted a file and changed another file that already existed in the skillcrush-104 repo and there was a merge conflict that wasn't resolved but was saved to your code. Take a look at the Files Changed tab to see what's happening.

xoxo,
Sharon

**Comment by benedettoadrianne** [comment]
I think it's all set. If not I feel like deleting it all and starting again!!
Thanks
Adrianne

**Comment by acodeinprogress** [comment]
Hey @benedettoadrianne,

You're welcome to delete it and start over again. That might be the best choice at this point.

xoxo,
Sharon

**Pull request closed without merging**
