### PR TITLE
retrying commit

### PR DESCRIPTION
**Pull request by empecot**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @empecot,

Looks good! The only thing is that there seems to be a merge conflict. Do you remember how to resolve this?

Let me know if you need any help!

**Comment by empecot** [comment]
Hi Sharon,

Yes, I noticed the merge conflict and wasn’t sure how to resolve it. Although I’ve used github before, I’m SLOWLY getting the hang of this branches and forking and merging stuff. 
Could you provide me with some guidance on how to resolve the merge conflict. 

Thanks!
emily


EMILY PECOT
IMAGINE | DESIGN | MAKE
www.emilypecot.com
empecot@yahoo.com
718-666-6583

**Comment by acodeinprogress** [comment]
Hey @empecot,

Check out this [tutorial](https://youtu.be/zz7NuSCH6II?t=3m37s), starting at 3:37
It shows you what a merge conflict looks like in the terminal as well as in your files.

Let me know if that's helpful!

**Comment by acodeinprogress** [comment]
Hey @empecot,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 19 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @empecot,

This is just a reminder that this pull request will close in 7 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @empecot,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

**Pull request closed without merging**
