### PR TITLE
adding whitney.rb

### PR DESCRIPTION
**Pull request by whitneyl206**
Pull request for 104 lesson 22, 23 and 24.

### CODE REVIEW

**Comment by sareg0** [comment]
Hi there @whitneyl206 I have a suggestion for you to implement before we merge this puppy.

Could you please rename your css file to something specific to you.

If everyone name their css files 'style.css', then your html documents might get quite confused as to which style file to use. I propose the following changes.

1) Update your 'style.css' file to be name 'whitneyl206.css', to make sure it is very unique to you. You can call it whatever you like, but that is just one suggestion
2) update your html file to reference 'whitneyl206.css', instead of style.css

After you have made those changes add, commit and push them all, and they will show up here as a part of your pull request. 

Let me know if you need any further advice.

**Comment by sareg0** [comment]
Hey @whitneyl206 sorry for the late reply.  

Okay, sorry I misinterpreted. Leave you CSS the way it is, that's perfect.

I just have some extra feedback;
1) put your ruby file in the 'ruby' folder of the repo
2) put your advice page into the 'advice' folder of the repo

If you fix up those two things I can then merge this
Thank you!

**Comment by whitneyl206** [comment]
Oh man, I really really wish that you would have told me sooner. I'm moving
this week, and I don't have time to go back to comb over the lessons to
figure out how to move files on the repo, re-merge or whatever and ask for
this thing to be approved again. What lesson specifically tells me how to
do what you are asking?

Thanks so much for your help.

**Comment by sareg0** [comment]
Hey Whitney,

It is the lessons on merging in Skillcrush. There is nothing specifically about this particular thing I am asking you to do, but all you have to be is on the branch you made your changes on, make the changes, add, commit and push again, and it will join the other commits here. 

How about I close the pull request, you make those changes, and simple create a new pull request. That may be a bit simpler.

Once I close, remember to pull all the new stuff from this repo, into your fork, to make sure you have the most up to date version. 

Let me know which option you would prefer to go with.

**Comment by whitneyl206** [comment]
Ok, I think I managed to do it? Maybe. Lol. I closed the request, moved the
files and opened a new request. I think. A bit confusing to me still, but
hopefully this works...

**Pull request closed without merging**
