### PR TITLE
new fork repo file

### PR DESCRIPTION
**Pull request by wizzbit**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @wizzbit,

Looks great! I only have 1 tiny request for you. We would like for your ruby file to be in the ruby folder. If you could move it over there, then run git add -A, commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @wizzbit,

Thanks for making that update. It also looks like there's a merge conflict happening. Do you remember how to fix this?

**Comment by acodeinprogress** [comment]
Hey @wizzbit,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by wizzbit** [comment]
I’m only just getting this message today. I don’t check into this account too often so missed this completely. Can you remind me how to fix a merge conflict?

Thanks,
Nathan

**Comment by wizzbit** [comment]
How do I locate this branch conflict?.

**Comment by acodeinprogress** [comment]
Hey @wizzbit,

You'll need to get the changes from skillcrush's repo before you'll see a merge conflict. Once you do, check out that article I sent and you should be good to go.

**Comment by wizzbit** [comment]
Hi, 

I’ve updated the file and commit -m & merged master to the repo. I can see the files changed but no commit with the message “merge conflict resolved” can you advise one what to do from here?. Thanks Nathan

**Comment by acodeinprogress** [comment]
Hey @wizzbit,

Did you get a message that there's a merge conflict? If so, you'll have to fix the conflict manually. You can find instructions on how to do so here: https://githowto.com/resolving_conflicts

**Comment by wizzbit** [comment]
Yes I got that message and fixed it, or at least I thought I did but I’m having trouble pushing the changes up. I had explained this in a previous message, I also followed your web link on conflicts but I think I’m missing something here. Any ideas what that might be?.

I’m getting…

♥ git status
On branch master
Your branch is ahead of 'origin/master' by 3 commits.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean

**Comment by acodeinprogress** [comment]
Hey @wizzbit,

That message is saying that you've made changes on your local repo but you haven't yet pushed them to your remote repo on GitHub. Once you've resolved your conflict, you can run **git add .** and **git commit** (if you haven't already). Then all you have to do is run **git push** and you should be good to go!

**Comment by wizzbit** [comment]
Yes that was what I thought but in the end I don’t have the right access permissions. Any ideas?…

See below:

♥ git push
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

ERROR: Permission to skillcrush/skillcrush-104.git denied to wizzbit.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
nathanbarclay1: skillcrush-104

**Comment by acodeinprogress** [comment]
Hey @wizzbit,

It looks like you're trying to push your files to skillcrush's repo, which you do not have access to. You'll need to push them to your personal repo.

**Comment by wizzbit** [comment]
Hey Sharon, 

Would I be pushing to the forked repo or ruby 104 class repo or something else i.e create a new one?

https://github.com/wizzbit?tab=repositories

Can you clarify how to complete this task and maybe indicate what git command I need to be using in the terminal?

Very much appreciated…

Thanks,
Nathan

**Comment by wizzbit** [comment]
Hey Sharon,

I think I may have solved the issue and managed to push the newly edited index.html file to the forked skillcrush-104 repo, (My personal repo you refereed to I think?). The repo appears to have a automated merge function in place to merge with the master file. 

Can you please check and confirm everything has been completed OK and let me know?

Thanks,
Nathan

**Comment by acodeinprogress** [comment]
Hey @wizzbit,

You're soooo close! It looks like you somehow removed some links from the index.html file. If you take a look at the Files Changed tab, the removed lines will be highlighted in red and have a minus sign at the beginning of the line.
If you could add those back in, then add, commit, and push, it should be good to merge!

**Comment by wizzbit** [comment]
Hey Sharon,

I’ve updated the index.html file and sent it back up for viewing. Can you let me know if that is complete and ready to be an accepted pull request?

Thanks,
Nathan

**Comment by acodeinprogress** [comment]
Hey @wizzbit,

Great job! Your code is all merged in. :)

**Comment by wizzbit** [comment]
Yay!

**Pull request merged**
