### PR TITLE
amended push request

### PR DESCRIPTION
**Pull request by korra69**
Hi,
Some code would be nice, so here's my amended pull request.
korra69

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @korra69,

This looks great! I have one minor change for you before I merge this in. We would like for your Ruby file to be in the Ruby folder. If you move the file then run git add -A (don't forget the -A), commit, then push, your changes will join your pull request here. Then I can get it all merged in!

Let me know if you need any help!

**Comment by korra69** [comment]
Hi, Sharon.
I moved my leslie-di-mitri.rb file to the ruby folder in the git bash but attempts to add using git add -A and git add leslie-di-mitri.rb return the error message: fatal not a git repository (or any of the parent directories): .git. The ls command in the bash shows the file listed with many others, did my mv command commit the file simultaneously? See a shot of the bash here: 
git file move screenshot

**Comment by acodeinprogress** [comment]
Hey @korra69,

From this screenshot, it looks like you tried moving the file using git. My guess is that putting git in front of your command made it think that your file was supposed to be a repo. Now that the file is moved, try going back into your main skillcrush-104 directory and running git add -A, then commit and push. Let me know if that works!

**Comment by korra69** [comment]
Hi, @acodeinprogress. 

As you can see in the screenshot below the git add -A command still returned the error message: fatal not a git repository or (any of the parent directories) .git. This happened when I entered the command from inside the skillcrush-104 directory. Could the problem be that my computer thinks my desktop file is a repository? 
git add a cmd screenshot

**Comment by korra69** [comment]
yet, my ruby file shows up in the ruby folder on this list (you can see it in the continuation screenshot below)
git add a cmd pg2

**Comment by acodeinprogress** [comment]
Hey @korra69,

Do you know if you removed a .git folder from that directory? I would try recloning your forked repo onto your computer, then you can simply move your changed files over to the newly cloned repo.

Let me know if you need any help!

**Comment by korra69** [comment]
Sharon,
I think the problem may be a matter of folder names.  In your first comment to me on gitbhub you wrote: "We would like for your Ruby file to be in the Ruby folder." I have a local ruby folder in my local skillcrush-104 folder and I also have a ruby challenges directory (renamed depeche-code) that i pushed up to github in a previous exercise. Did you intend for me to put my ruby file inside the ruby challenges repository I had created in a previous exercise and push from there?

**Comment by korra69** [comment]
Hello @acodeinprogress !
Please ignore my previous message about the folder names. I reviewed the last 4 lessons and finally everything clicked. After re-cloning the forked repository, the git add -A command worked. Please let me know if my code can now be added. Thanks-

**Comment by korra69** [comment]
Hi, @acodeinprogress,
I pushed the code back up to the forked repo. Hope this resolved everything.
korra69

**Comment by acodeinprogress** [comment]
Hey @korra69, great work figuring this one out! It looks perfect! Your code is all merged in now.

**Pull request merged**
