### PR TITLE
Joy added advice 

### PR DESCRIPTION
**Pull request by EmilyDayo**
A little movie-based advice I would love to share :)

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @EmilyDayo,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by EmilyDayo** [comment]
Hi Sharon,

Thank you for your note, I've added the HTML file and committed it to my Experiments fork but I'm not sure is there's another step I need to take.

**Comment by acodeinprogress** [comment]
Hey @EmilyDayo,

I'm not seeing any changes. Did you make sure to push your changes to GitHub?
When you say "another button to re-add another file", are you looking on GitHub? It's best to make your changes on your computer using your text editor and then pushing them to GitHub.

Happy git-ing,
Sharon

**Comment by EmilyDayo** [comment]
Hello again Sharon :)
Thanks for your note - I've pushed it out again (in the terminal) and this is a screenshot of what I did:
screen shot 2017-12-04 at 18 47 59

and what I can see in Github:

screen shot 2017-12-04 at 18 46 20

The HTML file is just on top of the CSS one. 
I hope you can see that too now.

xoxo
Joy

**Comment by EmilyDayo** [comment]
Hello Sharon,

I hope this note finds you well …

I’ve responded to this email within Github but haven’t had any feedback on if my HTML file is still not visible.

I’m just reaching out here in case there is still an issue so I can try and fix it before the 10 day lag rolls over and the merge request is closed.

I’ve done the steps again in GIT and it says this on my end:


I just want to make sureI don’t leave any loose ends before I head into Phase two.

Many thanks!

Joy

**Comment by EmilyDayo** [comment]
-- Please reply above this line --


Hello Joy!

Ann here. I hope you don't mind if I hop in for Sharon! :)

Here is where I can see what your experiments branch is adding to the
main codebase. [1] Do you see how there are only two files listed
there, your advice page (advice/joys-advice.html) and the main css
stylesheet (css/style.css) ? This is great, but we still need you to
pop into the main index.html file and add a link to your
advice/joys-advice.html page, so that folks can benefit from your
words of wisdom! :)

In the screenshot that you attached in the e-mail below, I can see
that you have pushed up your master branch, but this isn't what we
want to do. In projects where we work with multiple developers, using
the fork/pull-request workflow (which is the workflow that we are
teaching you) - you don't want to be using the master branch for
anything other than a means to keep any topic branches in sync with
the main code base (a topic branch would be your 'experiments' branch,
for example).

So! This is what I suggest you do.

First, make sure to checkout your experiments branch.

GIT CHECKOUT EXPERIMENTS

Then, pop into the main index.html file, and add a link to your
project towards the bottom of the list. Save that change, then add:

GIT ADD -A

and commit:

GIT COMMIT -M "ADD LINK TO ADVICE PAGE" (or message of your choosing!)

Great! Now, let's move back into the master branch:

GIT CHECKOUT MASTER

Using your upstream remote connection (you can double check that you
do indeed have this set up by running 'git remote -v') - let's fetch
the most recent commits from the main code base:

GIT FETCH UPSTREAM

Next, let's merge those into your master branch:

GIT MERGE UPSTREAM/MASTER

Excellent! Now let's pop back into the experiments branch one more
time:

GIT CHECKOUT EXPERIMENTS

and let's merge in our freshly updated master branch:

GIT MERGE MASTER

There may be a merge conflict here. IF there is, open up the related
files (git will tell you which files are affected by the conflict) -
fix the conflict, make sure to remove the conflict markers, save the
file(s) and then add (git add -A) and commit (git commit -m "bringing
up to date with main code base")

Once you are done with this, you can push up your branch:

GIT PUSH ORIGIN EXPERIMENTS

which will update your pull request, including the change to the main
index.html file, and we should be able to merge in your code!

Let us know if you have any questions about this. You can do it!!

Cheers,
Ann



Links:
------
[1] https://github.com/skillcrush/skillcrush-104/pull/1553/files

--
Ann Cascarano
Skillcrush

 DID WE MAKE IT EASY FOR YOU TO GET THE HELP OR INFORMATION YOU
NEEDED?

**Comment by EmilyDayo** [comment]
Hello Ann,

Thanks a million for jumping in  for Sharon and helping out - your instructions worked like a charm. I knew something was missing but I totally forgot to branch the trunk. 

All done now so the pull request looks like this now

 
I even noticed a typo which I fixed too and I resolved the merge conflict as well.

Thanks again for all your help.

You rock!!

xoxo,
Joy

**Comment by redrambles** [comment]
Hey @EmilyDayo,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Comment by EmilyDayo** [comment]
Whoop Whoop!

Thanks Ann :D

xoxo,
Joy

**Pull request merged**
