### PR TITLE
Skillcrush 104

### PR DESCRIPTION
**Pull request by obrummer**
Hello, made two changes because forgot to add <br> from the first one.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @obrummer !

This is great! The only thing we are missing is a little CSS that would apply to your advice page. You can carve out a little place in the main css/style.css stylesheet and put a few lines of CSS - add and commit your changes and then push up your skillcrush-104 branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code! :)

Cheers,
Ann

**Comment by obrummer** [comment]
Hello,
Changes done. Actually twice, I corrected the first one.
Best,
Olli

**Comment by redrambles** [comment]
Hello @obrummer !

Ok! If you take a look a [this page here](https://github.com/skillcrush/skillcrush-104/pull/2123/files) - you can see that I still don't have any CSS. Did you perhaps forget to push up your changes?

Let us know if you need some help!

Cheers,
Ann

**Comment by obrummer** [comment]
Hello,

Ok, thanks! I just forgot to push up changes.

Best,
Olli

**Comment by obrummer** [comment]
Hey,

I don't know what happened but now it's been double-checked. Hope it's ok!

Best,
Olli

**Comment by acodeinprogress** [comment]
Hey @obrummer,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
