### PR TITLE
change html & css files

### PR DESCRIPTION
**Pull request by Picokcu**
Advice submitted for beginners. Checkout if appropriate.
Thank you

Janet

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Picokcu,

Looks great! I do have 1 little request for you before I can merge this in.
It looks like you created your own folders inside the advice and css folders. We'd like for you to keep them directly inside the advice and css folders. If you could move those files and then delete your custom folders, that would be great! We'd also like it if you could include a link to your advice page in the index.html file.
Once you make those changes, you can run git add -A (don't forget the -A), commit, and push and your changes will join your pull request here.

Let me know if you need any help!

**Comment by Picokcu** [comment]
Hi Sharon

Not sure what I have done but it seems I do not have those files anymore.
See screenshot when I tried to open.

Can I still retrieve them?

Thank you

Janet

**Comment by acodeinprogress** [comment]
Hi @Picokcu,

I don't see a screenshot. :(

**Comment by Picokcu** [comment]
Sorry Sharon

Here is the screenshot. So i tried this again today and same thing. Is
there anyway you can fix on your end? Otherwise I think I would have to
redo everything, right? UGH!

Janet

**Comment by acodeinprogress** [comment]
Hey @Picokcu,

I'm still not seeing a screenshot. Would you mind sending an email to your blueprint-specific email about this issue and including the screenshot there?

**Comment by Picokcu** [comment]
OK doing that now.

Thank you

Janet

PS attaching one more time just in case it works

**Comment by acodeinprogress** [comment]
Hey @Picokcu,

Were you able to get this straightened out? If no changes are made, this pull request will close in 20 days.

**Comment by Picokcu** [comment]
Sorry Sharon I will look at this now. Forgot about it.

J

**Comment by Picokcu** [comment]
Sharon sorry I have looked at this and as I am not that familiar with
github I am not sure where to find my css there? I cannot seem to see where
I can get to the file I submitted?

Any help

Thank you

Janet

**Comment by acodeinprogress** [comment]
Hey @Picokcu,

If you look towards the top of this page, there will be a link that says Files Changed. You can find your file when you click on that page.

**Comment by Picokcu** [comment]
Hello Sharon

I know I am being a pain. But I found the files but now I did not take
notes and not sure what you want me to do with this again.

Sorry but I also moved and everything is everywhere. I can't even find the
notes from that lesson to see what we were doing so I could figure out what
to do with this css file now.

I know we were pushing a file but do not remember how it was to be set up.

Help! & Sorry!

Janet

**Comment by acodeinprogress** [comment]
Hey @Picokcu,

Not a pain at all. Remember that you'll want to be on your experiment branch.
You should already have your advice file in the main advice folder so all you need to do is add your css file to the main css folder. You can either redo the css by hand or copy it from the Files Changed tab. If you do the latter, you'll want to make sure that you remove all the plus signs at the start of every line.
Once you do that, you'll want to run a slightly different git command (git add -A), then commit and push and your changes will join your pull request here.

**Comment by Picokcu** [comment]
Sharon

I have done what you said so I guess it should be good to go.

Thank you for your help.

Janet

**Comment by acodeinprogress** [comment]
Awesome, @Picokcu! Thanks for making those changes! Your code is all merged in.

**Pull request merged**
