### PR TITLE
Adding my repo files

### PR DESCRIPTION
**Pull request by thejasonwilson**
Creating my first pull request.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @thejasonwilson,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by thejasonwilson** [comment]
I made my changes and pushed but see that there is a conflict error above. I did a git status in Terminal and it says: "On branch experiments
nothing to commit, working tree clean"

I'm guessing because I pushed the branch "experiments" and not actual the "master"? A little confused on that part. Is this something I should fix through Terminal or could I use the "Resolve Conflicts" button above and fix it in GitHub. Just want to complete this correctly. Thanks!

**Comment by redrambles** [comment]
Hey @thejasonwilson !

Everything is good here - it's just the index.html file has evolved since you last pushed up your branch, which means that merging in your branch as it is would create a conflict that we would need to resolve in that file. This is 100% normal and expected in a codebase that moves quickly and that many people contribute to.

You can either:
1) Let us fix the conflict ourselves open merging your code
or
2) Fix it yourself, by first checking out your master branch, fetching from upstream, merging the upstream/master branch into your local master branch, checking out your experiments branch and then merging your freshly updated master branch into it. This will trigger the conflict, which the terminal will alert you about and point you to the file that it needs your help with (index.html), which you can then open up in your text editor and fix. Once you have done that (make sure the keep everyone's code and to delete the conflict markers) - you can add (git add -A), commit (git commit -m "bringing up to date with master") - which will complete the merge -  and then push up your experiments branch once more.

Let us know what you would like to do! :)

**Comment by acodeinprogress** [comment]
Hey @thejasonwilson,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
