### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by KellyCuevas**
Thank you for checking my edits!

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @KellyCuevas !

This is great - but we have two extra image files which we need to ask you to remove (`img/my-photo.jpg`) and (`img/tech-screenshot.png`) - so basically the whole 'img/' directory. We cannot accept media files because our repository would get much too large. You can totally link to external images, though - that are hosted somewhere on the web! :)

Once you have deleted the 'img' directory, please add your changes with `git add -A` and then commit `git commit -m "your message here"` and finally push up your branch once more: `git push origin experiments`, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions, and keep up the great work!!

Cheers,
Ann

**Comment by KellyCuevas** [comment]
Thank you so much for all of your help, Ann!  I decided to figure out how to host my photo remotely, and I think I did it!

**Comment by acodeinprogress** [comment]
Hey @KellyCuevas,

Thanks for making those changes! It looks like in the process of resolving the merge conflict, some work from other students was removed. We want to preserve everyone's work so we'll need to make sure to add those back in. You can see what was deleted by looking at the [Files Changed](https://github.com/skillcrush/skillcrush-104/pull/2022/files) tab near the top of this page.

xoxo,
Sharon

**Comment by KellyCuevas** [comment]
Thank you, Sharon!


Is there anything I need to do on my end to fix the issue?


Thanks,

Kelly


________________________________

**Comment by acodeinprogress** [comment]
Hey @KellyCuevas!

Yes, you'll want to add back in what was deleted. The lines that were removed are highlighted in pink when you look at the Files Changed tab near the top of this page.

Once you add that content back in, you can add, commit, and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @KellyCuevas,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
