### PR TITLE
triciaisham.rb

### PR DESCRIPTION
**Pull request by TriciaAI**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @TriciaAI,

This is a great start. There are a couple things I'd like for you to change before we can merge this. First, we'd like for your Ruby file to be in the Ruby folder. Also, we'd like the code inside the file to resemble Ruby code, so if you could put a puts statement in front of "Hello" that would be great! Go ahead and make those changes then run git add -A, commit, then push. Your changes will join your pull request here.

Let me know if you need help!

**Comment by TriciaAI** [comment]
Did I do something wrong? Here are my screen shots (guess I could have left out some of the red):

**Comment by acodeinprogress** [comment]
Hey @TriciaAI,

It's totally fine! This happens all the time. It's no big deal. But if you could move your file into the Ruby folder on your computer and change the code slightly so that it's more Ruby-esque, that would be fantastic! In my last message, I gave instructions for how to save your changes so that it's changed in GitHub as well.

Let me know if you need any help! :)

**Comment by TriciaAI** [comment]
So I thought I did what you asked. I moved triciaisham.rb into the ruby folder and did puts “Hello” then saved. then did the steps as you indicated in the terminal. Was there something more?

**Comment by acodeinprogress** [comment]
Hey @TriciaAI, I'm not seeing the changes on GitHub. Did you run git push origin master?

**Comment by TriciaAI** [comment]
Yes, that's why i attached the screenshot. I thought I had done everything right. I just did everything again and double checked to make sure the changes saved when I made them earlier.
screen shot 2015-11-16 at 12 48 49 pm

**Comment by TriciaAI** [comment]
ugh, that last image was not what the screenshot was of (I hate that it only captures so many screenshots and then starts over in the list - I always grab the wrong one!). I’m going to try this again…..

**Comment by TriciaAI** [comment]
I’m moving on and trying to create the GitHub profile page as the instructions state. When I clone the repository it appears as a single file on my computer, so I’m a little confused. Is there something I could be doing wrong that it doesn’t create a file I can add an index.html to?

**Comment by TriciaAI** [comment]
I’m in the challenge to add a personal advice page to the repository in lesson 104. 

I had tried to follow the instructions to update my local repository of skillcrush-104 but i must have done something wrong along the way. I’m getting this (screenshot) and don’t understand what to do as it says I’m still in a merge. What is my next step and what did I do wrong? Thanks!

Tricia

**Comment by acodeinprogress** [comment]
Hey @TriciaAI, I hope you had a great Thanksgiving! I was just checking to see if you were able to get this working. Let me know! :)

**Comment by TriciaAI** [comment]
No, I wasn’t able to get the GitHub profile page working. I tried it a couple different times and finally found their instructions for making a profile page, but it wasn’t like the Skillcrush instructions. By then I was back working on the other problem we were trying to solve and I never got back to it.


Just for reference, this was my previous message:

I’m moving on and trying to create the GitHub profile page as the instructions state. When I clone the repository it appears as a single file on my computer, so I’m a little confused. Is there something I could be doing wrong that it doesn’t create a file I can add an index.html to?

Thank you for all of your extra help, Sharon!

Tricia

**Comment by acodeinprogress** [comment]
Hey @TriciaAI, 
No problem! I'm happy to help! Were you able to follow the instructions in the email I sent you?

**Comment by acodeinprogress** [comment]
Hey @TriciaAI,

This pull request will be closed in 9 days if no changes are made. I'd be happy to help you get things squared away either through GitHub or email! Or I can close this pull request and you can try again.

Keep me posted!

**Comment by TriciaAI** [comment]
I am thoroughly confused as to how to make this work. I keep getting funky messages still about the commit not being complete. I’m about to throw in the towel.

**Comment by acodeinprogress** [comment]
Go ahead and send me an email and we'll work through it together. :)

**Comment by TriciaAI** [comment]
trying this yet again! do i have it?

**Comment by acodeinprogress** [comment]
Hey @TriciaAI,

You made changes! It looks like you deleted your Ruby file. Now all you have to do is make a new file in the Ruby folder, then add, commit, and push. Your changes will join this pull request and then I can get it merged in! :)

**Comment by TriciaAI** [comment]
I thought I did that! Arg!!!! This is what I did:

Tricias-MacBook-Pro:skillcrush-104 triciaisham$ git add triciaisham.rb
Tricias-MacBook-Pro:skillcrush-104 triciaisham$ git commit -m "triciaisham.rb"
[master a87e2c9] triciaisham.rb
 1 file changed, 1 deletion(-)
 delete mode 100644 triciaisham.rb
Tricias-MacBook-Pro:skillcrush-104 triciaisham$ git push origin master
Counting objects: 2, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 219 bytes | 0 bytes/s, done.
Total 2 (delta 1), reused 0 (delta 0)
To git@github.com:TriciaAI/skillcrush-104.git
   9035a56..a87e2c9  master -> master
Tricias-MacBook-Pro:skillcrush-104 triciaisham$ 


but you say it isn’t there? did I do it wrong?

**Comment by TriciaAI** [comment]
just tried this again. maybe i wasn't actually in ruby in skillcrush-104?

**Comment by acodeinprogress** [comment]
Perfect!!! It's all merged in. Great work, @TriciaAI!

**Comment by TriciaAI** [comment]
Success??? Really???? I did it???? Pull me off the floor!!!

Thank you!!! Can you hold my hand like this all the time?!

:)

**Comment by TriciaAI** [comment]
so continuing on, how does the upstream work? I typed in the code as on the challenge, but I get: -bash: git@github.com:skillcrush/skillcrush-104.git: No such file or directory

**Pull request merged**
