### PR TITLE
hope this works

### PR DESCRIPTION
**Pull request by dmarino622**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @dmarino622,

This looks great so far! I just have a couple requests before we can merge this in:
1) I don't see any CSS. If you could add some in, either in the main style.css file or in a personal stylesheet, that would be great!
2) We would like for you to include a link to your advice page in the index.html file. 

If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by dmarino622** [comment]
Thanks for the feedback.  I went back and did everything again, let me know
if it worked.  Thanks!

**Comment by acodeinprogress** [comment]
Hey @dmarino622,

Thanks for making those changes!

If you take a close look at the code that you added in the `index.html` file, there are some typos. Can you spot them?
Also, when you added your CSS, it looks like you added everyone else's styles. Since this is a personal stylesheet and only your page links to it, you only need to have your styles in the file.

Once you make those changes, you can add, commit, and push again.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @dmarino622,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
