### PR TITLE
Leigh added advice

### PR DESCRIPTION
**Pull request by leighdamico**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @leighdamico!

This is looking good - we just need a link in the main index.html file that points to your advice page, so that folks can benefit from your words of wisdom! Once you've made that change, you can add (`git add -A`) and commit (`git commit -m "your message here"`) and then push up your branch once more, which will automatically update this pull request.

Let us know if you have any questions! :)

**Comment by leighdamico** [comment]
I think I did everything I needed to do.   Are the branch conflicts that are now showing up in this conversation a problem for me?  Or is that what you do when you merge pull requests?

**Comment by redrambles** [comment]
Hey @leighdamico !

This is great! I know what you mean about Git / GitHub - it can be a steep learning curve but the good news is that you don't need to know a whole lot of commands in order to benefit from version control nor to use it regularly! With more time and practice, I'm confident that you will see how useful Git is!

This is great - I now have  a link to your advice page on the index.html file - awesome! You have noticed that there are conflicts in both the css/style.css and the index.html file. I can either resolve these myself during the pull request - or - if you'd like to get more practice this this yourself, you can resolve the conflicts on your end! 

Normally you would have made your changes in a topic branch (a branch that you created and named 'advice', for example) - and then the workflow would be to checkout your master branch, bring it up to date with the main code base, check out your 'advice' branch and merge your updated master branch into it, resolving any merge conflicts that come up - add, commit and push up your branch.

Because you are working directly on the master branch, your process would be a little bit different. You would first need to make sure that you have a connection to the main code base (usually called 'upstream') by running `git remote -v` to confirm. If you do see an upstream remote connection, you would fetch `git fetch upstream` and then merge into your master branch `git merge upstream/master`. This will trigger the merge conflict which you would then need to resolve by opening up each file where conflicts are present, resolving them (make sure to keep your work and not erase any one else's!) - saving the files, adding them (`git add -A`) committing (`git commit -m "resolving merge conflicts"`) and then pushing back up (`git push origin master`) - which will automatically update your pull request here. 

At that point - we should be all good to merge in your code.

Let us know if you'd like to try your hand at fixing those conflicts yourself, or if you'd like us to do it on our end. :)

Keep up the great work!

**Comment by leighdamico** [comment]
Thank you!

I want to try to do it myself.  But not until tomorrow.  :)

**Comment by leighdamico** [comment]
Okay, now I'm stuck.  I verified that I was connected with the main code base.  (At least I think that's the upstream I'm connected to?)

****************************************************************************
Andrew@BSAP MINGW64 ~/Desktop/105-project/skillcrush-104 (master)
$ git remote -v
origin  git@github.com:leighdamico/skillcrush-104.git (fetch)
origin  git@github.com:leighdamico/skillcrush-104.git (push)
upstream        git@github.com:skillcrush/skillcrush-104.git (fetch)
upstream        git@github.com:skillcrush/skillcrush-104.git (push)
****************************************************************************


And then I merged but it didn't trigger the merge conflict.


*****************************************************************************
Andrew@BSAP MINGW64 ~/Desktop/105-project/skillcrush-104 (master)
$ git merge upstream/master
Already up to date.
*****************************************************************************

What do I do now?  Besides go back and rewatch the 105 lessons.  Which is what I'm going to do while I wait for further instructions.  Is this situation fixable or am I doomed because I violated the cardinal rule not to work on the master??

Thanks,
Leigh

**Comment by leighdamico** [comment]
Can I ask another question?

I'm the "Working with Others Via Github" lesson in 105 again.

In the "Working with Others on Github" document that I downloaded in Step 2, the workflow includes adding the original repository as an upstream repo right after I clone it.  But as I worked through the example in Steps 3-8, I don't set up an upstream remote until Step 7 - after I've edited my topic branch.

Does it matter which order I follow?

**Comment by redrambles** [comment]
Hello @leighdamico !

Ok! Your upstream remote connection is indeed linked to the correct repository - awesome! The reason why you didn't get any merge conflicts is because you didn't first fetch from the upstream remote repository.

You will want to run:

`git fetch upstream`

so that you can grab all recent commits and **then** merge:

`git merge upstream/master`

This is when you will see the conflicts and can proceed to resolving them.

Let us know how it goes!

P.S - About your second question - no - it doesn't matter when you add a connection to your upstream remote, so no worries there. :)

**Comment by leighdamico** [comment]
I think I did it!

I also now have a shiny new 3 page document summarizing everything I've learned and relearned in this segment.  Would it be okay if I repeated the assignment?  Can I make an additional advice page and try to follow every step this time?

**Comment by acodeinprogress** [comment]
Hey @leighdamico,

We can go ahead and close this pull request (or you can close it yourself) without merging it in and you can redo it if you'd like!!

Let us know!

xoxo,
Sharon

**Comment by leighdamico** [comment]
I just closed the pull request and am starting over.  Thanks for walking through this with me!

**Pull request closed without merging**
