### PR TITLE
Larissa's Advice Project

### PR DESCRIPTION
**Pull request by larisschwa**
Here we go...

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @larisschwa !

We got your advice file - which is great! But we also need you to add a little styling (either in the main stylesheet - css/style.css - or in a new stylesheet that you create, place in the /css directory and link to from your advice file) and we need a link in the main index.html file so that folks can benefit from your words of wisdom. 

Once you've made those changes, you'll want to add, commit and push up your 'advice-project' branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by larisschwa** [comment]
I did do all that! Not sure why it didn't come through 😭

**Comment by acodeinprogress** [comment]
Hey @larisschwa,

Is it possible that you haven't added, committed, or pushed your changes to GitHub? Another possibility may be that you created them on a different branch. In order for it to show up here, it would have to be done on your advice-project branch.

xoxo,
Sharon

**Comment by larisschwa** [comment]
Did I do it?!

**Comment by redrambles** [comment]
@larisschwa you did it!!! Congrats, your code is all merged in!

**Pull request merged**
