### PR TITLE
Kate tries this again

### PR DESCRIPTION
**Pull request by kkait**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @kkait,

It looks like you added a bunch of other people's advice, css, and ruby files. Would you mind removing those files and only adding your own?
It also looks like you edited more than just your own information in style.css and the main index file. All you need is to update your own info.
Lastly, it looks like there's a merge conflict. Do you remember how to resolve this?

**Comment by kkait** [comment]
I think I did it this time!

**Comment by kkait** [comment]
Damn it, really thought I had it.  I didn't edit anything in the style.css (I opened it but that's it). Index.html to resolve the merge conflict I removed double entries for 3: Tiffany, William, and Ashley? I think.

I just re-committed my branch where each of the three folders now only contains my file.  Did that do it?

Says the merge conflict is gone at least.  After 2 weeks.

**Comment by acodeinprogress** [comment]
Hey @kkait,

It looks like even more files were affected. If you take a look towards the top of your pull request, you'll see something like this:

screen shot 2016-05-19 at 1 55 46 pm

So right now, it looks like you've changed 697 files.

**Comment by kkait** [comment]
I'm calling it. I'll just delete all my stuff and refork the repo tomorrow.
Because this is getting out of hand.

Sorry.

**Pull request closed without merging**
