### PR TITLE
added teni's advice and updated html and css

### PR DESCRIPTION
**Pull request by TeniCola**
Added my page of advice through Skillcrush 105!

### CODE REVIEW

**Comment by TeniCola** [comment]
Realized that I didn't update the merge conflict that I had fixed while syncing master branches, should be good to go now!

**Comment by acodeinprogress** [comment]
Hey @TeniCola!

This is super close!

It looks like there's an extra </div> in your code. You can see it by clicking on the [Files Changed](https://github.com/skillcrush/skillcrush-104/pull/1768/files) tab near the top of this page.

Once you remove that, you can add, commit, and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by TeniCola** [comment]
Hi @acodeinprogress and @redrambles! Thank you for reviewing my code, I was actually about to ask what was "extra" in my code in case I was missing something, but that clarification makes sense. I guess it must be the </div> that was left over in the index file when I synced it with the upstream repo, so I'll go ahead and correct it as soon as I can!

**Comment by TeniCola** [comment]
Oh wow, now Github did the same thing to me-- I meant the `</div>` haha

**Comment by TeniCola** [comment]
Alright, I think I was able to make the correction to my experiment branch, hope this will be alright for the pull request!

**Comment by acodeinprogress** [comment]
Hey @TeniCola,

Great job and thank for making that change so quickly! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
