### PR TITLE
moved file to ruby folder, edited advice page

### PR DESCRIPTION
**Pull request by krstikiv**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @krstikiv,

It looks like you made a ton of changes in the index.html file. Would you mind undoing those changes and just adding a link to your advice page? Once you do that, you can add, commit, and push and your changes will join this pull request.

Let me know if you need any help!

**Comment by krstikiv** [comment]
Fixed the index file. Hopefully it's good now.

**Comment by acodeinprogress** [comment]
Hey @krstikiv,

You're veeeeery close! There are still some things off about the index.html file.
1)
<!DOCTYPE html>
 <html>
is missing

2) You have an extra line
>>>>>>> f4b47082625a377888b18c3f6e5928ebb00772e0

Once you fix those up and add, commit, and push, I can get your code merged in.

**Comment by acodeinprogress** [comment]
Hey @krstikiv,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @krstikiv,

This is just a reminder that this pull request will close in 10 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @krstikiv,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

**Pull request closed without merging**
