### PR TITLE
Added psittacine-advice html & css files, & link on index.

### PR DESCRIPTION
**Pull request by psittacine**
Added my psittacine-advice.html and psittacine-advice.css files, and the link to my page on index.html.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @psittacine,

It looks like there's a merge conflict happening. Do you remember how to resolve this?

**Comment by acodeinprogress** [comment]
Hey @psittacine,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by psittacine** [comment]
I re-read the lesson about resolving merge conflicts, but it's with a conflict we created and resolved locally.  So, I'm not sure how to proceed in this instance when trying to push up to the skillcrush repo.

**Comment by acodeinprogress** [comment]
Great work, @psittacine! Your code is all merged in.

**Comment by redrambles** [comment]
Yay!!! :) Great work indeed, @psittacine! Thanks for mergine, @acodeinprogress !

**Pull request merged**
