### PR TITLE
my first commit

### PR DESCRIPTION
**Pull request by MitaliShah**
first pull request :)

### CODE REVIEW

**Comment by redrambles** [comment]
Hello @MitaliShah !

This is great! We just have two little things we need you to address before we can merge in this code.

1) You have included a 'css/Mitali-style.css stylesheet' -which is great! We will need you to link to this stylesheet from your  'advice/advice-template-Mitali.html' page, so that these styles will apply to your advice page. Right now, your advice page is linking to the main stylesheet (css/style.css) which you aren't using.

2) We need you to include a link to your advice page at the bottom of the list on the main index.html page, so that folks can find your words of wisdom! :)

Once you have made these changes in your 'mybranch' branch,  remember to add and commit and then push up your branch once more, which will automatically update your pull request over here.

Once that is done, we should be good to merge in your code! Let us know if you have any questions, and keep up the good work!

**Comment by acodeinprogress** [comment]
Hey @MitaliShah,

Thanks for making that change! You're super close!

It looks like you added a class name with an apostrophe in it, which isn't allowed in CSS. If you take a click on the Files Changed tab towards the top of this page, you'll see that line 52 is highlighted in red. If you could fix that up, that would be great!

Happy git-ing!
-Sharon

**Comment by MitaliShah** [comment]
Hi Sharon,
Thanks for reviewing my work! Can you guide me fix this issue as I
don't see any error on GitHub page?

 xoxo
-Mitali

**Comment by acodeinprogress** [comment]
Hey @MitaliShah,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
