### PR TITLE
advice 

### PR DESCRIPTION
**Pull request by Adrienne-Leigh**
Not sure if I did this right :-/

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Adrienne-Leigh,

This looks great! I just have a couple requests before I merge this in.
1) We would like for you to include a link to your advice page in the index.html file. 
2) It'd be great if you could add a personal stylesheet with some CSS to style your page.

If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Adrienne-Leigh,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 10 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by Adrienne-Leigh** [comment]
Sorry about that, I've been on vacation! Thanks for the heads up. I'll be
on it soon :)

**Comment by acodeinprogress** [comment]
Hey @Adrienne-Leigh,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
