### PR TITLE
hello_world file added

### PR DESCRIPTION
**Pull request by CindyinWoodstock**
and a big Hello from Cindy!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @CindyinWoodstock,

Looks great! I only have 2 tiny requests for you. 
1) We would like for your ruby file to have an original name such as cindyinwoodstock or your first and last name.
2) We would like for your ruby file to be in the ruby folder. 

If you could make those changes, then run git add -A, commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @CindyinWoodstock,

We would like for your ruby file to be in the ruby folder. If you could move it over there, then run git add -A (don't forget the -A), commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @CindyinWoodstock,

It looks like you still have some extra files in the main directory (hello-world.rb and cindycown.rb). Also, we'd love for you to have a link to your advice page in the index.html file!

Once you make those changes, you can run **## git add -A** (run this exact command), commit, then push. You changes will join this pull request and I can get your code merged in!

Again, let me know if you need any help!

**Comment by CindyinWoodstock** [comment]
Hi Sharon
Do I need to commit deleted files?
Thanks!
Cindy

**Comment by acodeinprogress** [comment]
Hey @CindyinWoodstock, thanks for making those changes! It all looks great and your code is all merged in.

**Pull request merged**
