### PR TITLE
added advice, styled css, added link to index

### PR DESCRIPTION
**Pull request by andresraaron**
Some advice I would like to share.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @andresraaron,

This is super close! I just have a couple requests before I merge this in:
1. It looks like you changed the name of the style.css file to be your personal stylesheet. Instead, we want you to create your own personal stylesheet (and leave the style.css file) and add your own styles to it.
2. You seem to have deleted the advice template. Other students need this template to create their own advice pages so you'll need to restore that.

xoxo,
Sharon

**Comment by andresraaron** [comment]
For some reason I feel stuck.  I need more guidance with this one please.

Thanks,

Aaron

Thanks,

Aaron Andres

**Comment by redrambles** [comment]
Hi @andresraaron !

Ok no problem! Here's what I would suggest.

First - make sure that you are in your 'experiments-104' branch `git checkout experiments-104`

Next, grab your advice/aaronandres-advice.html file, and place it temporarily on the desktop. Grab your css/aaronandres-style file and place it temporarily on the desktop as well, and rename it to have a .css extension (aaronandres-style.css)

Next, we're going to do a little git magic and roll back in time.
`git reset --hard 030abc1`

Here we are rewinding our project back to the state it was at that particular commit - which was before you made your changes.

Next, place your aaronandres-advice.html that's waiting on your Desktop back inside the /advice directory - and your aaronandres-style.css file back in the /css directory. 

Open up your advice/aaronandres-advice.html file and make sure your custom stylesheet that you are linking to also has that .css extension.

Then you'll want to add a link to your advice page in the index.html page.

Once you're done - make sure to add your changes `git add -A`, commit `git commit -m "your message here"` and then push up your branch once more: `git push origin experiments-104` - and this will automatically update your pull request. We should then be good to merge in your code!

Hope this helps - let us know if you have any more questions!

Cheers,
Ann

**Comment by acodeinprogress** [comment]
Hey @andresraaron,

Unfortunately, it looks like those screenshots didn't come through. Would you mind emailing them to questions@skillcrush.com? We'd be happy to take a look and help get you back on the right track!

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @andresraaron !

This is great! There are just two little things that need a little tweak, and we'll be all set to merge this in.

1) Your css/aaronandres-style.css.css file has a double .css extension! :) We just need one '.css' there, so you'll need to rename it.

2) You have ALL the styles in your (freshly renamed) css/aaronandres-style.css file - but all we need are your styles in there, so you can remove everyone else's.

Once you are done making those changes, you can add with:

`git add -A`

and then commit:

`git commit -m "your message here"`

and then push up your branch once more: `git push origin experiments-104`

and we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann

**Comment by andresraaron** [comment]
Done!

Thanks!!!

Aaron

Thanks,

Aaron Andres

**Comment by acodeinprogress** [comment]
Hey @andresraaron,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
