### PR TITLE
Lydia made CSS changes

### PR DESCRIPTION
**Pull request by LydMedina**
I didn't add an advice.  Just made CSS changes.

### CODE REVIEW

**Comment by LydMedina** [comment]
Learning how to pull in github

**Comment by acodeinprogress** [comment]
Hey @LydMedina,

This looks great! I have a few requests before I can merge this in.
1) It looks like you changed someone else's styles in the main stylesheet (style.css) and their link in the index.html file. Instead, we want you to add your styles and link in addition to everyone else's so that we can preserve everyone's styles and links. 
2) You seem to have added a test folder and put your advice file in there. Instead, we would like for all the advice files to be directly in the advice folder. All you need to do is put your file in the advice folder and then delete the test folder.
Once you fix that up, you can run a slightly different git command (git add -A), commit, and push and your changes will join your pull request here.

Let me know if you need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @LydMedina,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 20 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by LydMedina** [comment]
Hi Sharon, 

Sorry I am getting back to you so late.  I made the requested changes.  Please let me know if I need to do anything else. 

Thank you, 
Lydia

**Comment by acodeinprogress** [comment]
Hey @LydMedina,

Thanks for making that change! It still looks like you altered some information in the style.css and index.html files. Instead of changing information, we'd like for you to add your own. If you could change that back, it would be great!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @LydMedina,

We still had all the changes fixed up yet. If no changes are made in 10 days, this pull request will be closed. 

Let us know if you still need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @LydMedina,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
