### PR TITLE
I created and styled my personal advice page

### PR DESCRIPTION
**Pull request by JJDWolfe**
I created an advice page and made the background color pop!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @JJDWolfe,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @JJDWolfe,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 10 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by JJDWolfe** [comment]
Hi Sharon! Somehow I missed the notification for the first message! I will get on this asap!

**Comment by JJDWolfe** [comment]
Hi Sharon, I've checked the code. There should already be a link to the index page in my advice. Is the link not accurate?

**Comment by acodeinprogress** [comment]
Hey @JJDWolfe,

Yep! You have that link in there. We'd also like you to include a link to your page in the index.html file so that others can see your advice page from the main page.

xoxo,
Sharon

**Comment by JJDWolfe** [comment]
Hi again! Ah, well, of course that's what you meant! I'll get that done. I apologize for the confusion!

**Comment by acodeinprogress** [comment]
Hey @JJDWolfe,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
