### PR TITLE
Added Advice/Meghana.html and meghana.css alongwith Bootstrap codes

### PR DESCRIPTION
**Pull request by meghanas0808**
- Created advice/advice-meghana.html

- created meghana.css

- added bootstrap css files to folder(not sure if I should have instead used the maxcdn link in the head)

- Made all related changes in index.html

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @meghanas0808,

I have one tiny request for you. Would you mind removing all of the extra bootstrap files? Once you do that, you can run git add -A (don't forget the -A), commit, and push. Your changes will join your pull request here.

Let me know if you need any help!

**Comment by meghanas0808** [comment]
Hi @acodeinprogress 
Below is the excerpt of the outcome:

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

I think I have done the right thing although I am not sure it worked! Could you please check and let me know?

**Comment by acodeinprogress** [comment]
Hey @meghanas0808,

Did you run **git add -A ** with the capital A then commit?

**Comment by meghanas0808** [comment]
hey @acodeinprogress , 
Yes I did, I double checked the comment and ensured I did!

**Comment by acodeinprogress** [comment]
Hey @meghanas0808,

That's great! Thanks for making that change! 
It also looks like there's a merge conflict happening. Do you remember how to resolve this?

**Comment by acodeinprogress** [comment]
Hey @meghanas0808,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by meghanas0808** [comment]
@acodeinprogress 
I tried checking for the conflict but when I do it on my git it says all files up to date! M not sure what is causing the conflict!! :(

**Comment by acodeinprogress** [comment]
Hey @meghanas0808,

Did you get the changes from skillcrush's repo? That should produce the merge conflict.

**Comment by meghanas0808** [comment]
@acodeinprogress I finally managed to rework on the steps in the assignment and it now throws a CSS /style.css conflict. I am not sure if its the same conflict for you as well, 
image

**Comment by meghanas0808** [comment]
This is my current status and i am hoping it is closer to where we want to get! 

image

**Comment by acodeinprogress** [comment]
Hey @meghanas0808,

Does your latest screenshot mean that you were able to fix the merge conflict?

**Comment by meghanas0808** [comment]
@acodeinprogress I guess so cos I dont see any conflicts or errors, it only mentions that the origin/master is 1452 commits ahead, I believe that would be all the other pull requests from other learners! How do I verify this?

**Comment by acodeinprogress** [comment]
Hey @meghanas0808,

Our wonderful @redrambles figured this one out for me. You're actually in your 105-project directory instead of your skillcrush-104 directory. That's why you're running into issues.

**Comment by meghanas0808** [comment]
Dang it!! :-(
Please give me this weekend, I shall resolve this.

**Comment by meghanas0808** [comment]
@acodeinprogress 
I was working on this today and it says everything is up to date incl. merge. Not sure if it actually worked - could someone please check!
image

**Comment by acodeinprogress** [comment]
Great work, @meghanas0808! Your code is all merged in.

**Pull request merged**
