### PR TITLE
added my advice, changed css syles

### PR DESCRIPTION
**Pull request by kstover12**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey there @kstover12!

This is looking great! We just need one more thing - that you include a link to your 'advice/kaleigh-advice-template.html' advice page from the main index.html page. (You can just add it at the bottom of that long list! :)) 

Once that is done - add and commit your change - and push your advice branch back up again (git push origin master) - and your pull request will be automatically updated!

Once that's done, we'll be able to merge in your code. Great work and let us know if you have any questions!

**Comment by kstover12** [comment]
Thank you, I think I have done that. Can you let me know?

Thanks,
Kaleigh

**Comment by redrambles** [comment]
Hello Kaleigh,

Ok! I'm not seeing a new commit yet. Do you remember if you have saved the change, added it (git add -A) and committed it (git commit -m "added my link to the main index.html file") and then push up your branch (git push origin advice) ?

**Comment by kstover12** [comment]
Yes, here is a screen shot of my terminal:

**Comment by redrambles** [comment]
Hello again! Screenshots are a bit tricky to share on GitHub - can you send it to us at 'frontend@skillcrush.com' please?

**Comment by acodeinprogress** [comment]
Hey @kstover12,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
