### PR TITLE
Advice from Melanie 

### PR DESCRIPTION
**Pull request by melanietrz**
I've added some advice!

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @melanietrz! 

I responded about your project in your Google group - let me know if you would like us to exchange about it here instead!

**Comment by melanietrz** [comment]
Hi Ann,

Thanks so much for checking in! I’ve been distracted working through a bit
of the next two classes to catch up a bit more and haven’t been able to
figure out exactly what I did during that CSS step in that git lesson. I
know there’s no such thing as falling behind here but it feels like it at
the moment! I hope to be able to figure the snag out in the next day or so
and be able to respond.

Thanks again!
Melanie

**Comment by acodeinprogress** [comment]
Hey @melanietrz,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 10 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by melanietrz** [comment]
Hi Sharon,

I’ve updated the css, commited and ran the ‘push origin’ command from my
branch.

What steps do I take from here.

Thanks so much!

Melanie

**Comment by acodeinprogress** [comment]
Hey @melanietrz,

You're super close! It looks like you saved some merge conflicts in your code. You'll need to remove those. For example, if you look at lines 8670 and 8671 in style.css, you'll see some merge conflicts. There is another line in that file and some lines in the index.html file.

You can see them a bit easier if you look at the Files Changed tab on this page.

Once you remove those conflicts, you'll follow the same process that you did before (add, commit, and push) and then we can merge your code in.

xoxo,
Sharon

**Comment by melanietrz** [comment]
Eeep, that’s no good! So I removed conflicts from the style.css, but I
didnt see any when I opened up index.html. I followed through the steps as
before.

Question - How would I know to look for these merge conflicts? I didn’t get
any sort of alert in the terminal or even edit those files files myself.

Thanks so much!

**Comment by acodeinprogress** [comment]
Hey @melanietrz,

Normally your computer will notify you that there is a merge conflict in your code and what files it's in. Then you'll go into the files and search for things that indicate a merge conflict, like HEAD or >>>. If you take a look at the Files Changed tab on this page and then scroll down to the index.html file, you'll be able to easily see the merge conflicts.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @melanietrz,

You're doing great! In addition to what @acodeinprogress said - you can take a look at [this link right here](https://github.com/skillcrush/skillcrush-104/pull/1479/files) and scroll down to the index.html file. On the right hand side, you will see your additions which also include the conflict markers. This will show you where they exist and should make it easy for you to locate and delete. Once that's done, you can add, commit and push - and we should be good to go!

Keep up the good work!

**Comment by melanietrz** [comment]
Hi ladies,

Thanks so much for all your help - but I’ve gotten myself really confused
here with resolving these conflicts. I had not made any changes to
index.html, and the other codes that is causing conflicts is styles for
other users - I unsure that I can delete this without affecting other’s
work.

I asked about what to look for with these as when I was making my changes
and commits I didn’t get any notification from my computer - which I
thought was unusal especially knowing that saving merge conflicts is a big
issue.

Thanks again, sorry I’ve made such a mess of this. I definitely be running
through all of 105 once I get this set & figured out.

Melanie

**Comment by acodeinprogress** [comment]
Hey @melanietrz,

Would you like us to close this pull request for now and you can give it another shot when you go through 105 again?

xoxo,
Sharon

**Comment by melanietrz** [comment]
Hi Sharon, 

That would be fine. 

Thanks!
Melanie

**Pull request closed without merging**
