### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by daphnied**
added advice and css style

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @daphnied,

It looks like you are on your master branch. You'll want to make those changes, add, commit, and push on your experiments branch.

**Comment by daphnied** [comment]
I don’t know where to start or how to get to my experiments branch. I keep going over the Github lesson and I am lost. What part of Skillcrush 105 is the section that will help me figure this out?

**Comment by acodeinprogress** [comment]
Hey @daphnied,

All you have to do is run **git checkout experiments** in your terminal. :)

**Comment by acodeinprogress** [comment]
Hey @daphnied,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Pull request closed without merging**
