### PR TITLE
fork challenge and add alice-advice.html

### PR DESCRIPTION
**Pull request by aliceFung**

### CODE REVIEW

**Comment by sareg0** [comment]
Hey Alice,
I noticed that you changed the stylesheet link from
<link rel="stylesheet" type="text/css" href="../css/style.css">
to
<link rel="stylesheet" type="text/css" href="style.css">
Was this a mistake? I notice you put all your css changes into the appropriate file, however. You relative path needs the '../css/style.css' part in.

Would you like to try and fix that up, add, commit and push again and the changes will show up in this pull request.

**Comment by sareg0** [comment]
Hi @aliceFung!

Is there a reason you change the following?
<link rel="stylesheet" type="text/css" href="../css/style.css">
to
<link rel="stylesheet" type="text/css" href="style.css">

**Comment by aliceFung** [comment]
Yes, it was a remnant from when I was viewing it on my computer.  Thanks for pointing it out!  I'll fix it immediately.

**Comment by aliceFung** [comment]
Done. I have committed and pushed the changes.  Thanks again!

**Comment by sareg0** [comment]
Hey @aliceFung I'm so sorry for the delay, but that is all merged up now!! Great work!

**Pull request merged**
