### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by Ania-chan**
Hi,
Sorry for taking so long to fix my merge issues.
I'm creating a new pull request.
Thanks,
Ania

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Ania-chan,

This is super close!

It looks like there are still some merge conflict markers in the index.html file. You can see them highlighted in green if you click on the [Files Changed](https://github.com/skillcrush/skillcrush-104/pull/1769/files) tab near the top of this page. You'll need to remove those before we can get this merged in.

Once you do that, you can add, commit, and push and your changes will join your pull request here. Then we can get everything merged in.

xoxo,
Sharon

**Comment by Ania-chan** [comment]
Hi Sharon!

Thanks for your answer.
As you can probably see from all the pull requests I've sent I really suck
in GitHub.
I tried but I don't know how to fix the current merge conflict.
In Files Changed I can see that the line " font-size: 36px; " is doubled in
style.css.

I checked the experiments branch in my local file and also tried the online
editor in github,
but in boths css files "font-size: 36px;" isn't doubled.

Can you help me with this problem?
Thanks,
Ania

2018-04-24 5:46 GMT+09:00 Sharon <notifications@github.com>:

**Comment by acodeinprogress** [comment]
Hey @Ania-chan!

The `font-size` line in the CSS is perfectly fine. You'll see that one line is highlighted in red and has a `-` next to it. That means it was deleted. Just below it, it is highlighted in green and has a `+`. That means it was added. In this case, the deleted and addition right next to each other cancel each other out so it's good to go.

The problem is actually in the index.html file. There are some conflict markers hanging out (`<<<<<<< HEAD`, `=======`, `>>>>>>> master` that we'll need to remove.

xoxo,
Sharon

**Comment by Ania-chan** [comment]
Hi Sharon
Thank you for your answer. I fixed index.html file. Is it ok now?
Thanks,
Ania

**Comment by redrambles** [comment]
Hey @Ania-chan !

Good work - your code is merged in!! 🎉

**Pull request merged**
