### PR TITLE
i hope this commit works

### PR DESCRIPTION
**Pull request by melrey**

### CODE REVIEW

**Comment by melrey** [comment]
pull request

**Comment by acodeinprogress** [comment]
Hey @melrey,

Looks great! I only have 1 tiny request for you. We would like for your ruby file to be in the ruby folder. If you could move it over there, then run git add -A, commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by melrey** [comment]
Hi Sharon,

Where did my ruby file go? I don't understand what I did wrong. Here's a
screenshot of the steps I took. I'm not super clear on working with GitHub
so if you could walk me through exactly what I need to do, I'd appreciate
it. Thanks.

[image: Inline image 1]

**Comment by acodeinprogress** [comment]
Hey @melrey,

Your Ruby file is in the main directory. All you need to do is drag it into the Ruby folder (which you should see in the main directory) and run *git add -A*, commit, and push.

**Comment by melrey** [comment]
Hi acodeinprogress,

I moved my ruby file into the ruby folder. Please let me know if there's still an issue.

**Comment by melrey** [comment]
Hi,

Not sure if you saw my comment in GitHub but I moved my ruby file
yesterday. Please let me know if there's anything else you need me to do.

**Comment by acodeinprogress** [comment]
Great work, @melrey! Your code is all merged in.

**Comment by melrey** [comment]
Thanks!!

**Pull request merged**
