### PR TITLE
Molly's advice added & styled

### PR DESCRIPTION
**Pull request by mlippert89**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @mlippert89,

Great pull request! I have a couple requests before we can merge this in.
1) It looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's. 
2) We'd like for you to include an advice page and then a link to your advice page in the index.html file.

If you could make those changes, that would be great! Once you do that, you can add, commit, and push and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by mlippert89** [comment]
Hello Sharon,

   I was wondering about all those styles! I took care of the changes you
requested, but now I am running into a different problem. I made a mistake
while trying to commit the files again and now I keep getting this error:

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

I have already restarted my computer and it did not solve the issue. Do you
have any suggestions on how to tackle this problem?

Thank you!

Molly

**Comment by acodeinprogress** [comment]
Hey Molly!

Oh no! I haven't seen that before so I went to my best friend (google) and searched for your error: **Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'**

I found this article: https://stackoverflow.com/questions/38004148/another-git-process-seems-to-be-running-in-this-repository

Go ahead and try that out and let us know if it works!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @mlippert89,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 10 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @mlippert89,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
