### PR TITLE
My forked repository with file named Janelle Scharon

### PR DESCRIPTION
**Pull request by ascharon**

### CODE REVIEW

**Comment by sareg0** [comment]
I've given you a few things to fix in this pull request @ascharon. All you have to do is make the changes add, commit and push them, and they will join your other commits here in this pull request.

**Comment by sareg0** [comment]
Hey @ascharon you've done such a great job fixing those things up. Now I just have one more task. I notice that you have both a css file called 'janellescharon-style.css', AND a custom class in the main 'style.css' file.

What I would like you to do is choose, as they both have the same content.

You are currently referenceing 'href="../css/style.css"' in your html file, so if you could delete 'janellescharon-style.css', then add, commit and push again, you will be ready for merge!

Many thanks in advance.

**Comment by ascharon** [comment]
Hi, 
I chose to use the janellescharon.style.css and removed my section from style.css. 
Thanks!Janelle  


     On Friday, July 3, 2015 5:57 PM, sareg0 <notifications@github.com> wrote:
   

 Hey @ascharon you've done such a great job fixing those things up. Now I just have one more task. I notice that you have both a css file called 'janellescharon-style.css', AND a custom class in the main 'style.css' file.What I would like you to do is choose, as they both have the same content.You are currently referenceing 'href="../css/style.css"' in your html file, so if you could delete 'janellescharon-style.css', then add, commit and push again, you will be ready for merge!Many thanks in advance.—

**Comment by sareg0** [comment]
Hey @ascharon thanks for doing all the fixes! I have now merged it all in! Whooohooo!

**Pull request merged**
