### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by lindsjg8**
Submitting my advice.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @lindsjg8!

This is looking great! We just need one more thing from you: A link to your advice page in the main index.html file. Once you have done this, you can add and commit your changes, and then push up your experiments branch once more, which will automatically update your pull request.

Let us know if you have any questions - great work so far!

Cheers,
Ann

**Comment by lindsjg8** [comment]
Hi Ann,
Thanks! I can’t believe I forgot that.  

I added the link, saved and committed my changes, and pushed my experiments branch.  I did submit a new pull request via GitHub. Did I need to do that? I think your comments means that github will automatically update my pull request when I push changes.  However, I didn’t see any evidence of that when I checked pull requests on the GitHub repo.  I submitted a new pull request, but let me know if that isn’t something I should normally do.  My understanding is that you have to make a pull request for every pushed change. Is that correct?

Thanks,
Lindsey

**Comment by redrambles** [comment]
Hello @lindsjg8 !

Thanks for making that change! 

While a pull request is open, there is no need to open it again. Given that this pull request was opened based on your experiments branch, any time you push up some updates to that branch, your pull request will be automatically updated. Now if you [take a look at this page](https://github.com/skillcrush/skillcrush-104/pull/1633/files), which lists the changes included in your pull request (no matter the number of commits) - we see that the index.html file is listed among the changed files now and we can see the line that you added there. Awesome! 

The only thing that remains to be done at this point, is bring your experiments branch up to date with the main code base - a very regular task when you work on teams. I can resolve this myself on my end if you would like, or you can do it yourself! Let me know which option you would like and if you have any questions!

Cheers,
Ann

**Comment by lindsjg8** [comment]
Thanks.  I did the git fetch upstream...etc. chain of commands on Terminal (screenshot hopefully attached).  I think that is what you mean by bringing experiments up to date?  
screen shot 2018-02-14 at 3 26 57 pm

**Comment by redrambles** [comment]
Hello there!

Thank you very much for your screenshot - I think I found the issue. Can you please run 
`git remote -v` and show us the result that you get in the terminal?

Thank you!

**Comment by lindsjg8** [comment]
Here it is.  
screen shot 2018-02-15 at 7 31 27 pm

**Comment by redrambles** [comment]
@lindsjg8 - thank you!

Do you see how both the origin and upstream remote addresses are the same? They are both pointing to your forked copy of the repository. We do want the 'origin' remote to point to your repository - but the upstream remote needs to point to Skillcrush's repository, which is the main code base that is evolving regularly as pull requests are accepted.

No worries! We need to correct that upstream address by running:

`git remote set-url upstream git@github.com:skillcrush/skillcrush-104.git`

Once that is done, hop back into your master branch and run `git fetch upstream` once more. This time you will see that there will be updates. Then merge into your master branch `git merge upstream/master` and then move into your experiments branch and merge in your freshly updated master branch. You will notice that there will be a merge conflict in css/style.css - and possibly another in index.html, depending on how much the code has evolved. Once you resolve the merge conflicts (make sure to keep everyone's code and to delete conflict markers) - you can add and commit and then push up your branch, and we should be good to merge in your code!

Let us know if you have questions!

**Comment by lindsjg8** [comment]
I think/hope I did what you asked.  It's crazy how much I forget about github over the course of 24 hours.

**Comment by redrambles** [comment]
Hey @lindsjg8 !

I know what you mean - Git really sinks in after you've been using it regularly for a while - and that's also usually when you begin to see (and really appreciate) the huge benefits you get from incorporating it into your workflow!

Right now I'm not seeing a change in your pull request. If you run 'git status' in your branch, is your working directory clean or do you still see some changes that you need to add and commit? If your working directory is clean, can you try pushing up your branch again? `git push origin experiments`

**Comment by lindsjg8** [comment]
Doh...I wonder if I typed git push origin master (instead of experiments).  I tried what you just said. Screenshot attached.  
screen shot 2018-02-15 at 9 38 52 pm

**Comment by redrambles** [comment]
@lindsjg8 

Yay!!! This is excellent - your code is merged in. Time to celebrate!

**Pull request merged**
