### PR TITLE
Kevin added advice

### PR DESCRIPTION
**Pull request by kevinkaitaozhao**
Some advice to share.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @kevinkaitaozhao,

This looks great so far! I have a couple requests before we can merge this in.
1) It looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's.
2) We would like for you to include a link to your advice page in the index.html file.

Once you make those changes, you can add, commit, and push and it will join your pull request here.

xoxo,
Sharon

**Comment by kevinkaitaozhao** [comment]
Thanks! I made the changes, added, committed, and now am trying to push but am getting the following comment in my terminal: "Updates were rejected because the tip of your current branch is behind its remote counterpart. Integrate the remote changes before pushing again." I tried pulling the origin master but that didn't seem to work. Any advice?

Thanks!

**Comment by acodeinprogress** [comment]
Hey @kevinkaitaozhao,

It looks like you got this figured out. Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Sharon

**Comment by kevinkaitaozhao** [comment]
@acodeinprogress Yep! I was able to figure it out. Thanks for the help!

**Pull request merged**
