### PR TITLE
malenes advice changes

### PR DESCRIPTION
**Pull request by malene33**
How about trying my advice?!

### CODE REVIEW

**Comment by malene33** [comment]
not sure how to fix that!

**Comment by malene33** [comment]
new fixes to index.html file

**Comment by malene33** [comment]
fix problems

**Comment by acodeinprogress** [comment]
Hey @malene33,

It looks like you removed someone's link in the index.html file. If you look at the Files Changed tab on the this page, it'll show the link highlighted in pink (towards the top of the file - don't worry about the rest of the pink on the page). If you could add that back in then add, commit, and push, your changes will join this pull request.

Let me know if you need any help!

**Comment by malene33** [comment]
i believed it is fixed now if you want to check it.

**Comment by acodeinprogress** [comment]
Hey @malene33,

I'm not seeing any changes. Did you make sure to push your branch up to GitHub?

**Pull request merged**
