### PR TITLE
Added advice page

### PR DESCRIPTION
**Pull request by alisande07**
Added alisande advice page to html and also added some css style.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @alisande07,

It looks like you changed Malene's styles and replaced them with your name. We still want Malene's styles in the css file so you can change those back and just add your own styles underneath.

**Comment by alisande07** [comment]
I changed the styles in the css file back to Malene's name per the lines highlighted in red. Sorry for the confusion!

**Comment by acodeinprogress** [comment]
Hey @alisande07,

It looks like you didn't add any of your own styles to the stylesheet. You can add them at the bottom of the page.

**Comment by acodeinprogress** [comment]
Hey @alisande07,

It looks like you copy and pasted some styles from another pull request. Your code seems to have extra + in front of every line. Also, you'll need to specify each css property to have personal identifiers from your advice page. Otherwise, these styles will affect all pages rather than just yours.

**Pull request closed without merging**
