### PR TITLE
Jennsadvice

### PR DESCRIPTION
**Pull request by jennerram**

### CODE REVIEW

**Comment by jennerram** [comment]
Adding my advice to the mix!

**Comment by redrambles** [comment]
Hey @jennerram!

This is awesome! We just have a few requests for you before we can merge this in.

1) You are using a custom stylesheet called 'css/jenn-wise-advice.css'. That's great! However - we only need _your_ code in that stylesheet - and not everyone else's. Just the lines of CSS in that file that pertain to your particular advice page, so you can delete the rest of the code.

2) In your advice page, you are linking to the main stylesheet (css/style.css) - but you'll want to link to your custom stylesheet instead (css/jenn-wise-advice.css).

3) There is a small typo that was introduced in the main index.html file, on line 20 (a '>'). Please remove it.

Once you have made those changes and saved your files - you'll need to add (`git add -A`), commit (`git commit -m "your message here"`) and then push up your files once more (`git push origin jennsadvice`) - which will automatically update this pull request.

At that point we should be all set to merge in your code!

Let us know if you have any questions, and keep up the great work!!

Cheers,
Ann :)

**Comment by jennerram** [comment]
Thanks so much, Ann!!  I actually got a little turned around and only after I had created my own style sheet did I realize I could've just contributed to the main css.  But now I see the difference.  I've made the changes you listed and hopefully, I'm there.  Let me know if I missed anything and thanks so much again.
Jenn

**Comment by acodeinprogress** [comment]
Hey @jennerram,

Thanks so much for making those changes! There's just one more tiny thing that we'll need to do.

On line 20, there is an extra `]` at the end of the line. If you could remove that, that would be perfect!

Then you can add, commit, and push just like you did last time and your changes will join your pull request here.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @jennerram,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
