### PR TITLE
Second commit attempt

### PR DESCRIPTION
**Pull request by anddaley**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @anddaley,

It looks like you also committed your GitHub page. You'll want to make a new repo for your GitHub page and put your files there. If you could please remove it from this repo, that would be fantastic. Then you can run git add -A, commit, then push. Your changes will join your pull request here and I can get it merged in.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @anddaley, I just want to let you know that this pull request will close in 20 days if no changes are made. Please let me know if you need any help making any of the requested changes!

**Comment by anddaley** [comment]
Hey Sharon Thanks for the update. My MacBook is experiencing some technical
difficulties at the moment. I will try to sort this out today if possible.

I am not sure I fully understand what is required so I may get back to you
for some help later on. Thanks again.

El lunes, 14 de diciembre de 2015, Sharon <notifications@github.com>
escribió:

> Hey @anddaley <https://github.com/anddaley>, I just want to let you know
> that this pull request will close in 20 days if no changes are made. Please
> let me know if you need any help making any of the requested changes!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/skillcrush/skillcrush-104/pull/384#issuecomment-164342992>
> .
>


-- 
Sent from my iPad Air 2

**Comment by acodeinprogress** [comment]
Hey @anddaley,

That's totally fine! Feel free to send an email to your blueprint and we'll help get everything all fixed up!

**Comment by acodeinprogress** [comment]
Hey @anddaley,
It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 10 days if no changes are made.
Let me know if you need any help!

**Comment by anddaley** [comment]
Hey Sharon could you send me some details as to what I need to do here I
don't fully understand.


Thanks.




El lunes, 28 de diciembre de 2015, Sharon <notifications@github.com>
escribió:

> Hey @anddaley <https://github.com/anddaley>,
> It looks like we haven't heard from you in a while. I just want to let you
> know that this pull request will be closed in 10 days if no changes are
> made.
> Let me know if you need any help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/skillcrush/skillcrush-104/pull/384#issuecomment-167693501>
> .
>


-- 
Sent from my iPad Air 2

**Comment by acodeinprogress** [comment]
Hey @anddaley,

It looks like you have a few extra files. The files are your github page (anddaley.github.io), an extra ruby file (it looks like you have andy-daley and timothy) and you edited the advice-template. All you have to do is remove the extra files (or you can move them elsewhere outside of this directory) and undo your changes to the advice template. Then you can run git add -A (don't forget the -A), commit, and push. Your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @anddaley,

Are you still having trouble with this assignment? Let me know and I'd be happy to help! If you don't want to post here, you can also send an email to your blueprint and we'll help get things straightened out. Otherwise, I can close this pull request and you can try again.

**Comment by acodeinprogress** [comment]
Hey @anddaley,

It's been a while since we heard from you. I'm going to close this pull request but please feel free to submit a new one when you're ready!

**Pull request closed without merging**
