### PR TITLE
Advice Page Commits pull requests

### PR DESCRIPTION
**Pull request by korra69**
Hi!
Hope my advice page words and pictures help someone down the road. Please merge them.
Thanks,
korra69

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @korra69,

This looks great! I only have 1 minor change for you. It looks like you're linking to your personal css file in your advice page. It also looks like your css file is empty and that all of your css is in the general style.css file. There are 2 ways we can fix this:
1) You can delete your personal css file, then link to the style.css file in your HTML
2) You can move your css styles from style.css to your personal css file.

Once you change that, you can run git add -A, commit, then push and your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @korra69,

We haven't heard from you in a while. This pull request will be closed in 10 days if no changes are made.

Again, let me know if you need any help!

**Comment by korra69** [comment]
Hey, Sharon,

sorry for not getting back. I thought my stuff had been merged weeks ago
from our correspondence on my pull request page on github. Since then, I
requested a transfer from the November blueprint to the January one which
it now looks like I won't be able to finish either due to my work schedule.

Hope to work with you in a later Skillcrush cohort once I'm done with
production in March. I really miss all I have been learning and the
terrific Skillcrush community...

Thanks for checking in!
Leslie



On Thu, Feb 11, 2016 at 10:54 AM, Sharon <notifications@github.com> wrote:

> Hey @korra69 <https://github.com/korra69>,
>
> We haven't heard from you in a while. This pull request will be closed in
> 10 days if no changes are made.
>
> Again, let me know if you need any help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/skillcrush/skillcrush-104/pull/414#issuecomment-182929893>
> .
>



-- 
Leslie Di Mitri
Executive Director
The Mitney Project
PO Box 349
Georgetown, SC 29442
direct tel. 917.763.7558
main tel. 843.546.7900
www.themitneyproject.org

"To a willing heart, nothing is impossible."

**Comment by acodeinprogress** [comment]
Hey @korra69,

That sounds good! I'll close this pull request for now and you can make a new one when you're ready!

**Pull request closed without merging**
