### PR TITLE
Adding advice by Fiona.

### PR DESCRIPTION
**Pull request by Fiona176**
Advice - my 2 cents.  :)

### CODE REVIEW

**Comment by Fiona176** [comment]
Looks like I messed up - I have no idea how to fix this!  Help!

**Comment by acodeinprogress** [comment]
Hey @Fiona176,

I saw that Ann helped out with this one in the Google Group. We haven’t heard from you in a while and haven't seen any changes on GitHub. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 10 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by Fiona176** [comment]
Hi again Sharon - I followed the instructions that Ann gave me, but it never showed me a conflict.  I did fix up my style.css file so it only has my stuff in it now.  Ann said that I did not need to do another pull request, so I didn't - but I will if you think I should.  I'm so sorry about my screw-up. 


Fiona

**Comment by acodeinprogress** [comment]
Hey @Fiona176,

That's not a problem! She's totally right! You don't need to make a new pull request. But you will need to push up your changes to GitHub. When you do, you'll need to make sure that your changes are on your fionas-advice branch and that you pushed to your fionas-advice branch.

When it comes to merge conflicts, there is 1 but you would only see it if you pull down the latest code from Skillcrush's repo. If you want the practice, you can totally do that! If not, I'm happy to take care of it on my end. The only required change is removing everyone else's styles from your stylesheet. :)

xoxo,
Sharon

**Comment by Fiona176** [comment]
Okay - I pushed the branch up to Github (I think).  And I definitely removed the others from my stylesheet.  I sure hope I did things right this time!  Unfortunately I have been having a (non-life-threatening!) medical thing that is going to take another couple of weeks to deal with - so not sure when I will get back to this, but I will try to make it as soon as possible.  Please forgive my giving you any extra work.  I am enjoying my classes at Skillcrush so much!  :)  Thank you for your help! 


Fiona

**Comment by acodeinprogress** [comment]
Hey @Fiona176,

I'm so sorry to hear about your medical troubles. I totally understand how difficult it is so please take care of yourself and don't worry about Skillcrush! You have lifetime access to the material and we'll still be here while you work on it. Your pull request looks fantastic so your code is all merged in. [Yay!](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Keep up the great work and I hope you feel better soon!

xoxo,
Sharon

**Comment by Fiona176** [comment]
Thank you so much Sharon!You are part of what makes Skillcrush so fantastic!:)
Fiona

Sent from Xfinity Connect Mobile App



------ Original Message ------

**Pull request merged**
