### PR TITLE
added zoe's advice

### PR DESCRIPTION
**Pull request by zoevons**
Some advice I am sharing

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @zoevons,

I noticed that you didn't add a link in the index.html file or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by zoevons** [comment]
Hi Sharon,

Thanks so much, not sure what happened and I think I got a bit confused.
Anyway I have watched the lesson again and I think I have done it
correctly.  Has it joined my pull request or do I need to go back into
Github and do it again?

Many thanks
Zoe

**Comment by acodeinprogress** [comment]
Hey @zoevons,

I don't see any changes for this pull request. Did you maybe push your changes to your master branch rather than your newadvice branch?

xoxo,
Sharon

**Comment by zoevons** [comment]
Oh no I am not sure, can you help me?

**Comment by acodeinprogress** [comment]
Hey @zoevons,

When you're in your terminal, you'll want to make sure that you're in your newadvice branch when you make your changes. When you're done with your changes and you've added and committed, you'll want to make sure that you push to your newadvice branch rather than your master branch.

Does that help?

xoxo,
Sharon

**Comment by zoevons** [comment]
Hi Sharon,

Third time lucky!! Has this worked??

Zoe :)

**Comment by acodeinprogress** [comment]
Hey @zoevons,

I see the changes! Awesome! This is super close. I saw that you added your css to the main stylesheet and then you made a personal stylesheet. You only need your styles in one of these places. Since your advice page links to your personal stylesheet, I suggest removing your styles from the main stylesheet (style.css). and if you could add a link to your advice page in index.html that would be great!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @zoevons,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 20 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by zoevons** [comment]
Hi Sharon,  I have done it again I really hope correctly this time :)

**Comment by acodeinprogress** [comment]
Hey @zoevons,

Awesome! I merged in your other pull request so I'll go ahead and close this one.

xoxo,
Sharon

**Comment by zoevons** [comment]
Yay yay Yay!!

**Pull request closed without merging**
