### PR TITLE
adding Meryl to forked repo

### PR DESCRIPTION
**Pull request by marshmeryl**

### CODE REVIEW

**Comment by sareg0** [comment]
hi @marshmeryl  , I see that you have commited your ruby file to the main directory of the repo. We would like it to be in the 'ruby' folder of the directory.

Could you plus just drag it into the appropriate folder on your computer, then add, commit and push the changes. They should join the pull request here.

Let me know if you need help

**Comment by marshmeryl** [comment]
Sorry about that! All should be well now.

Cheers!

**Comment by acodeinprogress** [comment]
Hey @marshmeryl! It looks like you have a Meryl.rb file in both the main directory and the ruby folder. Could you please remove Meryl.rb from the main directory, run git add -A, commit, and then push the changes? Then we can get it all merged in!
Thanks!

**Comment by acodeinprogress** [comment]
All merged! Great job!

**Pull request merged**
