### PR TITLE
Holly's commit

### PR DESCRIPTION
**Pull request by RubyRabelle**
pull please ;)

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @RubyRabelle,  your ruby file is in the root directory of the repository. We would like you to put it in the 'ruby' folder of the repo. Could you please move it to the right directory then run git add -A (the -A makes sure that the file we deleted on the computer is also deleted in git), commit, then push? Your changes will join your pull request and then I'll merge it!

**Comment by RubyRabelle** [comment]
i think that should do it ;)

**Comment by RubyRabelle** [comment]
does the pull request need to be open or closed?

**Comment by acodeinprogress** [comment]
Hey @RubyRabelle, great work! The pull request needs to be open in order to merge it, which I'm going to do now! :)

**Pull request merged**
