### PR TITLE
My advice

### PR DESCRIPTION
**Pull request by JenBroman**
Let's merge these updates

### CODE REVIEW

**Comment by redrambles** [comment]
Hello @JenBroman !

This is great but there were several lines deleted in the index.html file as part of your bringing your branch up to date with master, [see the index.html page here.](https://github.com/skillcrush/skillcrush-104/pull/1754/files) This no doubt occurred by mistake when you were resolving the merge conflict in that file.

No worries! We can fix this. Let's first rewind your experiment 'back in time' to the point just before you bring it up to date with master:

1) First thing - make sure that you are in your experiment branch! `git checkout experiment`

2) Now let's rewind: `git reset --hard 861bba`

3) Now let's pop into the master branch `git checkout master` and fetch from  upstream `git fetch upstream` - just in case anything new happened since the last time you fetched. Then let's merge those new commits into your local master branch: `git merge upstream/master`

4) Great! Now let's pop back into your experiment branch: `git checkout experiment`

5) Now let's merge in our freshly updated master branch: `git merge master`

This will create a conflict in the index.html file - just like it did the first time you proceeded with the merge. Now when you open your index.html file, make sure to keep all the code and only delete the conflict markers (such as >>>>HEAD, or =======) and save the file.

6) Next - let's add that again: `git add .`

7) And let's commit: `git commit -m "bringing up to date with upstream"`

8) And now let's push up your experiment branch once more, using a slightly different command:

`git push -f origin experiment`

We need to use the `-f` flag here because we changed our commit history by rewinding back in time earlier so that we could do our merge over again. This should be used with caution - but in this case, it only applies to your branch and your commit - so we are ok. :)

9) Dance! :) 


At this point, we should be good to merge in your code.

Let us know if you have any questions!!

Cheers,
Ann

**Comment by JenBroman** [comment]
Thanks so much Ann! I learned a lot and really appreciate your help.  U
rock!

JB

Jennifer Broman
annapoliswebs.com
410-897-2495

**Comment by redrambles** [comment]
Hello @JenBroman !

This is so so so close!! Great job on following the steps in my reply above - I know that there were several, and some involved commands that we didn't see in class.

We just need two more changes, and they are really small - and then we'll be all set to merge in your code!

1) The main index.html file is looking beautiful - there's just a little conflict marker that snuck in that we need removed. (Check out line 73)

2) Another skillcrush-104 repository is inside your current skillcrush-104 repository! It's sort of like inception, the code version! No worries - we can just delete that directory by running:

`rm -rf skillcrush-104`

Once we've made those changes, we'll want to add them using `git add -A` and then commit: `git commit -m "your message here"` and then push up one more time: `git push origin experiment` - which will automatically update your pull request.

That should do it!

Let us know if you have any questions and keep up the great work!

**Comment by JenBroman** [comment]
Hi Ann - thanks so much for walking me through this - again.  I think I
need to better learn how to check my work before submitting on github and
I'm a still a bit hazy on getting around.  This is something I'll look into
so that when I'm coding IRL such simple mistakes won't need to be pointed
out.  Thanks for your kind nudges in the right direction.  Hopefully my
code is as it should be now (although I'm still not sure).

Best, JB

Jennifer Broman
annapoliswebs.com
410-897-2495

**Comment by acodeinprogress** [comment]
Hey @JenBroman,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
