### PR TITLE
Changes to HTML and CSS

### PR DESCRIPTION
**Pull request by luceritodelalba**
added my own advice and a pretty gif to advice-lucero.html
and some styling to style-lucero.html

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @luceritodelalba,

This looks great! I just have a couple teensy requests before I merge this in.
1) We would like for you to include a link to your advice page in the index.html file. 
2) It looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's. 

Once you make those changes, you can add, commit, and push and they'll join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by luceritodelalba** [comment]
Hi Sharon,
Thanks for the feedback, and the extra committing and pushing practice - fun to see it show up in the commits tab here :) 
Cheers,
Lucero

**Comment by acodeinprogress** [comment]
Hey @luceritodelalba,

Thanks for making that change! I see that you added a link to the main style.css stylesheet in your advice page. You actually don't need to do that since you don't have any styles in that file. What I meant by my first request was that we have an index.html file where students add links to their advice pages. We'd like for you to add a link to your advice page in that file.

xoxo,
Sharon

**Comment by luceritodelalba** [comment]
Whoops! Goes to show one should read feedback carefully ;)
Ok, added my link to index.HTML and removed the extra link to the main stylesheet. 

Cheers, Lucero

**Comment by acodeinprogress** [comment]
Hey @luceritodelalba,

Perfect! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
