### PR TITLE
Newbranch - Advice from Vincent

### PR DESCRIPTION
**Pull request by violandi**
Advice I would like to share.

### CODE REVIEW

**Comment by redrambles** [comment]
Hello @violandi !

Ok! So there are two separate advice files in your pull request - and two links in the index.html file, pointing to each of them. (You can check out the files included in your pull request [here](https://github.com/skillcrush/skillcrush-104/compare/master...violandi:newbranch).)

Here's what we would like you to do! 

1) Choose one of the two advice pages you submitted and delete the other from your project. 
2) Remove the link in the index.html file that points to the advice page that has been discarded.
3) Add a little styling in the main css/style.css page which would apply to your advice page. 

Once you have done this, add and commit your changes using:

`git add -A`

(This command is necessary because you are deleting a file, and we want to make sure that Git applies that change as well, and not only the modifications to existing files.)

then commit:

`git commit -m "your message here"`

followed by pushing up your branch:

`git push origin newbranch`

Which will automatically update your pull request here (since it is based on that branch).

Once that is done, we should be good to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by violandi** [comment]
Thanks.

Sorry about that. I made the necessary updates. Let me know if I need to do
anything else.

Vin

**Comment by redrambles** [comment]
Hello @violandi !

Thanks for those changes - we are nearly there! I see you have only one advice page and only one link in the index.html page, which points to this remaining advice page. Great! Now we just need one more thing - a few styles that will apply to your advice page, which you would add to the css/style.css stylesheet, given that this is the one that you link to in the `<head>` of the advice page.

Once you have added those styles, add and commit that change and push up your branch once more - we should then be good to merge in your code!

Let us know if you have any questions! :)

Cheers,
Ann

**Comment by violandi** [comment]
Do I need to add css?

**Comment by redrambles** [comment]
Hello @violandi,

Yes - adding CSS is part of the challenge - but you don't need to make it complicated. Just a few declarations in the main stylesheet that make use of your .vincent-violandi-advice class so that these only apply to your advice page, and you're done!

(Once you add and commit that change and push up your branch once more, of course. ;))

**Comment by violandi** [comment]
Hi Ann.

Sorry for the back and forth. I added some styles to the page and
committed. Let me know how it went.

Thanks.

Vincent

**Comment by redrambles** [comment]
Hey @violandi,

This is great - your code is all merged in! :)

Cheers,
Ann :)

**Pull request merged**
