### PR TITLE
Techmeg's advice added

### PR DESCRIPTION
**Pull request by techmeg**
uh...not sure what to do next..

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @techmeg,

This looks great! There are just a couple changes that we'll need to make before we can merge this in.
1) There's a slight typo with your link in the index.html. You have `<a/>` instead of `</a>`.
2) You added your styles to a personal stylesheet and the main style.css. We only need to add our styles in one of these places. Since your advice page is linking to the main style.css file, we can just go ahead and delete the personal stylesheet.

Once you make these changes, you can run a slightly different git command (`git add -A`), then commit and push. They'll join your pull request here and then we can go ahead and merge this in!

xoxo,
Sharon

**Comment by techmeg** [comment]
OK, hopefully I did that right -- Git still feels like gibberish to me.

**Comment by acodeinprogress** [comment]
Hey @techmeg,

Thanks for making those changes - you did it perfectly! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif). Yay!


xoxo,
Sharon

**Comment by techmeg** [comment]
whew!

**Pull request merged**
