### PR TITLE
Created new reb advice html with corresponding css file.

### PR DESCRIPTION
**Pull request by rebthemaker**
Thanks for showing me how to sync/ upstream, merge, and pull requests! Now I feel like I can help with open source on GitHub :)

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @rebthemaker,

Looks great! I only have 1 tiny request for you. We would like for your advice file to be in the advice folder. If you could move it over there, then run a slightly different git command (git add -A), commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by rebthemaker** [comment]
Hey @acodeinprogress,

Thank you! I moved, added, committed, and pushed.  Thanks for your help :)

~ Reb

**Comment by acodeinprogress** [comment]
Hey @rebthemaker,

I'm not seeing any change. Is it possible that you fixed this on a different branch and not 104-project-branch-1?

**Comment by rebthemaker** [comment]
I think I got it this time @acodeinprogress, thanks for your patience :)

~ Reb

**Comment by acodeinprogress** [comment]
Hey @rebthemaker,

So sorry for the delay! Thanks for making that change! You did a great job and your code is all merged in! Yay!

xoxo,
Sharon

**Pull request merged**
