### PR TITLE
Jill's changes

### PR DESCRIPTION
**Pull request by revjill**
adding some advice

### CODE REVIEW

**Comment by redrambles** [comment]
Hey there @revjill !

This is great! The only thing we need you to change is the text for your link in the index.html file says 'Hillary's advice' but you probably want it to say something like 'RevJill's advice'. :)

Once you make that change, add and commit your code and push up your advice branch once more. This will automatically update your pull request, and we should be all set to merge in your code!

Let us know if you have any questions, and keep up the great work!

Cheers,
Ann :)

**Comment by revjill** [comment]
please disregard this commit - I'm trying to figure out the best way to remove it.

**Comment by redrambles** [comment]
Hello @revjill ! 

You do not need to create a new pull request - this one is great! It is completely normal that your local master branch is now many commits ahead of your 'origin' master branch - these are the commits that you fetched from the main codebase (upstream) and merged locally - but you didn't push up your local master branch, so your remote repository's master branch remains at the state it was when you initially forked it from the main codebase. You can go ahead and update your origin's master branch if you like - by running: `git push origin master`. 

If you have made the change to your link's text in your index.html file in your advice branch - add and commit that change and push up your advice branch once more, and we should be good to go!

Does this help clarify?

**Comment by revjill** [comment]
yes, completely clarified, thank you! All the changes have been made. :)

**Comment by acodeinprogress** [comment]
Hey @revjill,

I'm not seeing any updates to this pull request. You'll want to make sure to make the changes on your advice branch and then add, commit, and push to your advice branch on GitHub.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @revjill !

How is it going with this? Let us know if you need any help!

Cheers,
Ann

**Comment by redrambles** [comment]
Hey @revjill ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
