### PR TITLE
rm1411 added advice

### PR DESCRIPTION
**Pull request by rm1411**
Some advice that I would love to share.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @rm1411,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by rm1411** [comment]
Hi Sharon,

Oops, I was trying to follow along with the lesson. I thought that I was doing everything ok since I didn't get any error messages and was getting the feedback I was supposed to be according to the lesson. I apologize, I'm so unfamiliar with all of this that I don't even know where to look to see what I'm missing or where it should be, what I need to do, etc. At what point do you think I made the mistake? What could I have missed? 

Thanks so much for any help you can give me!

**Comment by rm1411** [comment]
Hi, I responded on the GitHub page but never got a reply so I'm guessing I wasn't supposed to send a message that way. I'm trying to figure out what I'm doing today again with the same lesson and I'm beyond confused. I really would like to start from scratch since I have no idea where the mistake was made or how to know where to pick up and start again, but I have no idea how to do that or if it's possible. Is there any way you could tell me what I'm doing wrong?

Thank you,
Robyn

**Comment by rm1411** [comment]
Hi Sharon, I made the change in index.html and I pushed my branch. I'm not sure if I followed the steps correctly because I haven't received any comments.

Thanks,
rm1411

**Comment by acodeinprogress** [comment]
Hey @rm1411,

I'm not seeing any changes. Did you add, commit, and then push? and were you on your master branch and then push to your master branch?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @rm1411,

I'm going to go ahead and close this pull request since you submitted a new one. Great job!

xoxo,
Sharon

**Pull request closed without merging**
