### PR TITLE
Commits

### PR DESCRIPTION
**Pull request by JlPerks**

### CODE REVIEW

**Comment by JlPerks** [comment]
Feel free to delete....

**Comment by acodeinprogress** [comment]
Hey @JlPerks,

Would you like me to close this pull request without merging it?

**Comment by JlPerks** [comment]
Hey Sharon. I have multiple pull requests. If you could add the one with
the advice page and delete the others that would be great.

Thanks!

Jessica Perkins

**Comment by acodeinprogress** [comment]
Hey @JlPerks,

This is the only pull request I see from you. When merging a pull request, I can't merge in specific files.
In order to merge in this pull request, you'll need to make a few changes.
1) Remove the rb.swp file.
2) Add some content to your ruby file.
3) Add your personal stylesheet (the one you link to in your HTML file).
4) Add a link to your advice page in the index.html file.
Once you make those changes, run git add -A (don't forget the -A), commit, and push. You changes will join your pull request here.

Let me know if you need any help!

**Comment by JlPerks** [comment]
Sharon, I was playing around with the command line and found a way to add a
ruby file from there but I could not swap it out for the original document.
That is where the rb.swp.file came from and why my original Ruby document
is blank. I added a line and I will re-push in a moment.
Also somehow I had two html files. The one marked index.html that I didn't
mean to add in. There is another, named jperkins.html in the advice folder
with the proper link to the stylesheet I placed in the css folder.

I deleted the rb.swp file, index.html file and the css file. I also added a
small puts line to my original ruby file that I moved to the ruby folder
and re-pushed everything. It might be to soon but I cannot select a new
pull request in Github at the moment. The Create Pull Request button is
blurred no matter what I select in the drop down above it. I will give it
some time and try again.


Thanks!

[image: Inline image 1]

**Comment by acodeinprogress** [comment]
Hey @JlPerks,

The index.html file is where you'll add a link to your advice page so you'll need to add it back in with all the content that was in there before. We'd also like for you to add a stylesheet (preferably the one that you're linking to in your advice page). Lastly, it looks like you have an extra ruby file that is in the main directory. You'll need to remove that file, then run git add -A (don't forget the -A), commit, and push.

**Comment by JlPerks** [comment]
Sharon, I have done all of that more than once and the instructions lead me
to believe that the style sheet is optional.
I have pushed several times and I would like to be done with this
assignment. I would appreciate it if my adjustment were merged and this be
marked as completed. Frankly I'm tired of going back and forth on this.
Thank you.

-Jessica

**Comment by acodeinprogress** [comment]
Hey @JlPerks,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 17 days if no changes are made.

**Comment by JlPerks** [comment]
I did all the things you asked for in the previous message.

**Comment by acodeinprogress** [comment]
Hey @JlPerks,

We really appreciate the time and effort that you put into this assignment, but unfortunately we are unable to merge your current code into the main skillcrush-104 repo. I would be happy to go over this with you more in depth during office hours, which is on Thursday at 8:30pm EDT. We can sort it out together and then I can merge it in on the spot. If you can't make office hours, another option would be to set up a 15 minute session to work through it. Let me know what works best for you!

**Comment by acodeinprogress** [comment]
Hey @JlPerks,

I'm going to close this pull request. Feel free to submit a new one when you're ready! Or if you'd like to reopen this one and work on it together, let me know. :)

**Pull request closed without merging**
