### PR TITLE
Hope's loop

### PR DESCRIPTION
**Pull request by HopeFrost**
skillcruch 104 fork challenge!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @HopeFrost, 

I have some improvements before this can be merged. 

- line 1 - there needs to be a puts in front of your string so that ruby knows the print this to the console
- line 2 - answer = gets, this should be gets.chomp. Chomp removes the new line that is added when the user hits 'enter' to submit their answer. Otherwise, even if the user types 'yes', it won't match our answer == 'yes' condition.
- line 3 - answer == yes, yes should be a string. If we use yes instead of 'yes', our program will think that it's a variable and will complain that it's undefined.
- your ruby file is in the main directory. It should be in the ruby folder.

Go ahead and make these changes then run git add -A, commit, and push the changes. They will join this pull request. Then I can go ahead and merge.

Let me know if you need any help.

**Comment by HopeFrost** [comment]
Opps. thats what I get for writing a quick file in the command line.

**Comment by acodeinprogress** [comment]
Hey @HopeFrost, thanks for making those changes! I forgot to mention that you have an endless loop. Our answer never changes so we will never break out of our loop and it will go on forever. Could you fix it up, then add, commit, and push?
Let me know if you need any help with this!

**Comment by acodeinprogress** [comment]
Hey @HopeFrost, great work! It's all merged in now!

**Pull request merged**
