### PR TITLE
Created file abz99.rb

### PR DESCRIPTION
**Pull request by abzxc99**

### CODE REVIEW

**Comment by sareg0** [comment]
Hi @abzxc99 I can't seem to find the fork that submitted this pull request from. May I ask if you cloned the repo directly or forked it?

**Comment by abzxc99** [comment]
Hi, I really don't remember for this particular pull request but I do remember forking the repo.  Any way I could find out?  Thanks.

**Comment by abzxc99** [comment]
Hi, I had created the pull request for file "abz99.rb".  Then I couldn't create a pull request for the later file "advice.rb".  I think I deleted the forked repository and forked again to check if I could create pull request for "advice.rb".  I was able to. Were we supposed to create a second pull request in the same repository?  Thanks.

**Comment by acodeinprogress** [comment]
Hey @abzxc99, I'm going to go ahead and close this pull request. Could you try this exercise again by forking the skillcrush, making your changes, and submitting another pull request?

Let me know if you need any help!

**Pull request closed without merging**
