### PR TITLE
EV added advise and changed some styles

### PR DESCRIPTION
**Pull request by evgdesign**
here is my first pull request

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @evgdesign,

This looks great! I just have a couple small requests before I merge this in.
1) We would like for you to include a link to your advice page in the index.html file.
2) It looks like you included a merge conflict in the style.css file. You can see it if you take a look at the Files Changed tab on this page.

If you could fix those up, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @evgdesign,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 10 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by evgdesign** [comment]
I'm too lost. I am going to start over. 

:(

**Comment by acodeinprogress** [comment]
Hey @evgdesign,

You're totally welcome to close this pull request and start over if you'd like. But you did a great job removing that merge conflict!

All you have to do next is add a link to your advice page into the index.html file. We also suggest using all lowercase for class and id names so that's another change that you can make in your HTML and CSS files.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @evgdesign,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif). I'm gonna go ahead and close your other pull request since this one is perfect! :)


xoxo,
Sharon

**Pull request merged**
