### PR TITLE
Teeba changes

### PR DESCRIPTION
**Pull request by talkhuda**
Hi!

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @talkhuda!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in.

Once you add your link, add and commit your changes and then push your 'trial' branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by talkhuda** [comment]
Hi!

I re-did it and everything was fine until I tried to merge the master and I
got an error. Can you please check it out as I did commit so not sure what
the message is about?

Also, I am a bit confused with one thing. How/when did the master get
updated in all this process? If I made a change on my trial branch, how did
the master change if I did not update ir or did I?

Thanks,
Teeba

**Comment by talkhuda** [comment]
oops forgot to attach.

**Comment by redrambles** [comment]
Hello @talkhuda !

The issue here was that there were conflicts in the style.css and index.html files, which needed to be resolved. This happens often when we are merging code -and that's ok! Do you want to try to resolve these yourself? What do you get in the Terminal when you are on your 'trial' branch and you run 'git status'?

**Comment by talkhuda** [comment]
I think it worked now! Do you see my updates advice? 

Thanks!

**Comment by acodeinprogress** [comment]
Hey @talkhuda,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by talkhuda** [comment]
sorry, I have been traveling. Will do this as soon as I can thanks!

Teeba

**Pull request closed without merging**
