### PR TITLE
Commit on a forked repository

### PR DESCRIPTION
**Pull request by emccool**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey Erin,

Looks great! I only have 2 tiny requests for you. 

1) It looks like you're linking your advice page to the main stylesheet but then it looks like you made a custom stylesheet. Would you mind changing it to direct to the correct stylesheet?
2) It also looks like you've added everyone's styles into your custom stylesheet. Since only your page will be using it, you only need to have your personal styles. 

If you could make those changes, then run add, commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by emccool** [comment]
Hello Sharon,

Everything should be corrected now. Let me know. Thanks and sorry about
that.

Erin

**Comment by acodeinprogress** [comment]
Hey @emccool,

Great job with the merge conflict! It looks like you left some of it in:
**<<<<<<< HEAD
 
 =======**
  				<a href="advice/sara-advice.html">Sara's Advice</a><br>
  				<a href="advice/joel-advice.html">Joel's Advice</a><br>
          <a href="advice/advice-sara-suzanne.html">Sara Suzanne's Advice</a><br>
 **>>>>>>> bd0198a92e0ca9aabbcfa8b7cb7548a624f05387**

If you could just remove the bolded lines, that would be fantastic! Then you can add, commit, and push and then I can get your changes merged in.

**Comment by emccool** [comment]
Hi Sharon.

I went back to the forked repository assignment and followed the
instructions from the beginning updating my local copy of the repository
etc and checked all three files index advice and css and didnt notice
anything in the head tags of any of them, so i added and re pushed
everything up to git hub. I hope it is resolved now.

Let me know if it is not,

Erin

**Comment by acodeinprogress** [comment]
Hey @emccool,

If you click on the Files Changed tab and scroll down, you'll see this:
screen shot 2016-07-26 at 3 16 41 pm

**Comment by emccool** [comment]
Hi Sharon,

I deleted the head tags and info in between in the repository on github per
the screenshot you sent and submitted a new pull request. i hope everything
is ok now; i think it should be. let me know if it isn't.

Thanks,

Erin

**Comment by acodeinprogress** [comment]
Did you push up your changes? I'm not seeing any extra commits showing and the Files Changed page still shows the items I circled on the screenshot.

**Comment by emccool** [comment]
Hi Sharon. I edited the changes right on git hub last night and submitted a
new pull request. I didn't use the local repository on my computer. I will
do that now for you.

**Comment by emccool** [comment]
Sharon,

I think everything should finally be okay now with this assignment. I hope. Let me know if it isn't. Sorry for all this back and forth.

Erin

**Comment by emccool** [comment]
Hi Sharon,

I think everything should be correct now with this assignment. Let me know
either way.

Erin

**Comment by acodeinprogress** [comment]
Hey @emccool,

No worries! This is perfect! Great work! Your code is all merged in.

**Pull request merged**
