### PR TITLE
adjusted page to add advice

### PR DESCRIPTION
**Pull request by carrietannahill**
I added some advice.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @carrietannahill,

This looks great so far! I have one request before I can merge this in.
It looks like you added your CSS to 2 files - a personal stylesheet and the main style.css stylesheet. Since your advice file links to the main style.css stylesheet, you can go ahead and delete your personal stylesheet.

Once you do that, you'll want to run a slightly different git command (git add -A), commit, and push. Your changes will join your pull request here and then we can get everything merged in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @carrietannahill,

Thanks for making that update! I'm seeing some merge conflict markers in the style.css stylesheet. You can see them if you take a look at the [Files Changed](https://github.com/skillcrush/skillcrush-104/pull/1765/files) tab near the top of this page. Would you mind removing those markers and then adding in your custom CSS?

Once you do that, you'll want to add, commit, and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @carrietannahill,

This is getting closer! There are still a couple changes we'll need to make:
1. It looks like you deleted someone elses styles in the main.css stylesheet. Again, you can see what was deleted by looking at the [Files Changed](https://github.com/skillcrush/skillcrush-104/pull/1765/files) tab near the top of the page.
2. There seems to be an extra `</div>` in the index.html file that will need to be taken out.

Once that's done, you can follow the same steps of adding, committing, and pushing.

xoxo,
Sharon

**Comment by carrietannahill** [comment]
Yay!  Thank you so much for all your help!

**Pull request merged**
