### PR TITLE
Added my advice 

### PR DESCRIPTION
**Pull request by SaraBohannon**
Added html file. Edit style.css to include style class.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @SaraBohannon,

It looks like there's a merge conflict happening. Do you remember how to resolve this?

**Comment by SaraBohannon** [comment]
Hi, @acodeinprogress, 

I edited the style.css file with the online editor to correct the missing end line. Then, chose commit changes. Is this correct or was I supposed to make changes from my local repo?
Thanks!
Sara

**Comment by acodeinprogress** [comment]
Hey @SaraBohannon,

You'll also need to get the changes from the Skillcrush-104 repo and resolve any merge conflicts. Then you can add, commit, and push your changes. Then I can merge in your code.

**Comment by SaraBohannon** [comment]
I made changes and created a new pull request. Should I have somehow re-submitted this pull request instead?

Thanks!
Sara

**Comment by acodeinprogress** [comment]
Hey @SaraBohannon,

It's totally up to you. When you work as a dev, it is going to be preferable to fix any merge conflicts on your own. But since we're just starting with git, it's totally ok to make a new pull request. I'm going to go ahead and close this one and merge in your other one.

**Pull request closed without merging**
