### PR TITLE
Gabby's advice

### PR DESCRIPTION
**Pull request by gbbywtsn**
Added advice

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @gbbywtsn,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by gbbywtsn** [comment]
Thanks! The link to my advice page should already be in the index.html
file.

**Comment by redrambles** [comment]
Hello @gbbywtsn !

[Here is a link to the changes included in your branch.](https://github.com/skillcrush/skillcrush-104/pull/1674/files) 

You see how your advice page and your css is there - but there is no index.html file which includes the link to your advice page? Once you add your link in the main index.html file, add and commit that change and then push up your sample branch, the index.html file will join the other 2 files in the changeset and then we should be good to merge in your code. Is it possible that you already made the change, but either didn't add/commit it - or didn't push it up?

Let us know if you have any questions!

**Comment by redrambles** [comment]
Hey @gbbywtsn ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Comment by gbbywtsn** [comment]
Hey Ann!

Thanks for checking back with me! I think I just made the change. Let me
know if I did it right!

Thanks!

Gabby

**Pull request closed without merging**
