### PR TITLE
added the tommyb file to the ruby folder

### PR DESCRIPTION
**Pull request by tommyb67**

### CODE REVIEW

**Comment by tommyb67** [comment]
I copied the advice.html template and the style.css file and made some small updates

**Comment by sareg0** [comment]
Hi @tommyb67, great work!

I have some improvements before this can be merged.

I see that you are committing the entire contents of the repo's css file in your css file. 

Since this would mean a lot of double up, could you please delete all of the CSS code that you do not need from your 'tommyb_advice.css' file, and then add, commit and push the changes. They will join the other changes in this pull request. Then I will be able to merge.

**Comment by tommyb67** [comment]
Hello!

I cleaned out the css file and did the add, commit and push.  Please let me
know if any other updates are required.

Best regards,

Tommy Brennan
718-440-4306
tommybrennan@gmail.com

**Comment by acodeinprogress** [comment]
Hey @tommyb67, I went ahead and updated your stylesheet link to point toward your tommybstyle.css file instead of the style.css and added a link to your html page in the index file. Now it's all merged! Great work!

**Pull request merged**
