### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by nfarnold10**

### CODE REVIEW

**Comment by nfarnold10** [comment]
Just a couple of small changes

**Comment by acodeinprogress** [comment]
Hey @nfarnold10,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by nfarnold10** [comment]
Welp, there's a conflict. I'll let an admin take care of that...

**Comment by redrambles** [comment]
Hey @nfarnold10,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Comment by nfarnold10** [comment]
Huzzah! Thanks!

**Pull request merged**
