### PR TITLE
I would like to pull my changes to the master

### PR DESCRIPTION
**Pull request by echoingnarc**
Hello, 

I have added my advice html and css file for the master. 

Thank you,

Chynna

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @echoingnarc,

It looks like you made a custom stylesheet but your src links to style.css. If you could update it so it links to the right place, that would be great! Then you can add, commit, and push and your changes will join your pull request here.

**Comment by acodeinprogress** [comment]
Hey @echoingnarc,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by echoingnarc** [comment]
Hi Sharon,

I will have an updated pull request by the end of today.

Thanks,

Chynna

**Comment by echoingnarc** [comment]
Hi Sharon, 
Here's my new pull request.

**Comment by acodeinprogress** [comment]
Hey @echoingnarc,

It looks like you changed the css link of the main index.html file to link to your custom file rather than style.css. We want this file to inherit from the main style.css file. Instead, could you change that back and then link your personal advice page to your custom css file?

**Comment by acodeinprogress** [comment]
Hey @echoingnarc,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 10 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @echoingnarc,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

**Pull request closed without merging**
