### PR TITLE
my advice

### PR DESCRIPTION
**Pull request by francescaamott**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @francescaamott,

I have a few small requests before we merge this in.
1) It'd be great if you could add in an advice page so that your styles will be applied to something!
2) It looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's.
3) We would like for you to include a link to your advice page in the index.html file. 

Once you make those changes, all you have to do is add, commit, and push your changes and they will join your pull request here.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @francescaamott,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 6 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by francescaamott** [comment]
Hi Sharon,

Sorry for the delay, I was on vacation.  I made the adjustments you requested.  Please let me know if this is correct.  

Thanks,
Francesca

**Comment by acodeinprogress** [comment]
Hey @francescaamott,

Thanks for making those changes! I'm still not seeing a link to your advice page in the index.html file. Once you add that in and push those changes, we can get this merged in.

xoxo,
Sharon

**Comment by francescaamott** [comment]
Hi Sharon,

Did it go through?  I was getting some error messages, then it looked like it went through multiple times.

Francesca

**Comment by acodeinprogress** [comment]
Hey @francescaamott,

Awesome! Thanks for adding that in!

It looks like in the process of making those changes, you added another skillcrush-104 folder inside this project. What you'll need to do is move that out of this project (or delete it) and then run a slightly different git command (git add -A), commit, and push.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @francescaamott,

We still haven't heard from you on this. I'm going to go ahead and close this. Feel free to reopen it or open a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
