### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by bcreativedigitaldesign**
Added my personal advice page and CSS code. Also added a link to the index page to my advice page.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @chicygeekdesigns,

This is suuuper close!

It looks like an extra file snuck into our pull request. You have two CSS files- one named `css/dstetser-style .css` and one named `css/dstetser-style css`. Let's go ahead and delete the `css/dstetser-style .css` file!

Once you do that, you'll need to run a slightly different git command (git add -A), then commit and push. Your changes will then join your pull request here.

xoxo,
Sharon

**Comment by chicygeekdesigns** [comment]
Sharon,

Thank you. I am really struggling with this lesson. I am having a difficult time understanding the order of operations as well as what to do or where to go next if I am not seeing the expected results. 

Here I realized that I had a space in the file name and went back to correct it but then I didn’t  know how yo remove the current pull request and submit a new one. 

Since I also write technical documentation, I think I need to go back through this class and create my own cheat sheet and see if I can wrap my head around the processes.

Thanks, 
Daphne Stetser

**Comment by acodeinprogress** [comment]
Hey @bcreativedigitaldesign,

There's no need to go back and make a new pull request! We can simply edit this one.

The way we can do that is to go into our css folder and delete the extra file with the space in it. Once you've done that, you'll run a slightly different git command (git add -A), then commit and push. That will automatically update this pull request and we can get it merged in!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @bcreativedigitaldesign,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
