### PR TITLE
added elyse's advice to 105 practice project

### PR DESCRIPTION
**Pull request by evilLA1989**

### CODE REVIEW

**Comment by evilLA1989** [comment]
Thank you to whichever Skillcrusher's job it is to go through all of these!

**Comment by redrambles** [comment]
Hello @evilLA1989!

This is great!! There's only one small issue. Your advice file is in the root of the project, but we want it to be in the advice/ directory. Once you move your 'elysevilla-advice.html' file in the advice directory, go ahead and add (`git add -A`), commit (`git commit -m "your message here"`) and push up your branch once more, which will automatically update your pull request. 

Then we should be all set to merge in your code! :)

Cheers,
Ann

**Comment by evilLA1989** [comment]
Ah! Sorry about that! I'll make the adjustment in the morning. Thank you
for letting me know.

Best,
Elyse

**Comment by redrambles** [comment]
Hey @evilLA1989,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
