### PR TITLE
updated my personal CSS and HTML docs

### PR DESCRIPTION
**Pull request by cschero**
Changed a couple of things to get it looking like more my style

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @cschero,

This is super close! I just have a couple small requests before we can merge this in:
1. It looks like you changed the body class in the advice template to your own class. This is the general template that all students will be using so we'd like for the class to remain as we had it.
2. You added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's. 

Once you make those changes, you can add, commit, and push and they'll join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by cschero** [comment]
Good Afternoon Sharon,
Thanks for the response back. I am confused as to what exactly to do for
the first portion because the course explicitly tells us to branch the
advise template and then change the body class to equal something specific.
I have attached a screenshot of the conflicting rules given and would love
and guidance you could give regarding its fixing.

**Comment by acodeinprogress** [comment]
Hey @cschero,

Hmm.. unfortunately, that screenshot did not come through. On the bright side, I think I know which instructions you're talking about.
screen shot 2018-06-18 at 4 06 14 pm
It sounds like you're referring to #4 in these instructions, correct? If you take a close look at #2, we have you open up your copy of the advice template in the text editor. The rest of the directions are for your copy of the advice template only. So when we say that you should change the class on the body, we are specifically referring to your copy of the advice template rather than the advice template itself.

Does that make a little bit more sense?

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @cschero,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
