### PR TITLE
Made my own advice page

### PR DESCRIPTION
**Pull request by AnniinaT**
Added my own advice page

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @AnniinaT,

It looks like you may have included everyone's styles in your personal stylesheet. Since only your page will be using it, you only need to have your styles. All you have to do is remove the rest, then add, commit, and push and your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @AnniinaT,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @AnniinaT,

This is just a reminder that this pull request will close in 10 days if no changes are made.

**Comment by AnniinaT** [comment]
Hi, I left only my own styles in the css file, hopefully this works now.

**Comment by acodeinprogress** [comment]
Hey @AnniinaT,

Thanks for making those changes! Your code is all merged in.

**Pull request merged**
