### PR TITLE
Included my advice

### PR DESCRIPTION
**Pull request by daphnied**
Added my 2 cent

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @daphnied,

This looks great! I just have a couple teensy requests before I merge this in. 
1) It looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's.
2) We'd love it if you included a link to your advice page in the index.html file.

Once you make those changes, you can add, commit, and push and they'll join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by daphnied** [comment]
I added the link and fixed the stylesheet

**Comment by redrambles** [comment]
Hey @daphnied,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Comment by daphnied** [comment]
Yes!!! 👍🏽

**Pull request merged**
