### PR TITLE
adding me to the file

### PR DESCRIPTION
**Pull request by ceatonneon**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @ceatonneon,

Looks great! I only have 1 tiny request for you. We would like for your ruby file to be in the ruby folder. If you could move it over there, then run git add -A, commit, then push, your changes will join your pull request here.
If no changes are made in 10 days, this pull request will close. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by ceatonneon** [comment]
My ruby file is in the folder and always has been.  There is a copy of the file in the directory above, but the code won't work with that one.

**Comment by acodeinprogress** [comment]
Hey @ceatonneon,

File structure can be a bit confusing sometimes, but GitHub has a feature that is a big help.
If you take a look at the Files Changed tab, it shows this as the only added ruby file:
screen shot 2017-05-16 at 6 46 38 pm
If it were in the ruby folder, it would show ruby/cynthia.rb instead of cynthia.rb.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @ceatonneon,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
