### PR TITLE
Adding file

### PR DESCRIPTION
**Pull request by m3r41ck**

### CODE REVIEW

**Comment by m3r41ck** [comment]
Adding "Merrick Calder's Advice Page"

**Comment by acodeinprogress** [comment]
Hey @m3r41ck,

Looks great! I only have 2 tiny requests for you. 

1) It looks like you've added everyone's styles to your stylesheet. Since only your advice page will be using it, you only need to have your personal styles.
2) We would like for your ruby file to be in the ruby folder. Your file should also start with a lowercase letter.

If you could make those changes, then run git add -A (don't forget the -A), commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @m3r41ck,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @m3r41ck,

This is just a reminder that this pull request will close in 9 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @m3r41ck,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

**Pull request closed without merging**
