### PR TITLE
Added RJ Young advice

### PR DESCRIPTION
**Pull request by RJacqueline**

### CODE REVIEW

**Comment by RJacqueline** [comment]
I had some advice I wanted to share

**Comment by acodeinprogress** [comment]
Hey @RJacqueline,

This is looking great! I just have some requests before we can merge this in.
1) It looks like you renamed someone else's file and replaced their styles. You can see this in the [Files Changed](https://github.com/skillcrush/skillcrush-104/pull/1573/files) tab towards the top of this page. We'd like to preserve everyone's work so we'll need you to change that file back.
2) You have another personal CSS file but it's in the main directory rather than the css folder. It'd be great if you would move it into that folder.
3) Your advice file is also in the main folder and will need to be moved to the advice folder. When you do this, you'll need to update the link to your personal stylesheet.
4) I see that you added some styles in the main style.css file. Since you already made a personal stylesheeet with your styles, you don't need to include them in the style.css folder.

Once you make those changes, you'll need to run a slightly different git command (git add -A), then commit, and push. It'll join your pull request here and we can get it merged in. If no changes are made in 10 days, this pull request will close.

Happy git-ing!
-Sharon

**Comment by acodeinprogress** [comment]
Hey @RJacqueline,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by RJacqueline** [comment]
Hi Sharon,

Yes, please pull request so that I can give this my full attention.

My apologies for the delay.

Jacqueline

**Pull request closed without merging**
