### PR TITLE
my advice and styles

### PR DESCRIPTION
**Pull request by MelissaTarbox**
My personalized advice and styles for you to review.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @MelissaTarbox,

Looks great! I only have 2 tiny requests for you. 

1) It would be great if you could include a link to your advice page in the index.html file.
2) It looks like you may have added all the styles from style.css into your personal stylesheet. All you need to have in there are your personal styles - so you can remove the rest of the contents.

If you could make those changes, you can add, commit, then push and your changes will join your pull request here.

Let me know if you need any help!

**Comment by MelissaTarbox** [comment]
Hi Sharon,
I would be happy to make those changes, but I just want to clarify to make
sure I am understanding correctly.
Request 1) Include a link to your advice page in the index.html file. Does
this mean the main html file that I copied to edit (the root file)?
Request 2) To remove the rest of the comments I can simply delete them, or
I do not need to comment them out?
Also, a question about the push, do I need to push it back using the origin
of my branch or my pull request?

Best,

Melissa


On Sun, May 8, 2016 at 1:57 PM, Sharon <notifications@github.com> wrote:

> Hey @MelissaTarbox <https://github.com/MelissaTarbox>,
>
> Looks great! I only have 2 tiny requests for you.
>
> 1) It would be great if you could include a link to your advice page in
> the index.html file.
> 2) It looks like you may have added all the styles from style.css into
> your personal stylesheet. All you need to have in there are your personal
> styles - so you can remove the rest of the contents.
>
> If you could make those changes, you can add, commit, then push and your
> changes will join your pull request here.
>
> Let me know if you need any help!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/skillcrush/skillcrush-104/pull/523#issuecomment-217736432>
>



-- 
Melissa Tarbox

**Comment by MelissaTarbox** [comment]
Hi Sharon, 
I believe I figured it out, hopefully the push links nicely here.
Best,
Melissa

**Comment by acodeinprogress** [comment]
Hey @MelissaTarbox,

It looks like you edited Jaiela's files somehow. Would you mind removing those extra files then running git add -A, commit, and push?

**Comment by MelissaTarbox** [comment]
Hi Sharon,
I see what you mean, I somehow pushed Jaiela's files with my own. I will resubmit when I get home tonight. Sorry about that!

**Comment by acodeinprogress** [comment]
Hey Melissa,

It looks like the files are still there. Did you use git add -A, with the capital A?

**Comment by MelissaTarbox** [comment]
Hi Sharon,
Perhaps I am using the git add function wrong, this is what I have been
typing in:
git add index.html
should I be doing something different?

On Wed, May 11, 2016 at 8:21 PM, Sharon <notifications@github.com> wrote:

> Hey Melissa,
>
> It looks like the files are still there. Did you use git add -A, with the
> capital A?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/skillcrush/skillcrush-104/pull/523#issuecomment-218627661>
>



-- 
Melissa Tarbox

**Comment by acodeinprogress** [comment]
Hey @MelissaTarbox,

**git add index.html** says "add only the index.html file", whereas **git add .** says "add all of my modified files, but don't delete anything", and **git add -A** says "add all of my modified files including removing any deleted files".

I hope this helps!

**Comment by MelissaTarbox** [comment]
Hi Sharon,
I'll give that "git add -A" a try. Hopefully that works!
Best,
Melissa

On Thu, May 12, 2016 at 12:28 PM, Sharon <notifications@github.com> wrote:

> Hey @MelissaTarbox <https://github.com/MelissaTarbox>,
>
> *git add index.html* says "add only the index.html file", whereas *git
> add .* says "add all of my modified files, but don't delete anything",
> and *git add -A* says "add all of my modified files including removing
> any deleted files".
>
> I hope this helps!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/skillcrush/skillcrush-104/pull/523#issuecomment-218811409>
>



-- 
Melissa Tarbox

**Comment by acodeinprogress** [comment]
Hey @MelissaTarbox,

It looks like Jaeila's files are still there. Did you remove them and then run git add -A?

**Comment by MelissaTarbox** [comment]
Hi Sharon,
I think so, I only added my files using git add -A. Do I need to do
something else first to remove them?


On Sun, May 15, 2016 at 1:30 PM, Sharon <notifications@github.com> wrote:

> Hey @MelissaTarbox <https://github.com/MelissaTarbox>,
>
> It looks like Jaeila's files are still there. Did you remove them and then
> run git add -A?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/skillcrush/skillcrush-104/pull/523#issuecomment-219299019>
>



-- 
Melissa Tarbox

**Comment by acodeinprogress** [comment]
Hey @MelissaTarbox,

That's perfect! Thanks for fixing that up! One other thing is that it looks like there's a merge conflict happening. Do you remember how to resolve this?

**Comment by MelissaTarbox** [comment]
Hi Sharon,
Off the top of my head no, but I know I have notes one it. I will try to
correct it tonight when I get home.


On Tue, May 17, 2016 at 6:04 PM, Sharon <notifications@github.com> wrote:

> Hey @MelissaTarbox <https://github.com/MelissaTarbox>,
>
> That's perfect! Thanks for fixing that up! One other thing is that it
> looks like there's a merge conflict happening. Do you remember how to
> resolve this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/skillcrush/skillcrush-104/pull/523#issuecomment-219868401>
>



-- 
Melissa Tarbox

**Comment by MelissaTarbox** [comment]
Hi Sharon,
I think I fixed the problem, it all looks good in my command line.

**Comment by acodeinprogress** [comment]
Hey Melissa,

In order to fix the merge conflict, you'll have to get the latest changes from the skillcrush-104 and merge them in with your code. Then you should be prompted that there is a merge conflict.

**Comment by MelissaTarbox** [comment]
Hi Sharon,
I did that and then when I attempted to correct the errors I kept getting
messages that the branch was clean, but then I would see on Github that the
error was still there. I'm not entirely sure what I am doing incorrectly.

On Wed, May 18, 2016 at 8:22 PM, Sharon <notifications@github.com> wrote:

> Hey Melissa,
>
> In order to fix the merge conflict, you'll have to get the latest changes
> from the skillcrush-104 and merge them in with your code. Then you should
> be prompted that there is a merge conflict.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/skillcrush/skillcrush-104/pull/523#issuecomment-220195959>
>



-- 
Melissa Tarbox

**Comment by acodeinprogress** [comment]
Hey @MelissaTarbox,

Could you tell me what commands you're running?

**Comment by MelissaTarbox** [comment]
Hi Sharon,
I have tried running a git pull command
I have tried running a git merge upstream
I have tried running a git push just to get updated files up
I have also tried adding files individually along with using the git add -A
command to make sure all my files were up to date.
I have also poked around trying to find the files marked as in conflict, so
far no luck.

On Thu, May 19, 2016 at 3:30 PM, Sharon <notifications@github.com> wrote:

> Hey @MelissaTarbox <https://github.com/MelissaTarbox>,
>
> Could you tell me what commands you're running?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/skillcrush/skillcrush-104/pull/523#issuecomment-220426970>
>



-- 
Melissa Tarbox

**Comment by MelissaTarbox** [comment]
screen shot 2016-05-20 at 4 44 08 pm
This is the message I get shown when I do a push.

**Comment by acodeinprogress** [comment]
Hey @MelissaTarbox,

This might be because you made your changes in your experiments branch rather than your master branch. Try merging experiments into master and see what happens. If not, could you run git status in your master branch and let me know the result? Once you merge into master, you may need to make a new pull request for your master branch.

**Comment by MelissaTarbox** [comment]
Hi Sharon,
I will try all of that tonight when I get home and keep you posted.

On Sun, May 22, 2016 at 1:57 PM, Sharon <notifications@github.com> wrote:

> Hey @MelissaTarbox <https://github.com/MelissaTarbox>,
>
> This might be because you made your changes in your experiments branch
> rather than your master branch. Try merging experiments into master and see
> what happens. If not, could you run git status in your master branch and
> let me know the result? Once you merge into master, you may need to make a
> new pull request for your master branch.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/skillcrush/skillcrush-104/pull/523#issuecomment-220846298>
>



-- 
Melissa Tarbox

**Comment by MelissaTarbox** [comment]
Hi Sharon,
I'm still having some weirdness, I've attached some screenshots so you can see what I see:
this was when I tried to merge the experiments branch with the master branch 
screen shot 2016-05-23 at 5 09 56 pm
this was when I tried to checkout the status on the master branch
screen shot 2016-05-23 at 5 12 28 pm
screen shot 2016-05-23 at 5 13 09 pm
this was when I did some pushes
screen shot 2016-05-23 at 5 17 07 pm
screen shot 2016-05-23 at 5 17 26 pm

**Comment by acodeinprogress** [comment]
Hey @MelissaTarbox,

It looks like you're trying to merge origin master into your experiments branch. When you use origin, it's saying that we want to get the code from our online repo.
Instead, try running this command in your master branch: **git merge experiments**
Then try pushing to origin master.

Try that out and let me know what you get!

**Comment by MelissaTarbox** [comment]
Hi Sharon,
I did as you asked, but the conflict notice is still present here, I do not see it in my git/command line. I'm confused as to why I keep getting that notice here but not in my command line. I've included some screen shots. These are the screenshots from running the git merge experiments and push origin master from the master branch:
screen shot 2016-05-25 at 6 35 14 pm
screen shot 2016-05-25 at 6 35 21 pm
screen shot 2016-05-25 at 6 35 24 pm
This is from when I did a git status check and push from my experiments branch to make sure it was all up to date. 
screen shot 2016-05-25 at 6 35 43 pm

**Comment by acodeinprogress** [comment]
Hey @MelissaTarbox,

Did you pull the changes from skillcrush's skillcrush-104 repo? If not, try doing that and see what happens. Also, it looks like you're pushing to origin master but you've created a pull request for your experiments branch. If you want, you can close this pull request and make a new one for your master branch, but it's up to you.

**Comment by MelissaTarbox** [comment]
Hi Sharon,
I feel like at this point with the amount of mistakes I've made on this
pull request, creating a new one might be the best idea. My branch
(experiments) would remain available to push up to a pull request even if
this pull was closed, correct?

On Thu, May 26, 2016 at 3:56 PM, Sharon <notifications@github.com> wrote:

> Hey @MelissaTarbox <https://github.com/MelissaTarbox>,
>
> Did you pull the changes from skillcrush's skillcrush-104 repo? If not,
> try doing that and see what happens. Also, it looks like you're pushing to
> origin master but you've created a pull request for your experiments
> branch. If you want, you can close this pull request and make a new one for
> your master branch, but it's up to you.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/skillcrush/skillcrush-104/pull/523#issuecomment-221977136>
>



-- 
Melissa Tarbox

**Comment by acodeinprogress** [comment]
Hey Melissa,

That's exactly right. If you close this pull request, your branch will still be available and you can submit a new pull request. :)

**Pull request closed without merging**
