### PR TITLE
Still Erica

### PR DESCRIPTION
**Pull request by ericalbryant**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @ericalbryant,

This looks great! I have one minor change for you before I merge this in. We would like for your Ruby file to be in the Ruby folder. If you move the file then run git add -A, commit, then push, your changes will join your pull request here. Then I can get it all merged in!

Let me know if you need any help!

**Comment by ericalbryant** [comment]
thank you! I moved that file :)

**Comment by acodeinprogress** [comment]
Hey @ericalbryant,

Thanks for making that change! It looks like the file is still showing up in GitHub. If you could run git add -A (don't forget the -A), commit, then push, it should remove the file from git and update your pull request.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @ericalbryant,

It looks like we haven't heard from you in a while. I'm going to close this pull request. Feel free to submit a new one when you're ready!

**Pull request closed without merging**
