### PR TITLE
added some advice!

### PR DESCRIPTION
**Pull request by bernettamoore**
created new advice.html, changed my styl.css and added link to my advice.html to index.html

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @bernettamoore,

This is super close! I just have a couple requests before we can merge this in:
1. It looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's.
2. It looks like you made some changes to other students CSS code in the main style.css file. You'll want to change those back to preserve their styles. You can see what was changed by clicking on the [Files Changed](https://github.com/skillcrush/skillcrush-104/pull/1881/files) tab near the top of this page.

Once you make those changes, you can add, commit, and push and it'll join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by bernettamoore** [comment]
Hi Sharon,
I made those changes.
Thank you!
-Bernetta

**Comment by redrambles** [comment]
Hey @bernettamoore !

Thanks for making those changes! This is nearly ready to be merged in, but I notice that in your advice page, you link to the main css/style.css stylesheet, but you have created a custom stylesheet (css/bernettamoore-advice-style.css) - so you'll want to link to that instead. 

Once you've made that change, go ahead and add, commit and push up your branch once more, and we should be all set! Keep up the great work!

Cheers,
Ann

**Comment by bernettamoore** [comment]
Hi Ann,

I just fixed my advice page.

Thank you,
Bernetta

**Comment by redrambles** [comment]
Hey @bernettamoore - 

Awesome! Thanks for making those changes, your code is all merged in! :)

Cheers,
Ann

**Pull request merged**
