### PR TITLE
Changes for merger

### PR DESCRIPTION
**Pull request by AryVidot**
The image folder and images were removed.
Here is my new version.
What should I do next? This is the message I get in Git bash:

_aryvi@LAPTOP-6BF33PBO MINGW64 ~/documents/websites/skillcrush-104 (aryvidot-advice)_
$ dir
advice  css  index.html  README.md  ruby

_aryvi@LAPTOP-6BF33PBO MINGW64 ~/documents/websites/skillcrush-104 (aryvidot-advice)_
$ git branch
* aryvidot-advice
  master

_aryvi@LAPTOP-6BF33PBO MINGW64 ~/documents/websites/skillcrush-104 (aryvidot-advice)_
$ git merge master
Auto-merging index.html
CONFLICT (content): Merge conflict in index.html
Auto-merging advice/aryvidot-advice.html
CONFLICT (add/add): Merge conflict in advice/aryvidot-advice.html
Automatic merge failed; fix conflicts and then commit the result.

_aryvi@LAPTOP-6BF33PBO MINGW64 ~/documents/websites/skillcrush-104 (aryvidot-advice|MERGING)_
$ git checkout master
error: you need to resolve your current index first
advice/aryvidot-advice.html: needs merge
index.html: needs merge

thank you

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @AryVidot!

This looks great! Thanks for making those changes!

There's just one more small change that is needed before we can merge this in:
It looks like you have an extra file called **New Text Document.txt** that is inside the css folder. You'll need to remove that file and then run a slightly different git command (**git add -A**). Then you can commit and push and your changes and they'll join your pull request here.

xoxo,
Sharon

**Comment by AryVidot** [comment]
I'll do that Sharon.

Thank you.

On 6 Jun 2018 20:19, "Sharon" <notifications@github.com> wrote:

Hey @AryVidot <https://github.com/AryVidot>!

This looks great! Thanks for making those changes!

There's just one more small change that is needed before we can merge this
in:
It looks like you have an extra file called *New Text Document.txt* that is
inside the css folder. You'll need to remove that file and then run a
slightly different git command (*git add -A*). Then you can commit and push
and your changes and they'll join your pull request here.

xoxo,
Sharon

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/skillcrush/skillcrush-104/pull/1891#issuecomment-395146921>,
or mute the thread

**Comment by AryVidot** [comment]
Hi. 
I'm not too sure if I have to resolve the conflict or you?
Please let me know if everything is in order.
best, Ary

**Comment by acodeinprogress** [comment]
Hey @AryVidot,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Comment by AryVidot** [comment]
Great.
Thank you.
Ary

**Pull request merged**
