### PR TITLE
first push to repo for skillcrush

### PR DESCRIPTION
**Pull request by applesauce9091**
Thoughts from life learning :)

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @applesauce9091,

This looks great! I just have a couple small requests before I merge this in.
We would like for you to include a link to your advice page in the index.html file.
I see that your advice file is linking to a personal stylesheet but I don't see that you added that stylesheet to this project.

If you could add those in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @applesauce9091,

Sorry for the confusion! You'll want to edit the index.html file and add in a link to your HTML advice page. If you need some help with how to do this, take a look at the other links in there and see if you can add your own.

xoxo,
Sharon

**Comment by applesauce9091** [comment]
haha ok i think I fixed it :)

**Comment by acodeinprogress** [comment]
Hey @applesauce9091,

I'm not seeing any changes for this pull request.

Did you make sure to complete the following steps?
Add a link to the index.html file like I described in my second message.
Add a personal stylesheet with some CSS.
Run `git add .`
Run `git commit -m "_**Your message here**_"`
Run `git push origin experiments`

If you haven't, your changes should show up here once you complete all those steps.

xoxo,
Sharon

**Comment by applesauce9091** [comment]
yes I have done those steps and I can see my page uploaded:
alexwest-thoughts.html / alexwest-style.css



where else is it supposed to be?​

**Comment by redrambles** [comment]
Hello @applesauce9091! :)

Ok! So I took a look at your repository and I see that you have made some changes to your master branch instead of your experiments branch - including a commit that contains the link to the index.html file. That explains why we weren't able to see the change here.

No worries - we can work this this! Locally, in your directory, please make sure that you are in your experiments branch by running `git checkout experiments`.

Then, merge in your master branch - which contains that link in the index.html file that we want:
`git merge master`

And then pus up your experiments branch once more:

`git push origin experiments`

This will update your pull request and we will be able to see your changes.

As for your master branch, let's rewind it back in time before your accidental commits.
First, check out your master branch:

`git checkout master`

Then let's run a unique command that will rewind it back in time a few commits. This is a powerful command that can be super helpful but must be used carefully. In this case - it's just what we need!

`git reset --hard fc99a34d8a`

Now your master branch will be returned to the state it was before you made changes to it. Then you can go ahead and fetch from upstream:

`git fetch upstream`

Fold in the commits that have since been made on the main code base, which will bring your local master branch in sync with the upstream repository:

`git merge upstream/master`

And then you can checkout your experiments branch once more:

`git checkout experiments`

and merge in your freshly updated master branch:

`git merge master`

At this point - you will get a merge conflict in the index.html branch - which is 100% normal. A few other links were added to the file, so you'll just need to make sure to keep those links as well as yours, and delete any conflict markers.

Once you've done that, save your file, add it back in:
`git add -A`

and then conclude the merge by running:
`git commit -m "merge master into experiments"`

Then the code in your experiments branch will be in sync with the main code base, and you should push up your code and dance!

`git push origin experiments`

Awesome!! Time to celebrate!

**Comment by acodeinprogress** [comment]
Hey @applesauce9091,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by applesauce9091** [comment]
I just found this, not sure how the message got lost, but apparently i
missed it.
I followed the steps from Ann, but did not get a "merge conflict". It came
back with "Already up to date".


so do I then "save", "commit" and do a happy dance? or am I missing
something?
​

**Comment by applesauce9091** [comment]
ok I committed my changes, I think. at least it said everything was up to
date....


​

**Pull request closed without merging**
