### PR TITLE
Branch one

### PR DESCRIPTION
**Pull request by ericpatrickrx**
Some advice that I would love to share.

### CODE REVIEW

**Comment by ericpatrickrx** [comment]
Completed the assignment by adding my advice page and would love some feedback on the design of it!

**Comment by acodeinprogress** [comment]
Hey @ericpatrickrx,

This is awesome!!! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by ericpatrickrx** [comment]
Hi Sharon,

Check it now.

Best,
Eric

**Comment by acodeinprogress** [comment]
Hey @ericpatrickrx,

Great job! Thanks for making that change! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
