### PR TITLE
Sam-Noobs-advice.html

### PR DESCRIPTION
**Pull request by EPIC448**
Hello there,
 I made some small changes which i know you would like. Take a look. 

thanks.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @EPIC448,

Looks great! I only have a couple small requests for you. 
1) We would like for your advice file to be in the advice folder. 
2) We would like for you to include a link to the your advice page in the index.html file. 

If you could make those changes, then run a slightly different git command (git add -A), commit, then push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by EPIC448** [comment]
Hi Sharon,
Would you like me to complete that in Github or do you recommend  on my
local computer.

thank you

**Comment by acodeinprogress** [comment]
Hey @EPIC448,

I highly recommend doing that on your computer and then pushing your changes to GitHub.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @EPIC448,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 10 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @EPIC448,

I'm going to close this pull request since you opened up a new one.

xoxo,
Sharon

**Pull request closed without merging**
