### PR TITLE
Adding molly file

### PR DESCRIPTION
**Pull request by mollystites**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @mollystites,

This looks great! I have one minor change for you before I merge this in. We would like for your Ruby file to be in the Ruby folder. If you move the file then run git add -A (don't forget the -A), commit, then push, your changes will join your pull request here. Then I can get it all merged in!

Let me know if you need any help!

**Comment by mollystites** [comment]
Hi Sharon,

Thanks. I deleted the file, then created a new one...I am having a little
trouble and still not sure if I did it right.

Thanks!

**Comment by mollystites** [comment]
Not sure if I did it correct this time. Thanks.

**Comment by acodeinprogress** [comment]
Hey @mollystites, this is perfect! Great work! Your code is all merged in. :)

**Pull request merged**
