### PR TITLE
testing pull requests

### PR DESCRIPTION
**Pull request by andelka**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @andelka,

Looks great! I only have 1 tiny request for you. We would like for your ruby file to be in the ruby folder. If you could move it over there, then run git add -A (don't forget the -A), commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by andelka** [comment]
Hi @acodeinprogress,

I've just moved the file to the ruby folder as you requested. Thanks for your help!
Apparently, the `git add -A` command is now restricted to the subdirectory, so I had to add the path of the tree as argument in order to have all my changes staged.

**Comment by acodeinprogress** [comment]
Hey @andelka,

Thanks for making that change! It also looks like you're linking to the main style.css stylesheet in your advice page but you made a personal file instead. It also looks like your personal stylesheet has all of the styles from style.css. The only styles you need in your file are your personal ones, so you can remove everyone else's.
Once you make those changes, you can add, commit, and push. 
Let me know if you need any help with this one!

**Comment by andelka** [comment]
Hi Sharon,

Yes, I had started to work on the advice page in the meantime and hadn't pushed my latest commits yet. I should have created a separate branch to avoid having this work in progress in the open pull request, right?

**Comment by acodeinprogress** [comment]
Hey @andelka,

Yep! If you didn't want your advice page work included in this pull request, you could've created another branch. But you did a great job and it's totally fine that you did everything on the same branch!

**Pull request merged**
