### PR TITLE
Jwalters advice

### PR DESCRIPTION
**Pull request by jennwalt**

### CODE REVIEW

**Comment by jennwalt** [comment]
some advice that was great.  I think I figured out the push and pull

**Comment by acodeinprogress** [comment]
Hey @jennwalt,

This looks great so far! I just have a couple of requests before we can merge this in:

1. I noticed that you didn't add any css. If you could add a personal stylesheet, that would be great! 
2. It looks like you have some conflict markers in the index.html file that will need to be removed. You can see them by clicking on the [Files Changed](https://github.com/skillcrush/skillcrush-104/pull/1872/files) tab near the top of this page.

Once you make those changes, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by jennwalt** [comment]
I'm so CONFUSED

**Comment by acodeinprogress** [comment]
Hey @jennwalt!

That's ok! Git and GitHub can be a bit confusing at first.

Let's look at the conflict markers in the index.html file (I've drawn big red arrows pointing the markers that we want to remove from our code):
screen shot 2018-06-06 at 10 59 30 am

Then, you'll want to follow step 6 on https://learn.skillcrush.com/module-13/make-a-change-then-push-to-your-repo/, which has the following directions:
**Now, style up your page using the style.css file. Important: Make sure you preface all your CSS styles with .yourname-advice so that you ONLY change the styles on your page, not everyone’s page!
And a note: If you want to use your own CSS file, that is a-okay. Just make sure you store it in the css folder.**

Once you do all that (you'll want to make sure that you do it all on your jwalters-advice branch), you can follow the normal add, commit, and push steps and your changes will join your pull request here.

Does that help you get started with making changes?

xoxo,
Sharon

**Comment by jennwalt** [comment]
I think so. thank you

**Comment by redrambles** [comment]
Hey @jennwalt,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
