### PR TITLE
my-name.rb file added

### PR DESCRIPTION
**Pull request by dustin-longenecker**

### CODE REVIEW

**Comment by dustin-longenecker** [comment]
Coded over dl-style.css on accident. Caught mistake and re pushed the original file.Should be functioning as original.

**Comment by acodeinprogress** [comment]
Hey @dustin-longenecker,

Looks great! I only have a few small requests for you. 

1) It looks like you have 2 css styles but you'll only need one. It looks like dl-style isn't being used by your HTML so that's the one I would suggest deleting.
2) We would like for your ruby file to be in the ruby folder. 
3) We would love for you to include a link to your advice page in the index.html file.

If you could make those changes, then run git add -A, commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @dustin-longenecker,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @dustin-longenecker,

This is just a reminder that this pull request will close in 10 days if no changes are made.

**Comment by dustin-longenecker** [comment]
Hmmm hello @acodeinprogress ... I had accidently made a change to someone who previously created dl-style and had to correct it back to its original state is maybe why it looks that way. Also my Ruby file is under the ruby folder titled dustin-longenecker.rb. I will add my link to the index.html file and see if it is closer to what you are looking for.

**Comment by dustin-longenecker** [comment]
Ok so I believe I should now have a dustinl-advice.html, dustinl-styles.css, and dustinl.rb file with the correct changes to each. Ignore the dl-advice.html file as I had mistaken it for my own and had to change it back to its original state. Sorry for the mishap. Let me know if I need further editing.

**Comment by acodeinprogress** [comment]
Hey @dustin-longenecker,

That looks good to me! One other request that I have for you is that there seems to be a merge conflict. Would you mind pulling the changes from the skillcrush-104 and fixing the conflicts?

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @dustin-longenecker,

Just another reminder that this pull request will be closed in 20 days if no changes are made.

**Comment by dustin-longenecker** [comment]
Hey @acodeinprogress I believe all the merge conflicts are resolved. Please let me know if anything else needs to be fixed.

Thank you for your patience.

**Comment by acodeinprogress** [comment]
Thanks for making those changes, @dustin-longenecker. Your code is all merged in.

**Pull request merged**
