### PR TITLE
Git commit

### PR DESCRIPTION
**Pull request by littleredtootle**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @littleredtootle,

Looks great! I only have 1 tiny request for you. We would like for your ruby file to be in the ruby folder. If you could move it over there, then run git add -A, commit, then push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by littleredtootle** [comment]
Hi Sharon, thanks for this. Unfortunately I have got a bit confused now -
I've moved the file to the correct folder (I can see the other .rb files),
but now I get an error message when trying to push origin master (screen
shot of terminal error is attached).

I must be in a bit of a tangle - everything else worked OK. Can you please
let me know where I'm going wrong?

Many thanks

Kind regards

Michelle

**Comment by acodeinprogress** [comment]
Hey @littleredtootle,

I don't see that the screenshot is attached. Could you attach it again?

xoxo,
Sharon

**Comment by littleredtootle** [comment]
Hi Sharon, thanks - it's definitely attached in my sent items so I'm not
sure what has happened - here it is again. Here's a copy and paste of the
text too just in case! Thanks

"GeekGirls-MBP:ruby geekgirl$ git status

On branch master

Your branch is ahead of 'origin/master' by 1 commit.

  (use "git push" to publish your local commits)

nothing to commit, working tree clean

GeekGirls-MBP:ruby geekgirl$ git push origin master

Enter passphrase for key '/Users/geekgirl/.ssh/id_rsa':

ERROR: Permission to skillcrush/skillcrush-104.git denied to
littleredtootle.

fatal: Could not read from remote repository.


Please make sure you have the correct access rights

and the repository exists."

I've definitely changed the folder used, so I'm not sure why the
'skillcrush-104' is still coming up as well..!

Many thanks

Kind regards

Michelle

**Comment by acodeinprogress** [comment]
Hey @littleredtootle,

That's odd. I still wasn't able to see the screenshot. But that's ok because you fixed the issue! Thanks for making that change! Your code is all merged in.

xoxo,
Sharon

**Comment by littleredtootle** [comment]
Wonderful - thanks Sharon! Yes, I think I managed to figure it out - wrong
folder - there were a couple of different 'ruby' ones! Thanks for your
help. :)

**Pull request merged**
