### PR TITLE
My personal advice as a rookie!

### PR DESCRIPTION
**Pull request by kvanier2822**
Advice assignment for 105 class. :)

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @kvanier2822,

This looks great! I just have a couple small requests before I merge this in.
1) We would like for you to include a link to your advice page in the index.html file. 
2) It looks like you added your styles to a personal stylesheet and the style.css file. You only need to add them in one place. If you decide to take your styles out of style.css and use your custom stylesheet, you'll also need to update the stylesheet link in your advice file. 

After you make those changes, all you have to do is run a slightly different git command (git add -A), commit, and push and your changes will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by kvanier2822** [comment]
I think I fixed them, but I am not seeing them under commits. Is this because they have to first be approved on your end?

**Comment by acodeinprogress** [comment]
Hey @kvanier2822,

If you're looking at the commits of the skillcrush-104 repo, that's because I have to merge them in. It looks like you merged 'master' into your branch but you didn't update your files by making the requested changes. Did you make sure that you were on your edits branch in your terminal and that you pushed to your edits branch on GitHub?

xoxo,
Sharon

**Comment by kvanier2822** [comment]
So I’ve been working at this a few days and have no idea what to do. So I looked at the edits branch, was getting an error every time I tried to push to edits. I took a screenshot of what I keep getting. Not sure if I should schedule office hours for this lol. Sorry for the confusion!

Khristian

**Comment by kvanier2822** [comment]
Here is the screenshot!

**Comment by acodeinprogress** [comment]
Hey @kvanier2822,

I'm not seeing the attachment. I wonder if it won't go through email. Can you try attaching it through a message on the GitHub site itself? Scheduling office hours would definitely be a great way to get help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @kvanier2822,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 10 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @kvanier2822,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
