### PR TITLE
Larissa's Advice Project

### PR DESCRIPTION
**Pull request by larisschwa**
Hey look I did a thing....I think...

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @larisschwa !

We see your advice page in your pull request - awesome!! Now we just need you to add a little CSS (either to the main stylesheet or to a new custom stylesheet that you create) - and we need one link in the main index.html page that will point to your advice page, so that folks can find your words of wisdom. :)

Once you are done making those small changes, please add and commit and push up your larissa-advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by larisschwa** [comment]
why is it adding the css style under mine in my file?? i'm so confused :(

**Comment by acodeinprogress** [comment]
Hey @larisschwa,

I'm not quite sure that I understand your question. Would you mind giving some more details about your question?

Also, it looks like there's one more step we'll need to take. We'll need to add a link in the main index.html page that will point to your advice page.

xoxo,
Sharon

**Comment by larisschwa** [comment]
I do see that there is a link in the main index.html page pointing to my page. I am not sure what to do at this point then.
screen shot 2018-09-05 at 5 30 25 pm

**Comment by acodeinprogress** [comment]
Hey @larisschwa,

Is it possible that you added your link on a different branch and haven't pushed it to GitHub? In order for your link to show up in this pull request, you'll need to add it on the larissa-advice branch and then push it to that branch on GitHub.

xoxo,
Sharon

**Comment by larisschwa** [comment]
I did accidentally create 2 branches I think. How can I merge the two, and
then push it to github? I thought I did already but apparently not. Thank
you!

**Pull request closed without merging**
