### PR TITLE
First time Forking

### PR DESCRIPTION
**Pull request by abicodes**
Forking challenge!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @abicodes, 

Looks great! I only have 1 tiny request for you. We would like for your ruby files to be in the ruby folder. If you could move them over there, then run git add -A, commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @abicodes,

It looks like your Ruby folder is still in the main directory on GitHub. The way to remove it is to run git add -A, commit, and push.
I also have 2 more requests for you.
1) We'd like for you to include a link to your advice page in the main index.html file.
2) It looks like you're referencing the main style.css in your HTML page but you made a custom css page. You can fix this by either moving your styles to the main style.css page or referencing your custom css page.

Let me know if you need any help!

**Comment by abicodes** [comment]
i) Hi! I do need your help, thanks. The Ruby folder you mean, is it the one I had forked or you mean the ruby_challenges?. I deleted the forked Ruby. If not,  do help me with this challenge commit etc. Where do I put the folder, in a branch? Do you mean I need to commit the ruby_challenges folder again :-(

ii) I added the link to the main index.html
iii) I did add the styles to  style.css... I left the

**Comment by acodeinprogress** [comment]
Hi @abicodes,

It looks like you moved it successfully! Since we're only working with skillcrush-104, we want to move it into the ruby folder that is already inside skillcrush-104, so great job! But it looks like git is still showing your ruby file in the main directory too. All you need to do is run git add -A (don't forget the -A) and it'll remove the file from git. Then you can commit and push!

**Comment by acodeinprogress** [comment]
Thanks for making all those changes, @abicodes! Your code is all merged in.

**Pull request merged**
