### PR TITLE
changed css and index and addedtobo advice

### PR DESCRIPTION
**Pull request by robopingvin**

### CODE REVIEW

**Comment by robopingvin** [comment]
Pull request in progress

**Comment by acodeinprogress** [comment]
Hey @robopingvin,

I noticed that you didn't add an advice page. If you could add that in, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

If no changes are made in 10 days, this pull request will close.

Happy git-ing!
-Sharon

**Comment by robopingvin** [comment]
Okay, I will do it next day, Im sick today. Hope your flu is better!

Happy holidays,
Marko

**Comment by acodeinprogress** [comment]
Hey @robopingvin,

We haven't heard from you in a while so I'm going to close this pull request.

Feel free to open up a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
