### PR TITLE
CSS & HTML for Guthrie S.

### PR DESCRIPTION
**Pull request by Guthrie-S**
Advice from Guthrie

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Guthrie-S !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in.

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Guthrie-S** [comment]
Thanks Ann!

I'll grab that this evening, thank you for the catch!

Cheers,

- Guthrie

**Comment by redrambles** [comment]
Hey @Guthrie-S,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Comment by Guthrie-S** [comment]
Thanks Ann!

Cheers,

- Guthrie

**Pull request merged**
