### PR TITLE
added advice by regina

### PR DESCRIPTION
**Pull request by ginabugac**
I'm trying to get practice with git. I'm not sure why it says can't automatically merge.  I would appreciate any feedback.  Thanks :)

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @ginabugac  !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in.

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by ginabugac** [comment]
I think I figured out what I was doing wrong all along. Hope it's correct this time.

**Comment by redrambles** [comment]
Hey there @ginabugac !

This is really good! There are just a few conflict markers that remain in the main css/style.css stylesheet ([you can see an example here)](https://github.com/skillcrush/skillcrush-104/pull/1706/files#diff-6a6a912d0c7b55b537768da778032849R10056) - such as `>>>>>>>>master` or `HEAD>>>>>>>>>>>`. Once you remove those, add your changes, commit and push up your branch one more time - and we should be all set to merge this in! :)

Let us know if you hit any snags!

**Comment by acodeinprogress** [comment]
Hey @ginabugac,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
