### PR TITLE
added Jubilee file

### PR DESCRIPTION
**Pull request by JubileeBredenberg**

### CODE REVIEW

**Comment by sareg0** [comment]
hi @JubileeBredenberg , I see that you have commited your ruby file to the main directory of the repo. We would like it to be in the 'ruby' folder of the directory.

Could you plus just drag it into the appropriate folder on your computer, then add, commit and push the changes. They should join the pull request here.

Let me know if you need help

**Comment by JubileeBredenberg** [comment]
Hello!
I've moved the jubilee.rb file to the Ruby folder, created and advice file, and added my css to the style file. Please let me know if there are any problems. Thanks!

**Comment by acodeinprogress** [comment]
Hey @JubileeBredenberg! Your ruby file is still showing up in the main directory on GitHub. If it's not showing up there in your local repo, could you try running git add -A, commit, and then push? -A should save it as having been deleted from the main directory.
Thanks! Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @JubileeBredenberg, I went ahead and removed your rb file from the main directory and merged in your changes. Good work!

**Comment by JubileeBredenberg** [comment]
Hello!
I'm so sorry I'm just catching up on emails now. I've been sick for a whole month and got very far behind. Thanks for merging the changes.
Cheers,Jubilee
Date: Sun, 4 Oct 2015 09:29:21 -0700

**Pull request merged**
