### PR TITLE
Advicefromjamieboutilier

### PR DESCRIPTION
**Pull request by jamieboutilier**
I added my link to the index.html

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @jamieboutilier!

This looks great! I just have one small request before we can merge this in.

It looks like you added two advice files (you can see them in the Files Changed tab near the top of the page). We'll need you to remove the extra file.

Once you do that, you'll need to use a slightly different git command (git add -A), then commit, and push. Your changes will join your pull request here and then we can get it merged in..

xoxo,
Sharon

**Comment by jamieboutilier** [comment]
Hi Sharon: I don’t want to remove or do the wrong thing. Would you be able to send me a screenshot or more specific details of what I need to do. Thanks so much.

On Mar 19, 2018, at 11:34 AM, Sharon <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @jamieboutilier<https://github.com/jamieboutilier>!

This looks great! I just have one small request before we can merge this in.

It looks like you added two advice files (you can see them in the Files Changed tab near the top of the page). We'll need you to remove the extra file.

Once you do that, you'll need to use a slightly different git command (git add -A), then commit, and push. Your changes will join your pull request here and then we can get it merged in..

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @jamieboutilier !

No worries! Ok, so what we need to do is remove one file, and then add and commit that change, and push up your branch once more.

1) While still in your 'advicefromjamieboutilier' branch, run:
`rm "advice/boutilier -advice.html"`

2) Then, in order to 'add' this deletion, you would run:
`git add -A`

3) Commit:
`git commit -m "removed extra advice file"`

4) Push up your branch:
`git push origin advicefromjamieboutilier`

This will automatically update this pull request (which is based off of the branch that you just updated and pushed) - so at this point we should be good to merge in your code.

Let us know if you run into any snags or if you have more quesitons!

**Comment by jamieboutilier** [comment]
I think I did this correctly, please let me know if I need to do anything else. Thank you!

On Mar 22, 2018, at 11:24 AM, Ann Cascarano <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @jamieboutilier<https://github.com/jamieboutilier> !

No worries! Ok, so what we need to do is remove one file, and then add and commit that change, and push up your branch once more.

  1.  While still in your 'advicefromjamieboutilier' branch, run:
rm "advice/boutilier -advice.html"

  2.  Then, in order to 'add' this deletion, you would run:
git add -A

  3.  Commit:
git commit -m "removed extra advice file"

  4.  Push up your branch:
git push origin advicefromjamieboutilier

This will automatically update this pull request (which is based off of the branch that you just updated and pushed) - so at this point we should be good to merge in your code.

Let us know if you run into any snags or if you have more quesitons!

**Comment by redrambles** [comment]
Hey @jamieboutilier ! Sorry for the delay!
I just spotted your note but [don't see any changes in this changeset.](https://github.com/skillcrush/skillcrush-104/pull/1693/files). 

Do you remember - while still in your 'advicefromjamieboutilier' branch - deleting the additional advice file and then adding (`git add -A`) and committing (`git commit -m "removed additional advice page"`) that change? If so, all that remains is to push up your branch: 
`git push origin advicefromjamieboutilier` 
and your pull request here will update with your latest changes.

Let us know if you run into any snags! :)

**Comment by redrambles** [comment]
Hey @jamieboutilier,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
