### PR TITLE
Julianexperiments

### PR DESCRIPTION
**Pull request by JulianLucero**
Hello Ann I already made the requested changes!!!

Hey @JulianLucero!

This is almost ready to go - but it looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's. Once you make that change, you can add, commit, and push up your branch once more, which will automatically update your pull request.

Then we should be all set to merge in your code! :)

Let us know if you have any questions!

Cheers,
Ann

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @JulianLucero !

Ok! So I think there may have been a small misunderstanding here. We don't want you to remove other students' CSS **files** - just the other code in **your** custom CSS file that doesn't pertain to your particular advice page. Essentially - you should only have a few lines of CSS in your custom stylesheet - a couple hundred lines at the most, if you made a LOT of CSS changes - and that's it. 

Does that make sense?

So let's rewind back to the state of your previous commit, and go from there.

In the Terminal (or Git Bash) - make sure that you are inside your skillcrush-104 directory and that you have checked out your julianexperiments branch:

`git checkout julianexperiments`

Then we are going to want to roll back in time to when you first made your pull request:

`git reset --hard 0b0e7d3`

Now open up your `css/JulianLucero-style.css` stylesheet - and only keep the code inside it that pertains to your advice page - so only your changes - and then save the file.

Once that is done, run `git status`. Git should have picked up the change in your `css/JulianLucero-style.css` stylesheet. Add (`git add -A`) and commit (`git commit -m "your message here"`) that change.

Next, we will push up your branch once more. Because we rolled back in time - we will need to use a 'force' flag (-f) when we push, to indicate the Git that we know that we are changing history. This can be done safely in this instance because it is happening on a branch that you are submitting for a pull request. You would want to shy away from using a force push in a shared code base - but in this instance it is ok! :)

`git push -f origin julianexperiments`

This will automatically update this pull request - which is based off of your julianexperiments branch - and we should be good to merge in your code.

Keep us posted and let us know how it goes!

Cheers,
Ann

**Comment by JulianLucero** [comment]
Hi Ann!!!
I will try again step by step according your instructions
I will keep you informed

Thanks in advance
Julian

**Comment by acodeinprogress** [comment]
Hey @JulianLucero!

This super close!

It looks like another `skillcrush-104` folder was added to this pull request. If you click on the [Files Changed](https://github.com/skillcrush/skillcrush-104/pull/1983/files) tab near the top of this page, you can see it by scrolling to the bottom of that page.

We'll need for that folder to be removed before we can merge this in. Once you delete it, you'll need to run a slightly different git command (git add -A), then commit and push.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @JulianLucero,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
