### PR TITLE
changes made to krista's advice page

### PR DESCRIPTION
**Pull request by krsfrt**
Changed the advice page!

### CODE REVIEW

**Comment by krsfrt** [comment]
corrected address on index.

**Comment by acodeinprogress** [comment]
Hey @krsfrt,

Looks great! I only have one teensy request for you before I can merge this in.
It looks like you replaced someone else's css with your information in the style page. You can see this highlighted by the pink line if you take a look at the Files Changed tab towards the top of this page. Would you mind re-adding the missing css and then create your own styles?
Once you do that, you can add, commit, and push. Your changes will join your pull request here.
Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @krsfrt,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @krsfrt,

This is just a reminder that this pull request will close in 10 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @krsfrt,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

**Pull request closed without merging**
