### PR TITLE
forked repository was deleted, please close the request

### PR DESCRIPTION
**Pull request by ArcyFlores**
My master and the  origin skillcrush master had no changes, so I had to create a pull request using my advice branch on git hub

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @ArcyFlores,

This looks great! I just have one teensy request before I merge this in.
It looks like you added an images folder and an image. We previously didn't have an images folder because we wanted to keep images out of our repo. If you could remove the image and the folder, that would be great. If you want to include an image, you can host it on an image hosting site and then link to it there.

Once you make that change, you'll run a slightly different git command (git add -A), then commit and merge. Your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @ArcyFlores,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @ArcyFlores,

This is just a reminder that this pull request will close in 7 days if no changes are made.

**Comment by ArcyFlores** [comment]
Sorry about the delay, the image file was removed

**Comment by acodeinprogress** [comment]
Hey @ArcyFlores,

Thanks for making that change! I just have one more request for you.
If you take a look at the Files Changed tab, you'll see that you replaced someone else's link to their advice page with your link. We'd like to include both links so if you could add the missing link back in while keeping yours, that would be great! Then you can add, commit, and push and I'll get your code merged in.

**Comment by acodeinprogress** [comment]
Hey @ArcyFlores,

I can definitely go ahead and close this pull request. Feel free to submit a new one if/when you're ready.

**Pull request closed without merging**
