### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by armieschoch**
Here's my advice - Armie Schoch

### CODE REVIEW

**Comment by redrambles** [comment]
Hello Armie!

Ok! We're nearly there! I think I may have been unclear when I last wrote to you about your pull request. We don't need you to remove all the css **files** that are in the /css folder except for yours - we need you to remove all the styling that is inside your 'armieschoch-advice.style.css' that doesn't relate to your advice page. Taking a look at your file - I can see that the first 40 or so lines of code are yours - everything else has been duplicated from the main css/style.css file - and we don't need it here. Your 'armieschoch-advice.style.css' file should only contain those 40 or so lines of code. 

Here is what I suggest that you do.

**Still in your experiments branch: **

1) In your armieschoch-advice.style.css file - delete everything except for the first 40 or so lines of code which are relevant to your advice page.

2) Move that particular css file onto your Desktop temporarily.

3) Reset your experiments branch to the previous commit - before all those css files were deleted:
`git reset --hard 6c6d50e801`

4) Drag your fixed-up css file from the Desktop back into the project's css/ directory.

5) Make sure that your advice page is linking to your css file.

6) Add and commit your changes - and push! Your pull request here will be automatically updated.

**Comment by armieschoch** [comment]
Hi Ann,

I thought I did this, that means I must have not push it correctly, or something else. I will go back and double check.

Thank you!
Armie

**Comment by armieschoch** [comment]
Ann,

I think I pushed to the master instead of to the experiments branch. I am trying to redo it to push to experiments branch but I got this error (see screenshot)

**Comment by armieschoch** [comment]
-- Please reply above this line --


Hey Armie!

The screenshot doesn't seem to have come through. Can you try sending
it again please? You can also copy/paste the output from the terminal
if that is easier and it doesn't look too messy. 

Let's take it from there!
--
Ann Cascarano
Skillcrush

 DID WE MAKE IT EASY FOR YOU TO GET THE HELP OR INFORMATION YOU
NEEDED?

**Comment by acodeinprogress** [comment]
Hey @armieschoch,

Do you still need help with this pull request or would you like to close it and submit a new one when you're ready?

xoxo,
Sharon

**Comment by armieschoch** [comment]
I am good now with this.

**Comment by acodeinprogress** [comment]
Hey @armieschoch,

Good to hear! I'm not seeing any changes. Did you make sure to push up your edits to experiments branch on GitHub?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @armieschoch,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
