### PR TITLE
my advice page, style page, and index link added

### PR DESCRIPTION
**Pull request by monacojay**
I merged my branch to my master and then used a git revert command to undo that. Switched back to my workBranch and pushed it. Not sure if I did the git'ing correctly. Let me know! Thanks

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @monacojay !

This is great! There is just one file `advice/104-workBranch` that we need you to remove. The other ones are fine! :) Once you have removed that file, you will want to use `git add -A` followed by `git commit -m "your message here"` in order to add and commit that change.

Then, you'll need to push up your topic branch once more:

`git push origin 104-workBranch`

which will automatically update this pull request. At this point, we should be all set to merge in your code. 

Let us know if you have any questions! :)

Cheers,
Ann

**Comment by monacojay** [comment]
Ok I removed the extra file and re-added and committed then merged and pushed back up to the remote at github. 

How do I confirm that it updated the pull request? I see it in the pull request timeline but am wondering are you notified on your end or something?

Thanks!!

**Comment by monacojay** [comment]
Did I even need to create a branch to do this assignment? Am I supposed to merge that branch to my master before pushing?

Tryna figure this out. Thank you!

**Comment by monacojay** [comment]
Conflicts resolved and pushed

**Comment by monacojay** [comment]
@redrambles Hey! Am I good on this? Is there something further I need to do? Did I finish it correctly?

Thanks!

**Comment by acodeinprogress** [comment]
Hey @monacojay,

I don't see any changes on this pull request, which means that you probably didn't make those changes on your branch or you didn't push them up to GitHub.

You'll want to make sure that you make your changes on your 104-workBranch branch and then push them to your 104-workBranch. Then they'll automatically join your pull request here and we can get it merged in.

xoxo,
Sharon

**Comment by monacojay** [comment]
@acodeinprogress Ok how about now? Did I do it right?

**Comment by acodeinprogress** [comment]
Hey @monacojay,

I'm still not seeing any changes. When you ran your git add command, did you make sure to run `git add -A` instead of `git add .`? If you didn't, it won't pick up the deletion of your `104-workBranch` file in the `advice` folder so nothing will be updated.

xoxo,
Sharon

**Comment by monacojay** [comment]
No I’m completely lost. I moved on to the next lesson and will just do this last module over again later. - It’s super hard for me because I have to memorize the entire git directory and all its branches. I can’t “see” it anywhere and get super lost almost immediately. I think I got screwed up with merging. Why would I ever push a branch? Wouldn’t I merge it to my master then push my master? It doesn’t make sense to me why I would synch a branch to an upstream master if I am just going to merge to my local master before I push. If I’m syncing my local branch to an upstream master why do I need a local master? See, completely confused. If I ever do (get) this I’m going to make a class on it because it’s confusing as heck!

**Comment by acodeinprogress** [comment]
Hey @monacojay!

One of the big reasons why we want to use branches is because your main codebase is generally what will get pushed to a live site. Let's say that you're working on a specific feature. You've created a branch for this feature and you've made some changes. You haven't made ALL the changes for that specific feature. If you merge it into your master branch prematurely, you'll have incomplete work that will then go up to the live site. Depending on what you're doing, that could be a big problem, especially if you've introduced a bug.

With branches, we can keep things separate from our main code, which gives us time to test, review, and complete our work while also allowing us to push it up to GitHub during that whole process. Sometimes a feature will take weeks or even months and we definitely don't want to do all that work and not push it up to GitHub.

It's ok if you want to take a break from this assignment. Git is definitely difficult but it's super important. I can go ahead and close this pull request for now and you can reopen a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
