### PR TITLE
SaraC Merges

### PR DESCRIPTION
**Pull request by SaraCanfield**
Added Advise From SaraC Page

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @SaraCanfield,

It looks like there's a merge conflict happening. Do you remember how to resolve this?

**Comment by SaraCanfield** [comment]
I'll check it out.  Thanks!

**Comment by acodeinprogress** [comment]
Hey @SaraCanfield,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by SaraCanfield** [comment]
Hi Sharon. I'll do a re-pull.  Got a bit behind with some ankle surgery issues.  Will catch up.  Thanks

**Comment by SaraCanfield** [comment]
Looks like I have the merge errors resolved.  Is there anything else I need to do or do you push it to the main site?  Thanks.

**Comment by acodeinprogress** [comment]
Hey @SaraCanfield,

No more changes needed! That's perfect! Your code is all merged in now. Great job!

**Pull request merged**
