### PR TITLE
helloooo

### PR DESCRIPTION
**Pull request by db44**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @db44,

Great work! I only have 1 tiny request for you. We would like for your ruby file to be in the ruby folder. If you could move it over there, then run git add -A, commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by db44** [comment]
Hi, 

I'm not sure which file you mean. Can you include exact file name, current location, and requested location? 

Thank you.

David

**Comment by acodeinprogress** [comment]
Hi @db44,

I'm referring to your david.rb file. It is in the main skillcrush-104 directory. If you take a look, there is a ruby folder in that directory. We would like for you to move your david.rb file into the ruby folder. Then run git add -A, commit, and push. Your changes will join your pull request here and then I can get it merged in.

**Comment by db44** [comment]
Ok. Thank you. Still trying to get the hang of this.

**Comment by acodeinprogress** [comment]
Thanks so much for making those changes, @db44! Your code is all merged in.

**Pull request merged**
