### PR TITLE
V2.0 John added advice

### PR DESCRIPTION
**Pull request by Grindfixer**
Some things I learned long ago, and have applied to learning code.

### CODE REVIEW

**Comment by Grindfixer** [comment]
This is my first time with version control of any kind. It can be a little confusing

**Comment by Grindfixer** [comment]
oops I pushed the wrong button the first time. Not sure if I did all this correctly

**Comment by Grindfixer** [comment]
Added added my advice and style sheet. Hope i click the right button this time.

**Comment by acodeinprogress** [comment]
Hey @Grindfixer,

So sorry for the delay! You did a great job and your code is all merged in! Yay!

xoxo,
Sharon

**Pull request merged**
