### PR TITLE
created my own advice page

### PR DESCRIPTION
**Pull request by momahony87**
styled up my very own advice page!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @momahony87,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @momahony87,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 20 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @momahony87,

We still haven't heard from you. If no changes are made in 10 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by momahony87** [comment]
Hey Sharon,

So sorry I haven’t gotten this done. I’ve got some time now to go fix the issue. Thanks for checking in via email… These busy summer days have me forgetting a lot of things!

Thanks again,
Maureen

**Comment by acodeinprogress** [comment]
Hey @momahony87,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
