### PR TITLE
Arletta Added Advice(Alliteration)

### PR DESCRIPTION
**Pull request by Rani-Lioness**
Just some advice from my heart!

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Rani-Lioness!

Nice work!! This is almost ready to go - but it looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet (css/arlettasstyle.css). All you need in there are your personal styles, so you can remove everyone else's. 

You'll also want to make sure that you are linking to your custom stylesheet from your advice page - right now you're linking to the main stylesheet (css/style.css). 

Once you make those changes, you can add (`git add -A`), commit (`git commit -m "your message here"`), and push (`git push origin practice-makies-perfect`) and it'll join your pull request here. :)

Let us know if you have any questions!

Cheers,
Ann

**Comment by Rani-Lioness** [comment]
Thank you so much! I’ll do just that!

**Comment by Rani-Lioness** [comment]
So I did all the steps you said, went back and tried to push it, but when I
refresh the page there are still no files to be seen.. what am I missing
here? Thanks in advance!

**Comment by redrambles** [comment]
Hey @Rani-Lioness !

Ok!

1) Double check that you are indeed in your 'practice-makes-perfect' branch
2) Double check that you have added your changes (run `git status` to make sure) - if not, add them with `git add -A` and then commit again `git commit -m "your message here"`
3) Make sure that you've pushed up your 'practice-makes-perfect' branch, and not your 'master' branch `git push origin practice-makes-perfect`

Does that help?

**Comment by Rani-Lioness** [comment]
Will I need to submit a new pull request with the updates you suggested before?

**Comment by redrambles** [comment]
Hey @Rani-Lioness !

Ok! Looks like your 'practice-makes-perfect' branch contains some commits that you do not have locally. Do you remember editing something directly on GitHub? 
In any case - we can totally work with this - you won't need to create a new pull request.

So! The first thing I'd like you to make sure of is that you are indeed in your 'practice-makes-perfect' branch. You can double check that by running 'git status' - it will be the first line of info you get from running that command. If you aren't on that branch, move to it by running `git checkout practice-makes-perfect`

Once you are on this branch - let's create another branch just for safekeeping, by running:
`git branch practice2`

This will create a new branch which will essentially be a copy of your 'practice-makes-perfect' branch - just in case we need it - but it isn't moving you to that other branch. We are just creating it. If you run `git status` you will see that you are still on your 'practice-makes-perfect' branch.

Ok! So now - let's fetch from your origin repository:
`git fetch origin`

And then let's merge in your 'practice-makes-perfect' branch which contains that change that isn't present locally:
`git merge origin/practice-makes-perfect`

Then let's push up your branch once more:

`git push origin practice-makes-perfect`

This time there shouldn't be any problem, given that your branch will be up to date with its remote counterpart.

Let us know how this goes - and feel free to drop by office hours if you'd like to chat more about this and other Git things!

**Comment by Rani-Lioness** [comment]
I appreciate all of your help so much, but honestly i think I will just
have to begin again because I still was receiving an error. Plus, I think I
had too much of a gap in between my learning because I started in my last
trimester and then was out of the game for three months so I am just going
to start from scratch! I need to actually understand where and why i'm
doing things so that I feel comfortable working on projects. Thank you
again for continuing to try and work with me through this though! Your
patience is astounding! 🤗

**Comment by acodeinprogress** [comment]
Hey @Rani-Lioness!

If you'd prefer to start over, that is totally fine! Would you like me to close this pull request? Or, if you'd like, you can even close it yourself! 

xoxo,
Sharon

**Comment by Rani-Lioness** [comment]
I'd like to try to close it myself if I could! How do I do that?

**Pull request closed without merging**
