### PR TITLE
debbies changes

### PR DESCRIPTION
**Pull request by CityGirlDebbie**
updated html and css with my changes

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @CityGirlDebbie,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by CityGirlDebbie** [comment]
Hi Sharon

Thank you for the message. I just updated and believe I have done the necessary updates and pushed the changes to the repo. Please review and let me know how it looks.

Thank you,
Debbie

**Comment by acodeinprogress** [comment]
Hey @CityGirlDebbie!

Thanks for making those changes! There are just a couple more things that we'll need to do before this can merged in:
1. There are a few conflict markers that need to be removed. Check out the index.html file in your pull request by clicking on the [Files Changed](https://github.com/skillcrush/skillcrush-104/pull/1876/files) tab - do you see the <<<<<<< HEAD, ======== and master >>>>>>> ? Those are conflict markers that are useful indicators while we are merging, but shouldn't be left in the code.

2. If you take a look at the style.css file using that same Files Changed tab, you'll see that another student's styles was replaced by your styles. You'll need to add that student's styles back in as well.

Once you make those changes, you can add, commit, and push like you did last time!

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @CityGirlDebbie,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Comment by CityGirlDebbie** [comment]
Good idea. I have had other distractions and would like to start this portion over again so that the whole process is refreshed in my mind, and the assignment is done correctly.

Thank you for the email!
Debbie

On Jun 18, 2018, at 2:01 PM, Ann Cascarano <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @CityGirlDebbie<https://github.com/CityGirlDebbie>,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
