### PR TITLE
chiu-test-hello.rb

### PR DESCRIPTION
**Pull request by chiukwok**
Test successful!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @chiukwok,

Looks great! I only have 1 tiny request for you. We would like for your ruby file to be in the ruby folder. If you could move it over there, then run a slightly different git command (git add -A), commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by chiukwok** [comment]
Added advice page per Lesson 24 Challenge!

**Comment by chiukwok** [comment]
Moved file as per requested

**Comment by acodeinprogress** [comment]
Hey @chiukwok,

Thanks for adding your file to the ruby folder. GitHub is still showing that your file is also in the main directory. If you could remove that and then run git add -A, commit, and push, that would be great!

**Comment by acodeinprogress** [comment]
Hey @chiukwok,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 17 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @chiukwok,

This is just a reminder that this pull request will close in 9 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @chiukwok,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

**Pull request closed without merging**
