### PR TITLE
Added advice!

### PR DESCRIPTION
**Pull request by michelleluix**
I deleted everyone else's css in my own css file and added a link for my own advice onto the html file.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @michelleluix!

Nice work! We just need you to make a few changes before we are able to commit this.

In the **css/styles.css** file and inside the main **index.html** file, there are some conflict markers, such as (+<<<<<<< HEAD) or (+=======) or (+>>>>>>> master) which we need you to remove. You can see exactly where they are by looking at the details of your commit, [here](https://github.com/skillcrush/skillcrush-104/compare/master...michelleluix:mlui). 

Once you have made those changes, please add (git add -A) and commit (git commit -m "your message here") and then push up your branch (git push origin mlui), which will automatically update your pull request. 

Once that is done, we should be able to merge in your code! Let us know if you have any questions!!

**Comment by michelleluix** [comment]
Hi @redrambles !

I think I fixed the conflict markers! Quick question: what usually adds the conflict markers into the code? I'm pretty certain I didn't add anything to other peoples' sections-- is this something that is added by GitHub when it senses a conflict between branches?

Thank you!!

**Comment by acodeinprogress** [comment]
Hey @michelleluix,

You're super close! It looks like there's one last conflict marker on line 53.

GitHub doesn't add them but Git does when there's a conflict. It does this locally on your computer and will normally notify you that there's a merge conflict. In order to fix the merge conflict, you have to manually go in and remove all the markers.

Happy git-ing!
-Sharon

**Comment by michelleluix** [comment]
I'm trying to resolve the conflict, but the last section of css is stumping me! It doesn't show up on the version of the css I am working on, but that is where the conflict is. How can I fix this?

**Comment by acodeinprogress** [comment]
Hey @michelleluix,

You got this! It's all fixed up. Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Sharon

**Pull request merged**
