### PR TITLE
Rob S's advice page

### PR DESCRIPTION
**Pull request by SirUncleCid**

### CODE REVIEW

**Comment by sareg0** [comment]
hi @SirUncleCid I see that you are committing a few extra files in your commit no. a6799cb

Could you clarify how that came about?

I may have to close the pull request and have you take another stab at it, and just make sure aren't pushing files that already exist back into the repo.

**Comment by SirUncleCid** [comment]
That Ruby file, I noticed, is extra, but none of the other files are out of the ordinary from the lesson 24 of the Ruby, Git & Command Line class.  

If you'd like me to remove the empty file (he snuck in there) and recommit, I will do that.

**Comment by SirUncleCid** [comment]
Actually, looking at that now, I'm not even sure how that happened.

**Comment by SirUncleCid** [comment]
https://github.com/skillcrush/skillcrush-104/commit/a6799cb9c391f2ef245c12fe72157a7f0015a417
Is all I really wanted to commit.

**Comment by sareg0** [comment]
Hey @SirUncleCid ok, well how about I close this pull request and you take another stab at it, and try to make sure that those extra files don't get committed. 

It may have been that you were copying a few files to use for your own advice page, and css, and those were duplicated and pushed up.

Just FYI your advice and css pages, as well as your ruby file commit (357165f and ea41d65) are perfect! It's just that middle one that is the problem. 

I'll close, but I look forward to seeing another pull request soon!

**Pull request closed without merging**
