### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by kytrangho**
I added five tips for prospective Skillcrushers and added color to the headlines, list headings and paragraphs.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @kytrangho,

It looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's. Once you make that change, you can add, commit, and push and it'll join your pull request here.

Let me know if you need any help.

**Comment by kytrangho** [comment]
Hi Sharon,

I don't understand what I did wrong. I made changes, committed them and
merged with the upstream file. But when I submit, it says there is nothing
to compare. What am I doing wrong. Here is all of command line operations.

Last login: Mon Sep 19 08:12:38 on ttys000

ky: ~

♥ cd

ky: ~

♥ cd desktop my-skillcrush.repo

ky: desktop

♥ cd my-skillcrush.repo

ky: my-skillcrush.repo

♥ git checkout kytrangho-branch

Switched to branch 'kytrangho-branch'

ky: my-skillcrush.repo

♥ git add kytrangho-style.css

fatal: pathspec 'kytrangho-style.css' did not match any files

ky: my-skillcrush.repo

♥ git add .

ky: my-skillcrush.repo

♥ git add css/kytrangho-style.css

ky: my-skillcrush.repo

♥ git commit -m "took out everyone else's code"

On branch kytrangho-branch

nothing to commit, working directory clean

ky: my-skillcrush.repo

♥ git push origin master

Everything up-to-date

ky: my-skillcrush.repo

♥ git push origin kytrangho-branch

Everything up-to-date

ky: my-skillcrush.repo

♥ git remote -v

github https://github.com/skillcrush/skillcrush-104 (fetch)

github https://github.com/skillcrush/skillcrush-104 (push)

origin https://github.com/kytrangho/skillcrush-104.git (fetch)

origin https://github.com/kytrangho/skillcrush-104.git (push)

upstream git@github.com:skillcrush/skillcrush-104.git (fetch)

upstream git@github.com:skillcrush/skillcrush-104.git (push)

ky: my-skillcrush.repo

♥ git remote rm kytrangho-branch

error: Could not remove config section 'remote.kytrangho-branch'

ky: my-skillcrush.repo

♥ git status

On branch kytrangho-branch

nothing to commit, working directory clean

ky: my-skillcrush.repo

♥ git push origin master

Everything up-to-date

ky: my-skillcrush.repo

♥ git status

On branch kytrangho-branch

Changes not staged for commit:

  (use "git add <file>..." to update what will be committed)

  (use "git checkout -- <file>..." to discard changes in working directory)


modified:   advice/kytrangho-advice.html

modified:   css/kytrangho-style.css


no changes added to commit (use "git add" and/or "git commit -a")

ky: my-skillcrush.repo

♥ git add .

ky: my-skillcrush.repo

♥ git status

On branch kytrangho-branch

Changes to be committed:

  (use "git reset HEAD <file>..." to unstage)


modified:   advice/kytrangho-advice.html

modified:   css/kytrangho-style.css


ky: my-skillcrush.repo

♥ git commit -m"added another piece of advice and rounded corners on
subheds."

[kytrangho-branch 8be3847] added another piece of advice and rounded
corners on subheds.

 2 files changed, 4 insertions(+), 3 deletions(-)

ky: my-skillcrush.repo

♥ git status

On branch kytrangho-branch

nothing to commit, working directory clean

ky: my-skillcrush.repo

♥ git push origin master

Everything up-to-date

ky: my-skillcrush.repo

♥ git push origin kytrangho-branch

Counting objects: 6, done.

Delta compression using up to 2 threads.

Compressing objects: 100% (6/6), done.

Writing objects: 100% (6/6), 796 bytes | 0 bytes/s, done.

Total 6 (delta 5), reused 0 (delta 0)

remote: Resolving deltas: 100% (5/5), completed with 5 local objects.

To https://github.com/kytrangho/skillcrush-104.git

   ad79676..8be3847  kytrangho-branch -> kytrangho-branch

ky: my-skillcrush.repo

♥ git remote add upstream

usage: git remote add [<options>] <name> <url>


    -f, --fetch           fetch the remote branches

    --tags                import all tags and associated objects when
fetching

                          or do not fetch any tag at all (--no-tags)

    -t, --track <branch>  branch(es) to track

    -m, --master <branch>

                          master branch

    --mirror[=<push|fetch>]

                          set up remote as a mirror to push to or fetch from


ky: my-skillcrush.repo

♥ git checkout master

Switched to branch 'master'

Your branch is up-to-date with 'origin/master'.

ky: my-skillcrush.repo

♥ git fetch upstream

Saving password to keychain failed

Saving password to keychain failed

Permission denied (publickey).

fatal: Could not read from remote repository.


Please make sure you have the correct access rights

and the repository exists.

ky: my-skillcrush.repo

♥ git fetch upstream

Saving password to keychain failed

Saving password to keychain failed

Permission denied (publickey).

fatal: Could not read from remote repository.


Please make sure you have the correct access rights

and the repository exists.

ky: my-skillcrush.repo

♥ git merge upstream/master

merge: upstream/master - not something we can merge

ky: my-skillcrush.repo

♥ git merge upstream/kytrangho-branch

merge: upstream/kytrangho-branch - not something we can merge

ky: my-skillcrush.repo

♥ git merge kytrangho-branch/master

merge: kytrangho-branch/master - not something we can merge

ky: my-skillcrush.repo

♥ git push origin kytrangho-branch

Everything up-to-date

ky: my-skillcrush.repo

♥ git commit

On branch master

Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean

ky: my-skillcrush.repo

♥

With gratitude and unconditional love,

Ky Trang Ho
Forbes Contributor -- Investing <http://www.forbes.com/sites/trangho/>
Financial News Media Consultant

KeyFinancialMedia.com <http://keyfinancialmedia.com/>
ky@keyfinancialmedia.com
323-875-7789

*@KyTrangHo* <http://twitter.com/kytrangho>
*Facebook* <https://www.facebook.com/trang.ho.775>
*LinkedIn <https://www.linkedin.com/in/kytrangho>*
Google+ <http://google.com/+KyTrangHoKFM>

*kytrangho.com <http://kytrangho.com/>*
*Quora* <https://www.quora.com/profile/Ky-Trang-Ho-1>
*Clarity.fm* <https://clarity.fm/kytrang-ho>

   -

**Comment by kytrangho** [comment]
​Nevermind my previous email. I think I got it to work!​

With gratitude and unconditional love,

Ky Trang Ho
Forbes Contributor -- Investing <http://www.forbes.com/sites/trangho/>
Financial News Media Consultant

KeyFinancialMedia.com <http://keyfinancialmedia.com/>
ky@keyfinancialmedia.com
323-875-7789

*@KyTrangHo* <http://twitter.com/kytrangho>
*Facebook* <https://www.facebook.com/trang.ho.775>
*LinkedIn <https://www.linkedin.com/in/kytrangho>*
Google+ <http://google.com/+KyTrangHoKFM>

*kytrangho.com <http://kytrangho.com/>*
*Quora* <https://www.quora.com/profile/Ky-Trang-Ho-1>
*Clarity.fm* <https://clarity.fm/kytrang-ho>

   -

**Comment by acodeinprogress** [comment]
Great work, @kytrangho! Your code is all merged in.

**Pull request merged**
