### PR TITLE
advice html and css pages

### PR DESCRIPTION
**Pull request by lmallpress**

### CODE REVIEW

**Comment by lmallpress** [comment]
I am submitting a pull request for my advice html and css pages.

**Comment by acodeinprogress** [comment]
Hey @lmallpress,

This looks great! I just have one teensy request for you. It looks like you added everyone's styles to your personal stylesheet. Since only your page will be accessing your stylesheet, you only need to include your personal styles. Once you fix that, you can add, commit, and push and your changes will join your pull request here.

Let me know if you need any help!

**Comment by lmallpress** [comment]
Hi Sharon,

Thank you for this. I've deleted my repo and am starting over, but I'm
confused as the directions state not to change anyone else's styles and it
looks like everyone added their own to the css file.  Based on what you are
telling me, I assume that I will be deleting everyone else's from the css
page and only keeping mine?

**Comment by lmallpress** [comment]
Scratch that. I get it. Just needed to dust out the cobwebs. Thank you!

**Pull request closed without merging**
