### PR TITLE
git here you go

### PR DESCRIPTION
**Pull request by espringer1**
Here is my pull request.
Thanks,
Eric Springer

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @espringer1,

I was hoping that you could make a couple changes before I merge this in.
1) It looks like you added all the styles from the main style.css file into your personal css file. Instead, could you edit it so that only your personal style changes are in there?
2) Could you add a link to your html page in the main index.html file?

Once you do that, you can add, commit, then push. Your changes will join your pull request here.

Let me know if you need any help!

**Comment by espringer1** [comment]
I made the updates. Please accept the pull request. Thanks. Eric

**Comment by acodeinprogress** [comment]
Hey @espringer1,

Thanks for making that change! It looks like you still have all the css from the style.css folder. All you need in your personal css file is your custom css. If you could remove everything except for your custom css, that would be fantastic. Then all you'll have to do is add, commit, then push and I'll be able to merge your changes.

**Comment by espringer1** [comment]
I deleted the other .css files in my css folder on my local repository, so it shows only ericspringer.css in that folder. Then I added, committed, and pushed the entire folder to github. Is that all I have to do?

**Comment by acodeinprogress** [comment]
Hey @espringer1,

Looking great! I just have 1 more minor change for you to make. It looks like you deleted someone else's css file (css/Linds-Advice.css). Could you please put that back in then add, commit, and push. Once that's done, it'll be perfect and I can get it merged in!

**Comment by acodeinprogress** [comment]
Hey @espringer1,

It looks like there is still a file missing and we haven't heard from you in a bit. I want to let you know that this pull request will be closed in 20 days if no changes are made. Again, I'd be happy to help!

**Comment by acodeinprogress** [comment]
Hey @espringer1, just a reminder that this pull request will be closed in 10 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @espringer1,

This pull request is now closed. Feel free to open up a new one when you're ready! :)

**Pull request closed without merging**
