### PR TITLE
Adding my advice page 

### PR DESCRIPTION
**Pull request by pattilouhoo**
adding advice page

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @pattilouhoo,

Looks great! I only have 1 tiny request for you. We would like for your ruby file to be in the ruby folder. If you could move it over there, then run git add -A (don't forget the -A), commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by pattilouhoo** [comment]
Hi Sharon,
I see, ok. So I moved it locally, added file and committed changes in git. I went to push it, but of course, I got an error as I pushed to the master. How do I push it to my own fork to add it to the existing pull request?

**Comment by acodeinprogress** [comment]
Hey @pattilouhoo,

Could you share a screenshot of the error you're getting? Also, if you type **git remote -v**, what is the output?

**Comment by acodeinprogress** [comment]
Hey @pattilouhoo,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @pattilouhoo,

This is just a reminder that this pull request will close in 9 days if no changes are made.

**Comment by pattilouhoo** [comment]
Ok - my apologies. I’ve not been able to attend class for the past several weeks due to a personal matter. 
Thanks for the reminder - I am not sure I remember what this request is for now but I’ll try to take a look this weekend.

**Comment by acodeinprogress** [comment]
Hey @pattilouhoo,

It's been a while since we heard from you and no changes have been made, so this is a reminder that this pull request will be closed in 10 days.

**Comment by acodeinprogress** [comment]
Hey @pattilouhoo,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

**Pull request closed without merging**
