### PR TITLE
advice update

### PR DESCRIPTION
**Pull request by lisaak**
my pull request

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @lisaak,

Great work! I only have 1 tiny request for you.
Your personal stylesheet has a bunch of styles for elements that don't exist on your page, such as .nav.
If you could remove the extra stylings then add, commit, and push, your changes will join your pull request here. 

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @lisaak,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by lisaak** [comment]
Hi Sharon, 
Sorry - I forgot that I needed to fix this. 
I'm trying to make a pull request with a new css file, but I'm getting this message on Github  Can’t automatically merge. Don’t worry, you can still create the pull request.
And I'm not seeing a Pull request button. Do you know why this might be happening?
Thanks,Lisa

**Comment by acodeinprogress** [comment]
Hey @lisaak,

You won't see a pull request button because you've already created a pull request. You'll need to update your local repo to include the updates made to the skillcrush-104 repo. and you'll also need to merge your branch into master. Once you do that, it might show a merge conflict, which you'll need to fix. Then you may need to open up a new pull request for your master branch.
Let me know if you run into any trouble!

**Comment by acodeinprogress** [comment]
Hey @lisaak,

Just another reminder that this will be closed in 20 days if no changes are made.
Again, let me know if you need any help! :)

**Comment by acodeinprogress** [comment]
Hey @lisaak,

This is just a reminder that this pull request will close in 10 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @lisaak,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

**Pull request closed without merging**
