### PR TITLE
Martin J Advice Step5

### PR DESCRIPTION
**Pull request by MJ3132**
Deleted martinj-advice.css

### CODE REVIEW

**Comment by MJ3132** [comment]
These is my advice that I would five future students, let me know what you think!

**Comment by acodeinprogress** [comment]
Hey @MJ3132,

This looks great so far! I have a teensy request before we can merge this in.

It looks like you added personal stylesheet on top of adding your styles to the style.css stylesheet. If you could go ahead and delete that extra stylesheet, that would be great. Once you do that, you can run a slightly different git command (git add -A), commit, and push. Your changes will join your pull request here.

If no changes are made in 10 days, this pull request will close.

Happy git-ing,
Sharon

**Comment by acodeinprogress** [comment]
Hey @MJ3132,

Thanks for making that change! It looks like you also deleted a link to someone else's advice page in the index.html file.

You can see which line was deleted by looking at the Files Changed tab near the top of this page.

If you could add that in, that would be great! Then you can add, commit, and push your code and it will join your pull request here again.

xoxo,
Sharon

**Comment by MJ3132** [comment]
Hey sharon,

I dont know what happened, i changed the index.html added the person I accidentally deleted (link), then i commited and pushed my code, but when i check in my github account for any changes i doesnt know , it shows another Martin contributed to some changes. Then I go to look in my batch and click git status, and it tells me there arent new commits . I am puzzled why i cant see my new commit in github.Please help.

**Comment by acodeinprogress** [comment]
Hey @MJ3132,

It looks like you ran your normal git add instead of **git add -A**. Try running that again then commit and push and see what happens!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @MJ3132,

It's been a while since we've heard from you so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
