### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by PeggyJMatthews**
practice

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @PeggyJMatthews,

This looks great so far! I just have a couple small requests before we can merge this in:
1) I see that you added an image to the project. We like to keep our repository as simple and clean as possible so we cannot accept images. You can host the image online and then include a link in your code to the image. Then you'll want to delete the image file and the images folder from this repo.
2) You added your advice file to the .gitignore file. Instead, we want to take that out so that your advice file shows up in this repo! :)

Once you make those changes, you'll want to run a slightly different git command (git add -A), commit, and push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by PeggyJMatthews** [comment]
how do I get the advice file out of the .gitignorefile? Then how do I get
it to show up in the repo?
I am just going to take my image completely out.

**Comment by acodeinprogress** [comment]
Hey @PeggyJMatthews,

You'll want to open up the `.gitignore` file in your text editor and then remove the line that says `advice/peggymatthews-advice.html`.

Once you make your changes, you'll want to run `git add -A`, then commit and push and your changes will show up here.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @PeggyJMatthews,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
