### PR TITLE
My advice

### PR DESCRIPTION
**Pull request by baronkarza23**
here is my submission of my advice added.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @baronkarza23,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file and a custom stylesheet. If you could add those in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

Let us know if you need any help!

xoxo,
Sharon

**Comment by baronkarza23** [comment]
Oops, missed adding those updated files.

**Comment by baronkarza23** [comment]
Looks like I have them in there now.  Thank you Sharon, have a great weekend!

**Comment by acodeinprogress** [comment]
Hey @baronkarza23,

Thanks for making that change! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
