### PR TITLE
added my advice & style

### PR DESCRIPTION
**Pull request by rudy42**
Added some advice & style

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @rudy42,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by rudy42** [comment]
I added the link.  Added, committed and pushed the changes.....I am not sure if I did everything right, so let me know.  Thanks!!

**Comment by acodeinprogress** [comment]
Hey @rudy42,

I'm not seeing any changes. Did you make sure to make the changes on your experiments branch on your local repo and then push to your experiments branch on GitHub?

xoxo,
Sharon

**Comment by rudy42** [comment]
Hi there - 
I tried it again and it shows that there is 2 commits now to review, so crossing my fingers that I did it right.  However, I see that I have a conflict.  But, since I only have Read Access, I can't resolve it, can I?  Sorry, this is all very confusing to me.....
Thanks,
Julie

**Comment by acodeinprogress** [comment]
Hey @rudy42,

Great job! Thanks for making that change! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
