### PR TITLE
added gtknowls advice in html, css but not ruby

### PR DESCRIPTION
**Pull request by GTKnowls**
I was not sure what to edit without messing other students hard work up... so.... I created my own advice html/css document, and added the link on the index.html page. I don't know ruby (yet) - that was the only file I did not contribute a file. Thank you!!!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @GTKnowls,

We would prefer not to use outside stylesheets. If there are specific files from the normalize stylesheet, you're welcome to include them in your personal stylesheet. If you could remove the normalize stylesheet, that would be great. Then run **git add -A**, commit, and push. Your changes will join your pull request here.

Let me know if you need any help!

**Comment by GTKnowls** [comment]
Deleted normalize and added with -A, committed & merged - Thank you

**Comment by GTKnowls** [comment]
I merged files with the -A as prompted, I don't see the merge (?)  
image
first-merge-step

**Comment by GTKnowls** [comment]
Hi Sharon! 
Please help - I am unsure how to track/find why my changes did not appear on the github but did on my end when I opened the explorer . while in the master. I had no merge errors. I sent a message on pull request - but I see you have lots of them now, so I know you are a busy gal. I looked up that -A updates the index as well. very nice. This is used when you have additional links to index pages such as this? 
Please advise…. 

Also - Thank you so much for your patience! Big hug - Tess

**Comment by acodeinprogress** [comment]
Hey @GTKnowls,

It looks like you pushed up your master branch. All you need to do is go to your experiments branch, remove the normalize file, and then run git add -A (still on the experiments branch). Then you can commit and push.

**Comment by acodeinprogress** [comment]
Hey @GTKnowls,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by GTKnowls** [comment]
Hi @acodeinprogress I believe I did it correctly this time.

**Comment by acodeinprogress** [comment]
Hey @GTKnowls,

This is VERY close! It's totally fine to add a personal css stylesheet. But as for the normalize stylesheet, that is an outside resource that we'd like to keep out of the project. If you could move your css back to your gtknowls-stylesheet.css file, that would be great. Also, remember that the href directs to the file in relation to where we are. So if we are in advice/advice-file.html and our css file is in css/css-file.css, our link would need to go up a directory and then into the css folder.

Again, let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @GTKnowls,

Thanks for making all those changes! Your code is all merged in.

**Pull request merged**
