### PR TITLE
Trish advice branch

### PR DESCRIPTION
**Pull request by pkisinger**
Trish added her two cents.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @pkisinger,

I noticed that you didn't add any css. It also looks like your html page is missing the .html extension, so instead of advice-by-trisha, it should be advice-by-trisha.html. If you could add those things, that would be great! Once you do that, you can run a slightly different git command (git add -A), commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by pkisinger** [comment]
Where in the directory would I run the 'git add -A' command? I don't want to accidentally add a bunch of files that don't need to be added. I fixed the .html file and sorted out the .css file. I just added styles to the larger style.css file with my class name and forgot to add it to the repository. Should I create my own separate .css file? There's a merge conflict that I'm having trouble understanding.

**Comment by acodeinprogress** [comment]
Hey @pkisinger,

You're very close! Thanks for adding that html file! Now what you'll need to do is delete the old one and instead of running **git add .**, you'll do **git add -A**. That command says to delete the file from your repo whereas **git add .** doesn't recognize deleted files so it won't actually delete them from your repo. Don't worry, the file will still be in previous commits if you ever need it. Then you can commit and push!

xoxo,
Sharon

**Comment by pkisinger** [comment]
Alright! I have non HTML file deleted and committed and pushed. Do I need to sum it a new pull request? It's still showing merge conflicts?

**Comment by acodeinprogress** [comment]
Hey @pkisinger,

Thanks for making that change! and extra thanks for merging master into your code! It's all merged in. Yay!

xoxo,
Sharon

**Pull request merged**
