### PR TITLE
edited Shannon file

### PR DESCRIPTION
**Pull request by sawoodward**

### CODE REVIEW

**Comment by sareg0** [comment]
hi @sawoodward, I see that you have commited your ruby file to the main directory of the repo. We would like it to be in the 'ruby' folder of the directory.

Could you plus just drag it into the appropriate folder on your computer, then add, commit and push the changes. They should join the pull request here.

Let me know if you need help

**Comment by sawoodward** [comment]
Hi Sara,

I think I did it correctly this time. Please let me know if that’s not the case.

Thanks!

**Comment by acodeinprogress** [comment]
Hey @sawoodward, it looks like the file is still in the main directory. Could you move it to your ruby folder, then run git add -A, commit, and then push? Then I'll go ahead and get it merged in. Let me know if you have any trouble with this! :)

**Comment by sawoodward** [comment]
Hi there,

When I logged into GitHub, it shows my file, shannon-woodward.rb, is in the ruby folder:


If this is incorrect, can you please walk me through correcting it? It’s been a while since I’ve done this and could use a refresher.

Thanks!

**Comment by acodeinprogress** [comment]
Hey @sawoodward! So it looks like this is from an old repo that was deleted. You submitted a new pull request from your updated repo and I already merged that in. I'm going to go ahead and close this issue. Sorry for the confusion!

**Pull request closed without merging**
