### PR TITLE
I added a new file which I think you may like.

### PR DESCRIPTION
**Pull request by adriculous**
Please check it out and let me know what you think! :)

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @adriculous,

Awesome! I only have 1 tiny request for you. We would like for your ruby file to be in the ruby folder. If you could move it over there, then run git add -A (don't forget the -A), commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by adriculous** [comment]
I misunderstood the assignment. I didn't realize that the instructions were talking about the ruby folder inside the skillcrush-104 repo. I moved/pushed it there now. :)

**Comment by acodeinprogress** [comment]
Hey @adriculous,

That's totally ok! Would you mind removing your old file (the one in the main directory) and running **git add -A**, then commit and push?

**Comment by acodeinprogress** [comment]
Hey @adriculous,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @adriculous,

This is just a reminder that this pull request will close in 10 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @adriculous,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

**Pull request closed without merging**
