### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by baconsizzle6**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @baconsizzle6,

This looks great! I just have one teensy request before I merge this in. It looks like you added everyone's styles to your personal stylesheet. Since only your page will be accessing your stylesheet, you only need your personal styles. Once you fix that, you can add, commit, and push and your changes will join your pull request here.

Let me know if you need any help!

**Comment by baconsizzle6** [comment]
Thanks, I didn't realize I'd done that. Is this correct now?

**Comment by acodeinprogress** [comment]
Hey @baconsizzle6,

Thanks for making that change. It looks like you have a couple extra files with a different name present in your pull request. They are under the name kyleighknight. If you could remove those then run a slightly different git command (git add -A), then commit and push, that would be great.

**Comment by acodeinprogress** [comment]
Hey @baconsizzle6,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by baconsizzle6** [comment]
Thanks. I got super busy, I'll try to fix the changes before it closes.

**Comment by baconsizzle6** [comment]
I'm not sure how to remove this file. I'm really confused

**Comment by acodeinprogress** [comment]
Hey @baconsizzle6,

All you have to do is go to your skillcrush-104 folder and remove those files. Then go to your terminal and run **git add -A**. Those will remove those files from git. Then you can commit and push.

**Comment by baconsizzle6** [comment]
Oh thanks! Hopefully, this will finally work.

**Comment by acodeinprogress** [comment]
Hey @baconsizzle6,

If you take a look at the Files Changed tab, it says that you altered 525 files. Based on the first few files, it looks like you deleted everyone's advice page. I would suggest pulling down the master branch in order to get all those files back.

**Comment by baconsizzle6** [comment]
Is it correct now?

**Comment by acodeinprogress** [comment]
Hey @baconsizzle6,

Unfortunately, all the files were somehow modified. I would suggest closing this pull request and trying to fork the repo again and redoing your work.

**Pull request closed without merging**
