### PR TITLE
added sonja's advice and changed color on .mallory-advice (practice)

### PR DESCRIPTION
**Pull request by redsonjacode**
Just practicing!

### CODE REVIEW

**Comment by redsonjacode** [comment]
adding sonja's advice and styles!

**Comment by redrambles** [comment]
Hello @redsonjacode !

This looks good except for one tiny thing - looks like you changed a bit of the CSS that belongs to another student in the main css/style.css file. If you look at your change set [here](https://github.com/skillcrush/skillcrush-104/pull/2098/files#diff-6a6a912d0c7b55b537768da778032849R24) - you'll see that a change was made from 'blue' to 'green'. Please return the change to 'blue' as it was before, then save the file, and add and commit that change. Then push up your branch once more `git push origin practice`, and this will automatically update your pull request.

Then we should be all set to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by redsonjacode** [comment]
I did change it and I’m so sorry! I did that edit while watching the video and realized later that that was someone’s css!! I’ll change it back and request a pull again.

:)

On Aug 31, 2018, at 17:33, Ann Cascarano <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @redsonjacode<https://github.com/redsonjacode> !

This looks good except for one tiny thing - looks like you changed a bit of the CSS that belongs to another student in the main css/style.css file. If you look at your change set here<https://github.com/skillcrush/skillcrush-104/pull/2098/files#diff-6a6a912d0c7b55b537768da778032849R24> - you'll see that a change was made from 'blue' to 'green'. Please return the change to 'blue' as it was before, then save the file, and add and commit that change. Then push up your branch once more git push origin practice, and this will automatically update your pull request.

Then we should be all set to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by redsonjacode** [comment]
Let me know if I changed it back successfully or not.  Thanks a million!

**Comment by acodeinprogress** [comment]
Hey @redsonjacode,

I'm not seeing your update. Did you make sure to make it on your practice branch and push it to your practice branch?

xoxo,
Sharon

**Comment by redsonjacode** [comment]
I have made the change on my branch and merged it with master now.  Do I need to do a new pull request? There are conflicts I see (above) but I didn't get any merge conflicts on my terminal?  

I'm hopeful that in a few weeks' time I'll look back on all these exchanges and laugh at how simple my problems were -- at least that is what I hope!!  :)  Thanks for your patience.

**Comment by acodeinprogress** [comment]
Hey @redsonjacode,

In order for your changes to show up in this pull request, you'll need to push up your `practice` branch.

If you'd rather push your `master` branch, you'll need to submit a new pull request for that.

xoxo,
Sharon

**Comment by redsonjacode** [comment]
Ok - I hope this worked this time.  I'm going to do the whole exercise again for good measure.  :)

**Comment by redrambles** [comment]
Hey @redsonjacode ! 

I see that you've made a change, but it was made to your master branch instead of this practice branch. Can you merge master into practice and then push up your practice branch? Then we'll see the changes reflected here. :)

Let us know how it goes!

Cheers,
Ann

**Comment by redsonjacode** [comment]
I hope this worked.  I made the change to master and merged it to practice and pushed it up. 

Otherwise, do I win the prize for the most effort?  :) 

Although now I am second guessing and ready to just start over.  I got a message that the repo has more recent updates than my version and then I got this screen and had to close the box down because I couldn't do anything (not letting me type, etc.). 


screen shot 2018-09-12 at 10 13 20

**Comment by redrambles** [comment]
Hello @redsonjacode !

This box is 'vim' the terminal based text editor that is very powerful, but not very intuitive to use. Git will launch this editor when it needs additional information from you (such as confirming or creating a commit message). When Vim launches, you will want to type **i** for 'insert' so that you can type - though most of the time, the default commit message that Git provides is just fine. Then you'll want to hit the **esc** key to enter 'command' mode - followed by **:wq** for 'write' and 'quit' (the colon is also important).

You can change your default text editor if you want to - given that you are using a mac, you might want to consider 'nano' - which is another Terminal based editor but is much simpler to use, with directions on the page. The command for this would be:

`git config --global core.editor "nano"`

Try merging with upstream again and pushing up! :)

Cheers,
Ann

P.S - You get ALL the points for effort. :)

**Comment by redrambles** [comment]
Hey @redsonjacode,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
