### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by Empress3**
Hoping to add my advice - fingers crossed!

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Empress3 !

This is great - the only thing we need is a little styling. I see you are linking to a stylesheet named 'css/sarahbairstow-advice-style.css' from your advice file - but it wasn't included in your pull request. Perhaps you have it locally and it hasn't yet been added / committed and/or pushed?

Once you add your stylesheet, we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann

**Comment by Empress3** [comment]
Hi @redrambles,

Oops! I missed a step there. I've added, committed, and pushed the css file ("Missing stylesheet") - I don't need to create a new pull request, do I?

Thanks for your help!
Sarah

**Comment by redrambles** [comment]
Hey @Empress3 !

You're correct, no need to create a new pull request - we can keep working with this one!

This is almost ready to go - but it looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's. Once you make that change, you can add, commit, and push up your branch once more, which will automatically update your pull request.

Then we should be all set to merge in your code! :)

Let us know if you have any questions!

Cheers,
Ann

**Comment by Empress3** [comment]
@redrambles, oh goodness, you're right! I hope the third time's a charm - have deleted the other styles, committed, and pushed up the branch. Thanks for your patience :-)

**Comment by acodeinprogress** [comment]
Hey @Empress3,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
