### PR TITLE
advice has been changed

### PR DESCRIPTION
**Pull request by Shyhaf**
I have shared some hopefully cool insights.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Shyhaf ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Comment by Shyhaf** [comment]
Can I have one more day? Just been busy and forgot. :(

**Comment by redrambles** [comment]
Sure! :) I'm reopening. :)

**Comment by redrambles** [comment]
Hey @Shyhaf,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
