### PR TITLE
adding my own html and css

### PR DESCRIPTION
**Pull request by ksdevdesign**
advice additions

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @ksdevdesign,

This looks great! I just have a couple teensy requests before I merge this in.
1) We would like for you to include a link to your advice page in the index.html file.
2) It looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's. 

Once you make those changes, you can add, commit, and push and it'll join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @ksdevdesign,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 10 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by ksdevdesign** [comment]
Sorry! I was out of town for a week. I'll take care of it in the next day or two. Thanks!

-Kaylin

Sent from my iPhone

On Aug 27, 2017, at 5:24 PM, Sharon <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @ksdevdesign<https://github.com/ksdevdesign>,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 10 days, this pull request will be closed.

Let us know if you need any help!

xoxo,
Sharon

**Comment by ksdevdesign** [comment]
Should be good to go now?

**Comment by acodeinprogress** [comment]
Hey @ksdevdesign,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
