### PR TITLE
created mariea file

### PR DESCRIPTION
**Pull request by lmallpress**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @lmallpress,

This looks great! I have minor request for you before I can merge this in. We would like for you to include a link to your advice page in the index.html file. Once you do that, you can add, commit, and push. Your changes will join your pull request here.

Let me know if you need any help!

**Comment by lmallpress** [comment]
Hey Sharon,

I've added my link and submitted the pull request again.  Thank you!

**Comment by acodeinprogress** [comment]
Hey @lmallpress,

I just have one more change for you. Would you mind putting some ruby code in your ruby file? It could be as simple as putting a puts and quotes around your sentence.

**Comment by lmallpress** [comment]
Hi Sharon. I've made the change and submitted the request. Thank you!

**Comment by acodeinprogress** [comment]
Thanks for making those changes, @lmallpress! Your code is all merged in.

**Pull request merged**
