### PR TITLE
Adding Advice html and css

### PR DESCRIPTION
**Pull request by Amanda-Lilley**
This is my first forked repository!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Amanda-Lilley,

This looks great! I have one minor change for you before I merge this in. We would like for your Ruby file to be in the Ruby folder. If you move the file then run git add -A, commit, then push, your changes will join your pull request here. Then I can get it all merged in!

Let me know if you need any help!

**Comment by Amanda-Lilley** [comment]
I noticed there was already an amanda.rb file so I created an amandalilley.rb instead, placed it in the Ruby folder. I'm still not sure I have done this properly.

**Comment by acodeinprogress** [comment]
Hey @Amanda-Lilley, 
You're very close! All you need to do now is delete the amanda.rb file then run git add -A (don't forget the -A), commit, then push again. That should remove the file from the main directory.

**Comment by Amanda-Lilley** [comment]
Hi @acodeinprogress ,

Thanks for your help. Hopefully third time is a charm. 
Do I have to do a pull request every time I do git push to a forked repository? I did a pull request after the initial fork-edit-commit-push. I'm not sure if each time I make a change I continue to do a pull requests. Thanks again!

**Comment by acodeinprogress** [comment]
Great work, @Amanda-Lilley! Your code is all merged in.

**Pull request merged**
