### PR TITLE
Kweku's advice html, css and modified index

### PR DESCRIPTION
**Pull request by CyberLord-Alpha**
Hi,

Please discard previous pull. This one is kosher :)

As much comment, correction, suggestion, criticism, etc as you can send.
Thanks.

Regards,
Kweku.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @CyberLord-Alpha !

This is looking great - there is just one little issue - your custom stylesheet isn't loading. Can you see why? Let us know if you need a hint!

Cheers,
Ann

**Comment by CyberLord-Alpha** [comment]
Hi Ann,


Thank you for your reply.


I have just resolved a "merge conflict" on github. Earlier on I resolved the same conflict on my gitbash terminal before the pull request so didn't think the problem persisted. Many thanks.


Regarding my stylesheet not loading, I will hunt down the problem. It loads without problem on my local repo. I'll get in touch once it's done, or if I'm completely defeated.


Regards,

Kweku.

________________________________

**Comment by CyberLord-Alpha** [comment]
Hi Ann,


If the problem is with backing out into the right folder, ie changing

<link href="css/ka1-style.css" rel="stylesheet" type="text/css">


to

<link href="../css/ka1-style.css" rel="stylesheet" type="text/css">


I have already made that correction, cancelled the original pull request, and re-submitted. :)

Regards,

Kweku.






________________________________

**Comment by redrambles** [comment]
Hey @CyberLord-Alpha ,

Ok! This pull request's change set can be viewed [right here](https://github.com/skillcrush/skillcrush-104/pull/1992/files). You can see that the change to the css link is still there. You don't need to close this pull request and submit another one - you can just make the edit in your advice page while on your ka1-branch branch, then add and commit that change, and push up your ka1-branch again, which will update this pull request automatically.

Then we should be all set! Let us know if you have any questions!

Cheers,
Ann

**Comment by CyberLord-Alpha** [comment]
Hi Ann,


Thanks for direction. BTW where did this " right here<https://github.com/skillcrush/skillcrush-104/pull/1992/files>." come from? I looked for MY html on github all yesterday but all that kept coming up was the skillcrush-104 index html on that same page with the same heading.


Unless of course I submitted the skillcrush-104 index.html as my html. If that's the case how come the right one is there today?


I have followed the steps you outlined but keep getting the attached return. Any help?

Kweku.


________________________________

**Comment by acodeinprogress** [comment]
Hey @CyberLord-Alpha,

If you look near the top of this page, there's a tab called **Files changed**. That's where Ann got that link from.

If you sent a screenshot, it looks like it didn't upload properly so we're not able to see it. Could you send it to questions@skillcrush.com?

xoxo,
Sharon

**Comment by CyberLord-Alpha** [comment]
Hi Sharon,


Thank you for your email. Sorry my attachment didn't upload properly. I will resend to questions@skillcrush.com<mailto:questions@skillcrush.com> as directed.

Have a good day.


Regards,

Kweku.

________________________________

**Comment by redrambles** [comment]
Hey @CyberLord-Alpha,

Thanks for making those changes! You are all set to go - we have merged in your pull request. :)

Cheers,
Ann

**Pull request merged**
