### PR TITLE
Michelle's html and css

### PR DESCRIPTION
**Pull request by michelleisclever**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @michelleisclever,

This looks great. I only have 1 minor request for you. We would like for you to include a link to your HTML file in the index page. Once you add that in, you can add, commit, then push and your changes will join this pull request.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @michelleisclever,

This is very close! Instead of adding a link to your GitHub page, we'd like for you to add a link to your advice page in the index.html file in this project.

**Comment by michelleisclever** [comment]
Gah. Try now.

**Comment by acodeinprogress** [comment]
Hey @michelleisclever,

Thanks for making that change! It looks like your Back to Main Page link is going to your GitHub page. Instead, we want it to direct back to our index.html file.

**Comment by acodeinprogress** [comment]
Hey @michelleisclever,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 19 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @michelleisclever,

This is just a reminder that this pull request will close in 9 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @michelleisclever,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

**Comment by michelleisclever** [comment]
Sorry. I thought I completed the task

**Pull request closed without merging**
