### PR TITLE
advice changes

### PR DESCRIPTION
**Pull request by tnhn28**
I hope this works.  Please let me know if I screwed something else up:)

### CODE REVIEW

**Comment by tnhn28** [comment]
I think everything is fixed.  Please let me know if I have completely this lesson correctly.

**Comment by redrambles** [comment]
Hey @tnhn28!

Ok! This is a great start - there are still a few change that we need to see before we can merge in your code.

The first thing is that you renamed the 'advice/advice-template.html' to your file 'advice/tinahenry-advice.com' - but we need that template file to remain in the directory. It's fine if you save the file as yours (this makes a copy of the file, which you can save under a new name) - but if you directly rename the file, it is no longer available to other students.

If you take a look at your changeset [here](https://github.com/skillcrush/skillcrush-104/pull/2064/files), you'll see where this happened. We need you to restore the advice-template.html file to it's previous content - and to save a copy of that file for your advice file.

The styling that you added to the main stylesheet (css/style.css) is fine - and so is the link that you added to the main index.html file - we just need you to remove `css/tinahenry-style.css`, `tinahenry-advice.html` and `tinahenry-style.css`.

In the end you will have replaced the original template file, created an advice/tina-henryadvice.html file, and removed those three extra files I mentioned above - and you will be all set.

Once those changes are made, you'll need to add (`git add -A`), commit (`git commit -m "your message here"`) and then push up your branch once more (`git push origin advice-changes`) - which will automatically update your pull request.

Then we should be good to merge in your code!

Let us know if you need any help with this or if you have any questions!!

Cheers,
Ann :)

**Comment by tnhn28** [comment]
Sorry I messed things up for everyone.  I think I got everything done right, but it won’t push the file.  It says rejected because the remote contains work that you don’t have locally. What do I need to do?

**Comment by redrambles** [comment]
Hey @tnhn28,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
