### PR TITLE
Some minor changes from Ania

### PR DESCRIPTION
**Pull request by Ania-chan**
Ania's advice

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Ania-chan  !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in.

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Ania-chan** [comment]
I`ve fixed the main index.html film but now I'g getting message about branch conflicts which I cannot resolve :(

**Comment by Ania-chan** [comment]
I think I fixed the merge conflicts and its ok now :)

**Comment by acodeinprogress** [comment]
Hey @Ania-chan,

Unfortunately, it looks like you removed some other students code. We like to preserve everyone's code so you'll need to add that back in before we proceed.

The code that was removed was highlighted in pink if you click on the [Files Changed](https://github.com/skillcrush/skillcrush-104/pull/1723/files) tab near the top of this page.

Let us know if you need any help!

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @Ania-chan! 

You've opened a second pull request - which is nearly perfect! So I'm going to go ahead and close this one. :)

**Pull request closed without merging**
