### PR TITLE
Index and Advice File

### PR DESCRIPTION
**Pull request by HJRandolph**
Hello,

My pull request consists of two files: a change to Index.html adding the new file advice-hjrandolph.html. 

Thanks.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @HJRandolph,

It looks like you've pushed a merge conflict in your code. This is a great exercise as merge conflicts are not that uncommon!

I have 2 resources for you to help with fixing the conflict.
1) https://confluence.atlassian.com/bitbucket/resolve-merge-conflicts-704414003.html
2) https://www.udacity.com/course/how-to-use-git-and-github--ud775
Also, I don't see any custom CSS. If you could add some, that would be great!

Once you make those changes, you can add, commit, then push and your changes will join this pull request.

Let me know if you need any help!

**Comment by HJRandolph** [comment]
Hi @acodeinprogress 

I'm having trouble figuring out how to fix the conflicts. I have looked at the one of the sources you recommended, but not yet taken the class. 

How do I know where the conflicts are?

Thanks.

**Comment by HJRandolph** [comment]
I'm not sure that I've fixed the conflict(s). Would it be better if I
canceled the request and started anew?

**Comment by acodeinprogress** [comment]
Hey @HJRandolph,

It's up to you! You're welcome to close this pull request and start over. Or you could try fixing the conflicts. Merge conflicts are indicated by <<<<<<< HEAD and ============= and >>>>>>>>>>>. What you'll want to do is remove those and make sure that the document has everything that you want in it.

**Pull request closed without merging**
