### PR TITLE
updated html to link to new css file. css formating changes.

### PR DESCRIPTION
**Pull request by wzh0ng**

### CODE REVIEW

**Comment by wzh0ng** [comment]
updated

**Comment by wzh0ng** [comment]
made formatting changes

**Comment by redrambles** [comment]
Hey @wzh0ng !

This is great - we only need two little things addressed and then we'll be all set.

1. There is an extra file 'advice/advice-template copy.html' included in your pull request that we don't need. Please delete it.

2. We are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links and see if you can add one of your own!

Once you make these changes, add (git add -A) and commit (git commit -m "your message here") them and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by redrambles** [comment]
Hey @wzh0ng,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
