### PR TITLE
Personal changes

### PR DESCRIPTION
**Pull request by DemarisB**
added my personal changes

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @DemarisB,

Great job so far! I just have a couple small requests before we can merge this in.
1. It looks like you deleted other students CSS code in the main style.css file. We want to preserve everyones styles so we'd love for you to add those back in. You can see what was deleted by clicking on the [Files Changed](https://github.com/skillcrush/skillcrush-104/pull/1858/files) tab near the top of this page.
2. We'd like for you to add a link in the index.html file that goes to your advice page.

Once you make those changes, you can add, commit, and push and they'll join your pull request here.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @DemarisB,

Thanks so much for adding that CSS back in! Now there's just one more change to make!

You'll want to open up the index.html file in your text editor and add a link to your advice page. If you're not sure how to do this, feel free to take a look at other students links and see if you can add one of your own!

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @DemarisB ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @DemarisB ! 

I just accepted your second pull request, so I'm going to close this older one.

Congrats again! :)

Cheers,
Ann

**Pull request closed without merging**
