### PR TITLE
mike's advice when starting to code

### PR DESCRIPTION
**Pull request by mikedevpro**

### CODE REVIEW

**Comment by mikedevpro** [comment]
Just my little contribution to this project :)

**Comment by acodeinprogress** [comment]
Hey @mikedevpro,

Looks great so far! I see that you added your advice file within a new folder. We like to keep our repository as simple and clean as possible so we'd like for you to put your advice file directly in the advice folder and delete your extra folder.
It'd also be great if you could include a link to your advice page in the index.html file and create a personal stylesheet with some CSS for your advice page. 

Once you do that, you'll run a slightly different git command (git add -A), commit, and push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by mikedevpro** [comment]
Hi Sharon!

Thank you so much for your help!  I haven't even realized I made a
duplicate file, sorry about that.  I did create some CSS and also added the
link my advice page.  I think I did it right.

I do have another question.  I fell a little behind in my blueprint and I'm
only on Javascript right now.  I know I'm supposed to be on the Wordpress
part of the blueprint now but, I was wondering if I could start Wordpress
after I'm done with JavaScript.  I thank you again for all your help!

Mike

**Comment by acodeinprogress** [comment]
Hey @mikedevpro,

I'm not seeing any changes. Did you make sure to do your work on your repo branch and then push your changes to your repo branch on GitHub?

That's totally ok if you're behind! Skillcrush courses are self-paced so there's no rush!

xoxo,
Sharon

**Comment by mikedevpro** [comment]
I think I goofed.  I thought I had pushed and committed the changes.  I
keep getting an error message when I try to commit the changes.  I can
check to see I might've done wrong.

**Comment by acodeinprogress** [comment]
Hey @mikedevpro,

Can you share a screenshot of the error you're getting when you try to commit? You can email it to your blueprint email and we'll help you through there. :)

xoxo,
Sharon

**Comment by mikedevpro** [comment]
I think I'll try again.  I completely goofed, but I think I may have figured it out.  I can close this pull request.  I'll give it another shot :)

**Pull request closed without merging**
