### PR TITLE
Lenabalta advice

### PR DESCRIPTION
**Pull request by LenaEbb**

### CODE REVIEW

**Comment by LenaEbb** [comment]
OMG, I really tried, hopefully that does it... lol

**Comment by redrambles** [comment]
Hey @LenaEbb !

Hahaha - this is great! We just need you to add a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in.

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by LenaEbb** [comment]
Hello Ann,

This deal is beyond confusing hahaha I promise I’ll figure it out. 
I guess I’m not understanding which link I need to add. I thought you were talking about my css stylesheet, but that’s already there. 
Thanks,
Lena

**Comment by redrambles** [comment]
Hey @LenaEbb !

No worries - Git / GitHub can take a little GITTING used to! HAR HAR! See what I did there? 


Ok! So what I mean is that if you open up the main index.html file, you will see a looooooong list of links that point to each individual student advice page, so folks can click on them and read/enjoy! We need you to add yours to that list, and then we should be good to go. Let me know if this isn't clear or if you need any help! You got this!

Cheers,
Ann

**Pull request closed without merging**
