### PR TITLE
added my advice and modified the index file

### PR DESCRIPTION
**Pull request by chaudhryna**
Thanks for everything!

### CODE REVIEW

**Comment by redrambles** [comment]
Hello @chaudhryna !

This is great! We also need you to add some styling in the css/style.css stylesheet (which you are linking to in the `<head>` of your advice page) as well as a link to your advice page in the main index.html file, so that folks can find your words of wisdom once the pull request has been accepted.

Once you have made these two changes, add and commit them, and push up your experiments branch once more, which will automatically update this pull request (since it is based off of your experiments branch).

Then we should be good to merge in your code!

Let us know if you have any questions! :)

Cheers,
Ann

**Comment by chaudhryna** [comment]
Hi Ann,

Thank you for your email.

I did the styling.  It’s way at the bottom and the class is nancych-advice.

Please let me know if it’s ok.

Thank you,

Nancy

**Comment by acodeinprogress** [comment]
Hey @chaudhryna,

I hope you don't mind if I jump in here for Ann.

I see that you added the class to your HTML but there isn't any CSS to change how it looks. You can add some styles to the style.css file in the css folder.

We'll also need a link to your page to be added in the index.html file.

Once you do that, you can follow Ann's instructions for pushing your code up to GitHub and we'll be able to merge that in. :)

xoxo,
Sharon

**Comment by chaudhryna** [comment]
Hi,  

Ok.  I think I see the mistake I made the first time.  When I did the "git add" I ended up only adding one file.  I had already made the style change and the change to the index file but they didn't get added to the repo. 

Anyway, I think it should all be ready to go now.

Please let me know.  Thank you!

Nancy

**Comment by redrambles** [comment]
Hi @chaudhryna !

This is great! Thank you for making those changes, your code is merged in! :)

**Pull request merged**
