### PR TITLE
updated

### PR DESCRIPTION
**Pull request by DaMisFit2018**
some advice that would like to compare

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @DaMisFit2018,

I noticed that you didn't add any css. If you could add in some styles, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here. If no changes are made in 10 days, this pull request will close.

Let us know if you need any help!

xoxo,
Sharon

**Comment by DaMisFit2018** [comment]
ok i added the css thanks

**Comment by acodeinprogress** [comment]
Hey @DaMisFit2018,

I'm not seeing any changes on this branch (your **small** branch). It looks like you may have added your styles on your **experiment** branch. In order for your changes to show up on this pull request, you'll need to push them to this same branch.

Happy git-ing!

**Comment by acodeinprogress** [comment]
Hey @DaMisFit2018,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by DaMisFit2018** [comment]
hi, I'm sorry my computer crashed and i had to redo a whole bunch of stuff
on my computer, it's actually taken me a few days to get everything back
and running. I need to reinstall GIT on my machine. Will it still work with
the config i previously installed?

**Pull request closed without merging**
