### PR TITLE
Modifiche

### PR DESCRIPTION
**Pull request by guido-an**
Some advice to practice with GitHub

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @guido-an !

This is looking great - there's two tiny changes that we need from you in order to merge this in. 

1.  In the main index.html file, you made a change near line 14/15 where you added 'newtest'. If you could remove that and have it just say: `<h2>Advice for Newbies!</h2>` that would be awesome!

2. Still in the main index.html file - could you add a link at the bottom of the list to your Advice page? 

Then we'll be all set! Let us know if you have any questions or need any help.

Cheers!

**Comment by guido-an** [comment]
I did the changes and then write in the terminal the git add and git commit command. Is it ok?

**Comment by acodeinprogress** [comment]
Hey @guido-an,

Awesome! You just need to push up your code as the last step.

xoxo,
Sharon

**Comment by guido-an** [comment]
Hi Sharon,

Thank you for your help.

I wrote in the command line "git push -u origin master". Is it ok? 

Guido

**Comment by acodeinprogress** [comment]
Hey @guido-an,

You're super close! You'll make your changes on your modifiche branch on your computer, then add and commit. After that, you'll want to make sure that you push to your modifiche branch since that's what your pull request is for. You can do that by running **git push origin modifiche**.

Then your changes should show up in this pull request!

xoxo,
Sharon

**Comment by guido-an** [comment]
Hi Sharon,

Just did it!

how can I check if it is showing up in the pull request?

Guido

**Comment by acodeinprogress** [comment]
Hey @guido-an,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
