### PR TITLE
Advice from sam

### PR DESCRIPTION
**Pull request by EPIC448**
This was a fun project to work on. And it also has it challenges.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @EPIC448,

This is great! We'd still love it if you could add a link to your index.html file. Once you do that on your computer, you can add, commit, and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by EPIC448** [comment]
Hello Sharon,   
  Are you referring to linking my CSS folder to the HTML. I completed that. If that not the case, please elaborate. 

Cheers

**Comment by acodeinprogress** [comment]
Hey @EPIC448,

We have an index.html file where students add a link to their advice page. Are you in Skillcrush 104 or Skillcrush 105? I can link to the page where the instructions for this part of the assignment if you'd like.

xoxo,
Sharon

**Comment by EPIC448** [comment]
Hello Sharon,
   I am in Skillcrush 105,  things for the help. 


warm regards

**Pull request closed without merging**
