### PR TITLE
Jeanne's Advice 

### PR DESCRIPTION
**Pull request by JeanneEricksonCooley**
Advice I'd like to share about personal learning/working style.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @JeanneEricksonCooley,

Looking great so far! I have a few requests before we can merge this in.
1) It looks like you added another folder to the repo. We try to keep this as clean as possible so it would be great if you could delete that folder. You can do it right through your file manager.
2) We would like for you to include a link to your advice page in the index.html file. 

If you could make those changes, all you have to do is run a slightly different git command (git add -A), commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by JeanneEricksonCooley** [comment]
Sharon,

I think I took care of these problems. Please let me know if the updated index.html is there, and the extra 104 folder is gone. 

Thanks!

Jeanne

**Comment by acodeinprogress** [comment]
Hey @JeanneEricksonCooley,

It looks like you made those changes on your experiment branch, but this pull request is to merge in your master branch. You have a couple options here:
1) You can make those changes again but on your master branch and push them to your master branch.
2) You can close this pull request and open another one for your experiment branch.

I suggest option 2 but it's totally up to you!

xoxo,
Sharon

**Comment by JeanneEricksonCooley** [comment]
Sharon,

One last try? I merged my branch with my master, and pushed to my repo. I'm really hoping this did the trick. If not, I'll close this request and submit a pull request for my experiment branch. I kind of want to work myself out of whatever problem I created (I learn so much more this way).

Thanks!

Jeanne

**Comment by acodeinprogress** [comment]
Hey ,

Fantastic work! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif). Yay!


xoxo,
Sharon

**Comment by JeanneEricksonCooley** [comment]
Thank you so much, Sharon!

**Pull request merged**
