### PR TITLE
added Regina's Advice

### PR DESCRIPTION
**Pull request by ginabugac**
Some advice I would love to share

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @ginabugac,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @ginabugac,

It looks like we haven’t heard from you in a while. We’d love it if you would make the changes we requested above so we can get this all merged in! If no changes are made in 20 days, this pull request will be closed. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by ginabugac** [comment]
Hi Sharon,

I know I’m pretty far behind, but I’m determined to finish. I'm not exactly sure of what I did wrong on the 105 project, I added advice and css. I went through the steps again that explained how to push my local repo to GitHub.  It says everything up to date.

**Comment by acodeinprogress** [comment]
Hey @ginabugac,

Unfortunately, I'm not seeing those changes. I checked your other branches and could not find those changes as well. If you'd like some help, you can sign up for office hours which happen to be tonight (June 6) at 8:30pm ET or send an email to your blueprint email and we'll get this straightened out.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @ginabugac ,

We still haven't seen any changes. If no changes are made in 10 days, this pull request will be closed.

Let us know if you still need help!

xoxo,
Sharon

**Comment by ginabugac** [comment]
Okay. I'll work on this again and figure it out.

**Comment by ginabugac** [comment]
Hi Sharon,
I think I finally did it.  Will you let me know if any changes came through.

Thanks for your help.

**Comment by acodeinprogress** [comment]
Hey @ginabugac,

Unfortunately, I'm not seeing any updates. Could you send a screenshot of what you're doing?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @ginabugac,

It's been a while since we've heard from you and there still aren't any changes. I'm going to close this pull request for now. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
