### PR TITLE
added name file to ruby folder, updated advice page and stylesheet

### PR DESCRIPTION
**Pull request by TravisBrace**
yaaaay!

### CODE REVIEW

**Comment by TravisBrace** [comment]
added advice page and style sheets

**Comment by sareg0** [comment]
Hey Travis,

I see that you're committing a merge conflict in your code. 

Is this something you can fix up and push again to this pull request. Alternatively I can close the PR and you can take another stab at it.

**Comment by TravisBrace** [comment]
Oh! Let me take another look at that tonight

**Comment by TravisBrace** [comment]
I tried to delete the other commits but it says I need to be on a branch? Not sure if I had the option when setting up the pull request to choose, this was probably the case. The only ones that should be added are:

added name file to ruby folder d5c607f
advice page and style sheet 37f5184

If it's easier to delete that so I can set that up again I can. This is my first time doing a pull request! 

Thank you so much Sara!

**Comment by sareg0** [comment]
all good! It's just a learning. How about I close it all up, and you take another stab. Just follow the process again. Make sure to pull the SC repo to get the latest version, and see how you go :)

Don't hesitate to ask if you have any troubles :)

**Pull request closed without merging**
