### PR TITLE
Gary Spongebob added advice 

### PR DESCRIPTION
**Pull request by GarySpongebob**
Some advice for people just starting out in tech.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @GarySpongebob,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by GarySpongebob** [comment]
Hi Sharon,

Here's a screenshot of my actions. Does this look about right?

**Comment by acodeinprogress** [comment]
Hey @GarySpongebob!

Unfortunately, I'm not able to see a screenshot. Could you try including it again? Maybe give it a full minute to upload. If that still doesn't go through, you can try emailing it to us at questions@skillcrush.com.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @GarySpongebob ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
