### PR TITLE
My first pull request

### PR DESCRIPTION
**Pull request by FrancescaBambozzi**
Please, let my branches merge :)

### CODE REVIEW

**Comment by redrambles** [comment]
Hello @FrancescaBambozzi,

Ok! We need you to make a few changes before we can merge in your code. Your advice/advice-francesca.html file is great! The issue is that you performed a 'saved-as' for the main stylesheet (css/style.css) and renamed it 'css/style-francesca.css'. It's totally fine if you want to create a custom stylesheet for your advice page, but you will need to create a _new_ stylesheet in the css/ directory which will contain your styles - (and only your styles - not ALL the styles that are in the main stylesheet) - and then make sure to link to that custom stylesheet in your advice/advice-francesca.html advice file, so that they apply to your advice page.

We also need you to add a link in the main index.html file that will point to your advice page, so that folks can find your words of wisdom once your code has been merged into the main code base.

Here's what we need you to do:

1) We need you to restore the main stylesheet (css/style.css)
2) Either add your particular styles to the main stylesheet, or create a new custom stylesheet in the css/ directory and link to it from your advice page
3) Add a link in the main index.html file that will lead to your advice page

Once you have made those changes, you will want to use `git add -A`, followed by `git commit -m "your commit message here"` and then push up your branch once more `git push origin advice-page` which will automatically update your pull request. 

Let us know if you have any questions or run into any difficulties with this!

Cheers,
Ann

**Comment by redrambles** [comment]
Hello there!

Thanks for your changes. I see that you have added a custom stylesheet and have linked to it from your advice page, and that you have added a link to your advice page in the main index.html file. Great!

The only thing that remains is to delete the `css/style-francesca.css` file - that was once `css/style.css` - and place the original `css/style.css` main stylesheet back in the project. You can copy/paste the main stylesheet from the main code base.

Once that is done, we should be all good to merge in your code.

Let us know if you need any help with this.

Cheers,
Ann

**Comment by acodeinprogress** [comment]
Hey @FrancescaBambozzi,

This is getting closer! It looks like you deleted the main style.css stylesheet that contains everyone's styles. We definitely don't want to do that so we'll need to add it back in. You can copy and paste the code from the Skillcrush repo.

Once you do that, you'll want to add, commit, and push all your code again. Then we can go ahead and merge everything in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @FrancescaBambozzi,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to open a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
