### PR TITLE
Lesson Challenge: Submit a Pull Request

### PR DESCRIPTION
**Pull request by arufino**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @arufino!

Looks great! I only have 1 tiny request for you. We would like for your ruby file to be in the ruby folder. I also highly suggest renaming your file so that it's only lowercase. If you could move it over there and change the name, then run a slightly different git command (git add -A), commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by arufino** [comment]
Hi @acodeinprogress!
Thanks for the feedback! I think I should have deleted my old repo! It got very confusing! Could you please check if I've done it right now? I had to pull another request, I'm afraid :(

**Comment by acodeinprogress** [comment]
Hey @arufino,

It looks like you tried fixing a merge conflict but it didn't seem to work correctly. If you take a look at the Files Changed tab, you'll see that your Ruby file hasn't changed location or name and now the index file has a bunch of information added to it (as well as >>>>>>> upstream/master)

**Comment by arufino** [comment]
Hi @acodeinprogress,
Sorry, I didn't add the new pull request here!

**Pull request closed without merging**
