### PR TITLE
added styles

### PR DESCRIPTION
**Pull request by ginabugac**
This is my advice

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @ginabugac,

This looks great so far! I do have a couple requests before I can merge this in.
1) We'd like for you to add a link to your advice file in the index.html file.
2) You created a new advice-template and your own advice file in the main directory. Instead, you'll need to move your personal file to the advice folder and delete the advice-template that's in the main directory (don't delete the one in the advice folder).
Once you fix those up, you can run a slightly different git command (git add -A), commit, and push and your changes will join your pull request here. The reason we run git add -A is because it recognizes deleted files and will delete them from the repo. Don't worry, they'll still be in previous commits.

Let us know if you need any help!

xoxo,
Sharon

**Comment by ginabugac** [comment]
I made the changes, hope I did this correctly. I don't know why this has been so difficult for me.

**Comment by acodeinprogress** [comment]
Hey @ginabugac,

Unfortunately, I'm not seeing any changes. If you have questions about whether they've gone through or not, you can check the Files Changed tab on this page.
Are you making sure that you're making changes on your branch and pushing to your branch on GitHub? Meaning, are you making changes to your **changes** branch on your computer and then pushing your changes to your **changes** branch on GitHub?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @ginabugac,

Those changes went through! Your code is all merged in now.

xoxo,
Sharon

**Comment by ginabugac** [comment]
Woohoo! Finally.

**Pull request merged**
