### PR TITLE
add Nomi.rb file

### PR DESCRIPTION
**Pull request by nomi474**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @nomi474,

I have a few small requests for you before I can merge this in.
1) We would like for your ruby file to be in the ruby folder.
2) It looks like you added everyone's styles to your personal stylesheet. Since only your page will be accessing your stylesheet, you only need to include your personal styles. Once you fix that, you can add, commit, and push and your changes will join your pull request here.
3) If you take a look at the Files Changed tab, it shows that you changed the title and css link in the index page. We still want to keep that information. The only thing that you should change in the file should be adding a link to your advice page. The rest of the information should stay the same.
If you could make those changes, then run a slightly different git commit (git add -A), commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @nomi474,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 20 days if no changes are made.

**Comment by nomi474** [comment]
Hi Sharon,
Thanks for following up with me. I'll be submitting again soon with the modified changes.
Thanks.~Nauman

**Comment by acodeinprogress** [comment]
Hey @nomi474,

This is just a reminder that this pull request will be closed in 10 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @nomi474,

I'm going to close this pull request. Feel free to submit a new one when you're ready!

**Pull request closed without merging**
