### PR TITLE
Claire's page added

### PR DESCRIPTION
**Pull request by claire-ellen**
Added a page with advice from me :)

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @claire-ellen !

This is great! We'll just need you to add some CSS and a link to your advice page from the main index.html file, and we'll be good to merge in your code.

I see that you are link to a stylesheet at ../css/clairellenadvice-style.css - have you created this file? If so, it may be that it still needs to be added and committed. If you run `git status`, you will find out whether there are any files that have been modified and have yet to be committed. 

Once you have added your stylesheet in the /css directory and the link to your advice page in the main index.html file, go ahead and add and commit those changes and then push up your 'experiment' branch once more. This will automatically update your pull request, and we should be good to merge in your code! :)

Let us know if you have any questions!

Cheers,
Ann

**Comment by claire-ellen** [comment]
Thanks for looking out! I followed those steps, but I can't tell if anything happened.

**Comment by acodeinprogress** [comment]
Hey @claire-ellen,

I'm not seeing any of those changes either. Did you make sure that you were on your experiments branch and then pushed to your experiments branch on GitHub?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @claire-ellen,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
