### PR TITLE
advice html personalized

### PR DESCRIPTION
**Pull request by BluesBaka**
Here's my personalized advice page. Thanks!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @BluesBaka,

This looks great! I just have a few requests for you before I can merge this in.

1. We would like for your advice file to be in the advice folder.
2. I noticed that you didn't add any css. If you could add some in, that would be great!
3. We would also like for you to include a link to your advice page in the index.html file.

Once you do that, you'll need to run a slightly different git command (git add -A), commit, then push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by BluesBaka** [comment]
Hey Sharon,
I finished up and commited my changes- they're still on my advice branch. Do i need to merge my advice and master branches before I submit another pull request?

Thank you!

**Comment by acodeinprogress** [comment]
Hey @BluesBaka,

It looks like your pull request is for your master branch, so yes, your changes will need to be on that branch before they'll show up here.

xoxo,
Sharon

**Comment by BluesBaka** [comment]
Okay- I think I have it.

I'm starting to get more confused about my branch options...

**Comment by redrambles** [comment]
Hey @BluesBaka ,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
