### PR TITLE
sheryl-hodgson added

### PR DESCRIPTION
**Pull request by sherylhodgson**

### CODE REVIEW

**Comment by sareg0** [comment]
Hey @sherylhodgson I see that you have added a lot extra stuff to the index.html file that shouldn't be there.

Is there a reason you put all that stuff in there. It's commit 'e766076'

**Comment by sherylhodgson** [comment]
Hi there,

Oh dear!  Was I not supposed to include the links to everyone else's advice?  But just include my own advice? Lol!

Kind regards,
Sheryl

**Comment by sareg0** [comment]
hehe, no we don't want you to recommmit everyone's links again, just your new addition :)

Do you think you can fix it up, or should I close, and let you run through the process again?

**Comment by sherylhodgson** [comment]
I'll have a go at fixing it and if I get into trouble I'll let you know!!

Kind regards,
Sheryl

**Comment by sareg0** [comment]
Super! Yep, just give it a try. Don't worry we can always close the PR, and let you have another go from the beginning

**Comment by sareg0** [comment]
hey @sherylhodgson I'll close this one on up for now, but feel free to take another go at it.

You can create  fresh pull request whenever you're ready. Just make sure to bring your fork up to do date the repo as it currently stands. Let me know if you need help!

**Pull request closed without merging**
