### PR TITLE
Loanton

### PR DESCRIPTION
**Pull request by loanton**
Second try

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @loanton,

It looks like you deleted a bunch of other students files. We want to preserve everyones work so we'll need you to add those files back in. Once you do that, you can add, commit, and push and your changes will join your pull request here. Then we can get this merged in!

xoxo,
Sharon

**Comment by loanton** [comment]
Sorry, could you please clarify- did I delete .html files?  I can't for the life of me recall doing that...  
    On Monday, August 20, 2018, 4:48:43 PM MDT, Sharon <notifications@github.com> wrote:  
 
 
Hey @loanton,

It looks like you deleted a bunch of other students files. We want to preserve everyones work so we'll need you to add those files back in. Once you do that, you can add, commit, and push and your changes will join your pull request here. Then we can get this merged in!

xoxo,
Sharon

**Comment by loanton** [comment]
Did I get it now?

**Comment by redrambles** [comment]
Hey @loanton !

Ok - if you look at your [pull request over here](https://github.com/skillcrush/skillcrush-104/pull/2062/files) - you'll see that there are over 700 files that have been changed. We should only be seeing 3 files - your advice page, the file with your styles and the main index.html file that contains the link to your advice page.

Because it's very difficult at this point to find out exactly what went wrong here - my suggestion would be to temporarily place your advice page outside of the repository (say - on your Desktop somewhere) - and also your custom stylesheet, and delete this entire directory and clone it fresh from your forked copy on GitHub. 

Once you've done that - move into the repository using the Terminal (or Git Bash) and add a connection to the upstream remote:

`git remote add upstream git@github.com:skillcrush/skillcrush-104.git`

Then fetch from upstream:

`git fetch upstream`

and merge into master:

`git merge upstream/master`

Now let's create and move to a branch:

`git checkout -b advice`

And then move your advice page and css that you put aside on the Desktop into the /advice and /css directories. Then open up the main index.html file and add a link to your advice page.

Once that's done, add `git add -A`, commit `git commit -m "your message here"` and push up your branch: `git push origin advice`.

Now you'll be set to open up a new pull request - make sure to choose your 'advice' branch - and we should be all set to merge in your code.

**Comment by loanton** [comment]
Hi Ann,
Thanks for your reply.  I know that files were changed, but that should be because I added back the css files of the other students that I deleted.  Can you check if this is the case- as far as I know, the pull request should be good to go.  You can also see in the comments where Sharon had said that I should add back in the deleted files, maybe that will give some context.  If I am wrong about this, I'll do as you have suggested.  
Thank you,Anton
   On Friday, August 24, 2018, 1:28:13 PM MDT, Ann Cascarano <notifications@github.com> wrote:  
 
 
Hey @loanton !

Ok - if you look at your pull request over here - you'll see that there are over 700 files that have been changed. We should only be seeing 3 files - your advice page, the file with your styles and the main index.html file that contains the link to your advice page.

Because it's very difficult at this point to find out exactly what went wrong here - my suggestion would be to temporarily place your advice page outside of the repository (say - on your Desktop somewhere) - and also your custom stylesheet, and delete this entire directory and clone it fresh from your forked copy on GitHub.

Once you've done that - move into the repository using the Terminal (or Git Bash) and add a connection to the upstream remote:

git remote add upstream git@github.com:skillcrush/skillcrush-104.git

Then fetch from upstream:

git fetch upstream

and merge into master:

git merge upstream/master

Now let's create and move to a branch:

git checkout -b advice

And then move your advice page and css that you put aside on the Desktop into the /advice and /css directories. Then open up the main index.html file and add a link to your advice page.

Once that's done, add git add -A, commit git commit -m "your message here" and push up your branch: git push origin advice.

Now you'll be set to open up a new pull request - make sure to choose your 'advice' branch - and we should be all set to merge in your code.

**Comment by acodeinprogress** [comment]
Hey @loanton,

Sharon here! I would definitely recommend following Ann's advice. Something went amuck somewhere and we shouldn't be seeing all of these files. 

Go ahead and try out Ann's advice and let us know how it goes!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @loanton!

I just merged in your other pull request so I'm going to go ahead and close this one as well.

xoxo,
Sharon

**Pull request closed without merging**
