### PR TITLE
Rutsaandeel

### PR DESCRIPTION
**Pull request by oglikap**

### CODE REVIEW

**Comment by oglikap** [comment]
Hi, here the page I made for even more advice. Regards, Rutger

**Comment by acodeinprogress** [comment]
Hey @oglikap,

Looks great! I only have 2 requests for you.
1) We'd love for you to have a link to your advice page in the index.html file.
2) The css folder is only for css files. In order to include an image, instead of pushing it to GitHub, I would suggest hosting it on a site and then including an image tag in your html that links to your hosted image.
Once you make those changes, you can run git add -A (don't forget the -A), commit, and push. Your changes will join your pull request here.

Let me know if you need any help!

**Comment by oglikap** [comment]
Hi @acodeinprogress ,

Thanks for your comments! I removed the picture from the css-folder and linked the background-img to my website. And added a link to the index.html. Hope this helps!

**Comment by acodeinprogress** [comment]
Great job, @oglikap! Your code is all merged in.

**Pull request merged**
