### PR TITLE
Adding tyler-sherkin.rb

### PR DESCRIPTION
**Pull request by TOR-Warrax**
As subject.

### CODE REVIEW

**Comment by sareg0** [comment]
hi @TOR-Warrax I see that you added 'test.rb' and 'tyler-sherki.rb' to the main directory, instead of the 'ruby' folder of the repo.

Could I trouble you to please remove 'test.rb', and drop 'tyler-sherki.rb' into the 'ruby' folder, and then add, commit and push. Your changes will join the pull request here. 

Your third commit (e01a02e) looks great, so leave that stuff as it is :)

**Comment by TOR-Warrax** [comment]
Ah, that's where this is.  I thought this was on MightyBell for whatever reason.  Sorry about that, too many cloned repositories for class, got a little mixed up!

**Comment by acodeinprogress** [comment]
Hey @TOR-Warrax, it looks like it's been a couple weeks since this issue. Would you be able to make the changes that Sara suggested? Once you get the changes pushed to GitHub, I can go ahead and get your code merged in!

Let me know if you need any help! :)

**Comment by acodeinprogress** [comment]
Hi @TOR-Warrax, I went ahead and made the changes. Your code is all merged in now. Good work.

**Pull request merged**
