### PR TITLE
No Cure for Curiosity adding personal advice page

### PR DESCRIPTION
**Pull request by nocureforcuriosity**
No Cure for Curiosity adding personal advice page.

### CODE REVIEW

**Comment by nocureforcuriosity** [comment]
No Cure for Curiosity adding personal advice page.

**Comment by redrambles** [comment]
Hi @nocureforcuriosity !

This is looking great! We only need you to make a few little changes before we can merge this in. In the main index.html file - a student's link was accidentally duplicated - and there's a bit of white space that we need to remove. [You can see it here](https://github.com/skillcrush/skillcrush-104/pull/1990/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR24). Once you remove that extra line and the bit of whitespace, you'll need to add, commit and push up your personal-advice branch once more, which will automatically update this pull request.

Let us know if you have any questions and keep up the good work!!!

Cheers,
Ann

**Comment by nocureforcuriosity** [comment]
Thank you, Ann. Hope I made the changes correctly.

**Comment by acodeinprogress** [comment]
Hey @nocureforcuriosity,

This is close! It looks like there are some more duplicate lines of code. When we look at the [Files Changed](https://github.com/skillcrush/skillcrush-104/pull/1990/files) tab, we only want to see the line that we added highlighted in green:
`<a href="advice/nocureforcuriousity-advice.html">No Cure for Curiousity's Advice</a><br>`

In this case, the two lines associated with Kiara's advice are ok too. The red and green lines cancel each other out - meaning that you didn't add the line, you just altered it.

This means that these three lines are duplicates and should be removed:
`<a href="advice/mims-advice.html">Mims' advice</a><br>
<a href="advice/kansas-advice.html">Kansas' advice</a><br>
<a href="advice/rachelstephens-advice.html">Rachel's Advice</a><br>`

xoxo,
Sharon

**Comment by nocureforcuriosity** [comment]
Thanks, Sharon. Giving it another try!

**Comment by acodeinprogress** [comment]
Hey @nocureforcuriosity,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
