### PR TITLE
commiting craig-dunn.rb

### PR DESCRIPTION
**Pull request by craighdunn**

### CODE REVIEW

**Comment by craighdunn** [comment]
yes

**Comment by acodeinprogress** [comment]
Hey @craighdunn!

Looks great! I only have 1 tiny request for you. We would like for your ruby file to be in the ruby folder. If you could move it over there, then run git add -A, commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @craighdunn,

Looks like we haven't heard from you in a while. I want to let you know that this pull request will be closed in 10 days if no changes are made. Again, I'd be happy to help!

**Comment by acodeinprogress** [comment]
Hey @craighdunn, this pull request is now closed. Feel free to submit a new one when you're ready! :)

**Pull request closed without merging**
