### PR TITLE
This is a commit to my forked branch

### PR DESCRIPTION
**Pull request by giggidy2**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @giggidy2,

Looks great! I only have 2 tiny requests for you. 
1) **puts** should be all lowercase.
2) We would like for your Ruby file to be in the Ruby folder. 

If you could make those changes, then run git add -A, commit, then push, your changes will join your pull request here.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @giggidy2,

It looks like you removed the file in your last commit but it is still showing up on GitHub. You don't need to completely remove the file. You can simply move it to the ruby folder and edit the puts inside the file. The way to remove the file from the main directory is by running **git add -A**.

Let me know if you need any help!

**Comment by acodeinprogress** [comment]
Hey @giggidy2,

It looks like we haven't heard from you in a while. I just want to let you know that this pull request will be closed in 14 days if no changes are made.

**Comment by acodeinprogress** [comment]
Hey @giggidy2,

This is just a reminder that this pull request will close in 7 days if no changes are made.

**Comment by giggidy2** [comment]
Hi Sharon,

Thank you for keeping up on this. I have made those changes.  Do I need to
create a new pull request?

**Comment by acodeinprogress** [comment]
Hey @giggidy2,

No need for a new pull request. Your code is all merged in. Great work! :)

**Pull request merged**
