### PR TITLE
Zoeadvice

### PR DESCRIPTION
**Pull request by zoevons**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @zoevons,

Great job so far! I have a couple requests for you before I merge this in. 
1) It looks like you changed someone else's advice page in addition to adding in your own advice page. If you could undo those changes, that would be fantastic!
2) There are a lot of links that were removed from the index.html file in this pull request. We'd like for you to add those back in as well.

Once you make those changes, you can add, commit, and push and they'll join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by zoevons** [comment]
Yes sorry Sharon, I thought that had happened. It was also my other one I changed as I did this before in the Front End Developer Course.  Can I cancel it and start again?

**Comment by acodeinprogress** [comment]
Hey @zoevons,

Sure! You have a couple options:
1) You can close this pull request and open another one.
2) You can mark this assignment as complete since you've already done it in another class. Of course, if you want to do the assignment again for more experience, we won't stop you! :)

xoxo,
Sharon

**Comment by zoevons** [comment]
Excellent thank you Sharon, I just wanted to have another go to make sure I
was doing it correctly :)

**Pull request closed without merging**
