### PR TITLE
added Veronica file

### PR DESCRIPTION
**Pull request by varmstrong27**
I added a Veronica file. :)

### CODE REVIEW

**Comment by varmstrong27** [comment]
I added a Veronica advice page and css

**Comment by acodeinprogress** [comment]
Hey @varmstrong27, it looks like you committed your ruby file to the main directory of the repo and you have some additional files that end with ~. If you could remove those extra files and move your ruby file to the ruby folder on your computer, then run git add -A, commit, and push the changes, it should join the pull request here.

Let me know if you need any help!

**Comment by varmstrong27** [comment]
Thank you for your help. Hopefully, I fixed it now.

**Comment by acodeinprogress** [comment]
Hey @varmstrong27. There's still one little stray file: css/style.css~. If you could remove that, then run git add -A, commit, and push again, I'll get everything merged in. Great job deleting and moving your other files!!!

**Comment by varmstrong27** [comment]
Doh! I deleted that last file. Hope it works now. Thanks again for your help. :)

**Comment by acodeinprogress** [comment]
Hey @varmstrong27, it's all merged now! Great work!

**Pull request merged**
