### PR TITLE
advice page push practice

### PR DESCRIPTION
**Pull request by jenjarsbutterfly**
practice

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @jenjarsbutterfly,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by jenjarsbutterfly** [comment]
I think it is a mistake. I'm pretty sure I did add an advice page with CSS.

**Comment by acodeinprogress** [comment]
Hey @jenjarsbutterfly,

If you take a look at the [Files Changed](https://github.com/skillcrush/skillcrush-104/pull/2023/files) tab near the top of this page, it tells us exactly what was changed on this branch. As you can see, only the index.html file was changed.

Is it possible that you made those changes later and either didn't add or commit or push them up to your experiments branch?

xoxo,
Sharon

**Comment by jenjarsbutterfly** [comment]
Did you see any changes?

**Comment by acodeinprogress** [comment]
Hey @jenjarsbutterfly,

Yep! It looks like your changes went through. There are just a couple more things that we'll need to change:
1. It looks like you added all of the styles from the main style.css stylesheet into your custom stylesheet. All you need in there are your personal styles, so you can remove everyone else's.
2. In the index.html file, you changed `<link rel="stylesheet" type="text/css" href="css/style.css" />` to link to your personal stylesheet (`<link rel="stylesheet" type="text/css" href="css/jennyj-advice.css" />`) instead of the main style.css file. Instead, we want this page to use our main style.css stylesheet.

Once you make those changes, you can add, commit, and push and they'll update this pull request.

xoxo,
Sharon

**Comment by jenjarsbutterfly** [comment]
I didn't. I made a copy of style.css and add my personal CSS there and then
rename the file. The original style.css does not have my CSS. That's why
you see these.

**Comment by jenjarsbutterfly** [comment]
I will work on them and get them to you later.

**Comment by acodeinprogress** [comment]
Hey @jenjarsbutterfly,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
